package org.kp.BTLfindBenefitPackage.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-18T12:52:09.380-07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "BenefitBundlePackageService", 
                  wsdlLocation = "file:/C:/Miei/Eclipse_Workspaces/SpringInAction/cfx_java2wsdl_wsdl2java/webroot/WEB-INF/wsdl/findBenefitPackage.wsdl",
                  targetNamespace = "http://Benefit_libs/BTLMediator/BenefitBundlePackageIntf") 
public class BenefitBundlePackageService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Benefit_libs/BTLMediator/BenefitBundlePackageIntf", "BenefitBundlePackageService");
    public final static QName BenefitBundlePackageServicePort = new QName("http://Benefit_libs/BTLMediator/BenefitBundlePackageIntf", "BenefitBundlePackageServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Miei/Eclipse_Workspaces/SpringInAction/cfx_java2wsdl_wsdl2java/webroot/WEB-INF/wsdl/findBenefitPackage.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BenefitBundlePackageService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Miei/Eclipse_Workspaces/SpringInAction/cfx_java2wsdl_wsdl2java/webroot/WEB-INF/wsdl/findBenefitPackage.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BenefitBundlePackageService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BenefitBundlePackageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BenefitBundlePackageService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BenefitBundlePackageInterf
     */
    @WebEndpoint(name = "BenefitBundlePackageServicePort")
    public BenefitBundlePackageInterf getBenefitBundlePackageServicePort() {
        return super.getPort(BenefitBundlePackageServicePort, BenefitBundlePackageInterf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BenefitBundlePackageInterf
     */
    @WebEndpoint(name = "BenefitBundlePackageServicePort")
    public BenefitBundlePackageInterf getBenefitBundlePackageServicePort(WebServiceFeature... features) {
        return super.getPort(BenefitBundlePackageServicePort, BenefitBundlePackageInterf.class, features);
    }

}
