
package org.kp.BTLfindBenefitPackage.server;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-18T12:52:09.349-07:00
 * Generated source version: 2.4.1
 * 
 */
 
public class BenefitBundlePackageInterf_BenefitBundlePackageServicePort_Server{

    protected BenefitBundlePackageInterf_BenefitBundlePackageServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BenefitBundlePackageInterfImpl();
        String address = "http://127.0.0.1:8080/cfx_java2wsdl_wsdl2java/ws/findBenefitPackage";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new BenefitBundlePackageInterf_BenefitBundlePackageServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
