package org.kp.BTLfindBenefitPackage.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-18T12:52:09.302-07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://Benefit_libs/BTLMediator/BenefitBundlePackageIntf", name = "BenefitBundlePackageInterf")
@XmlSeeAlso({ObjectFactory.class})
public interface BenefitBundlePackageInterf {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findBenefitPackage", targetNamespace = "http://Benefit_libs/BTLMediator/BenefitBundlePackageIntf", className = "org.kp.BTLfindBenefitPackage.server.FindBenefitPackage")
    @WebMethod
    @ResponseWrapper(localName = "findBenefitPackageResponse", targetNamespace = "http://Benefit_libs/BTLMediator/BenefitBundlePackageIntf", className = "org.kp.BTLfindBenefitPackage.server.FindBenefitPackageResponse")
    public java.lang.String findBenefitPackage(
        @WebParam(name = "Benefitbundle", targetNamespace = "")
        java.util.List<org.kp.BTLfindBenefitPackage.server.BenefitBundle> benefitbundle
    );
}
