
package org.kp.BTLfindBenefitPackage.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-18T12:52:09.177-07:00
 * Generated source version: 2.4.1
 * 
 */
public final class BenefitBundlePackageInterf_BenefitBundlePackageServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://Benefit_libs/BTLMediator/BenefitBundlePackageIntf", "BenefitBundlePackageService");

    private BenefitBundlePackageInterf_BenefitBundlePackageServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BenefitBundlePackageService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BenefitBundlePackageService ss = new BenefitBundlePackageService(wsdlURL, SERVICE_NAME);
        BenefitBundlePackageInterf port = ss.getBenefitBundlePackageServicePort();  
        
        {
        System.out.println("Invoking findBenefitPackage...");
        java.util.List<org.kp.BTLfindBenefitPackage.server.BenefitBundle> _findBenefitPackage_benefitbundle = null;
        java.lang.String _findBenefitPackage__return = port.findBenefitPackage(_findBenefitPackage_benefitbundle);
        System.out.println("findBenefitPackage.result=" + _findBenefitPackage__return);


        }

        System.exit(0);
    }

}
