package com.habuma.spitter.remoting.jaxws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-12-05T16:44:42.146-08:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", name = "SpitterService")
@XmlSeeAlso({ObjectFactory.class})
public interface SpitterService {

    @WebResult(name = "spitterObject", targetNamespace = "")
    @RequestWrapper(localName = "retrieveSpitterById", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.RetrieveSpitterById")
    @WebMethod
    @ResponseWrapper(localName = "retrieveSpitterByIdResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.RetrieveSpitterByIdResponse")
    public com.habuma.spitter.remoting.jaxws.server.Spitter retrieveSpitterById(
        @WebParam(name = "spitterInputId", targetNamespace = "")
        long spitterInputId
    );

    @WebResult(name = "spitterObject", targetNamespace = "")
    @RequestWrapper(localName = "retrieveSpitterByFullName", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.RetrieveSpitterByFullName")
    @WebMethod
    @ResponseWrapper(localName = "retrieveSpitterByFullNameResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.RetrieveSpitterByFullNameResponse")
    public com.habuma.spitter.remoting.jaxws.server.Spitter retrieveSpitterByFullName(
        @WebParam(name = "spitterInputFullName", targetNamespace = "")
        java.lang.String spitterInputFullName
    );

    @WebResult(name = "spittleObject", targetNamespace = "")
    @RequestWrapper(localName = "retrieveSpittle", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.RetrieveSpittle")
    @WebMethod
    @ResponseWrapper(localName = "retrieveSpittleResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.RetrieveSpittleResponse")
    public com.habuma.spitter.remoting.jaxws.server.Spittle retrieveSpittle(
        @WebParam(name = "spittleInputId", targetNamespace = "")
        long spittleInputId
    );
}
