package com.habuma.spitter.remoting.jaxws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-14T13:48:06.029-07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", name = "SpitterServiceEndpointInterf")
@XmlSeeAlso({ObjectFactory.class})
public interface SpitterServiceEndpointInterf {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSpittlesForSpitter", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpittlesForSpitter")
    @WebMethod
    @ResponseWrapper(localName = "getSpittlesForSpitterResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpittlesForSpitterResponse")
    public java.util.List<com.habuma.spitter.remoting.jaxws.server.Spittle> getSpittlesForSpitter(
        @WebParam(name = "spitter", targetNamespace = "")
        com.habuma.spitter.remoting.jaxws.server.Spitter spitter
    );

    @RequestWrapper(localName = "addSpittle", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.AddSpittle")
    @WebMethod
    @ResponseWrapper(localName = "addSpittleResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.AddSpittleResponse")
    public void addSpittle(
        @WebParam(name = "spittle", targetNamespace = "")
        com.habuma.spitter.remoting.jaxws.server.Spittle spittle
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRecentSpittles", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetRecentSpittles")
    @WebMethod
    @ResponseWrapper(localName = "getRecentSpittlesResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetRecentSpittlesResponse")
    public java.util.List<com.habuma.spitter.remoting.jaxws.server.Spittle> getRecentSpittles(
        @WebParam(name = "spittleCount", targetNamespace = "")
        int spittleCount
    );

    @RequestWrapper(localName = "deleteSpittle", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.DeleteSpittle")
    @WebMethod
    @ResponseWrapper(localName = "deleteSpittleResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.DeleteSpittleResponse")
    public void deleteSpittle(
        @WebParam(name = "spittleId", targetNamespace = "")
        long spittleId
    );
}
