
package com.habuma.spitter.remoting.jaxws.server;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-10-07T13:57:32.874-07:00
 * Generated source version: 2.4.1
 * 
 */
 
public class SpitterService_SpitterServiceEndpointPort_Server{

    protected SpitterService_SpitterServiceEndpointPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        //Object implementor = new SpitterServiceImpl();
        String address = "http://127.0.0.1:8080/SpitterService/ws/spitterService";
        //Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SpitterService_SpitterServiceEndpointPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
