package com.habuma.spitter.remoting.jaxws.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-23T15:35:15.980-07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "SpitterService", 
                  wsdlLocation = "file:/C:/Miei/Eclipse_Workspaces/SpringInAction/SpringInActionChapter10_remoting-jax-ws_SpringBeanAutowiringSupport/webroot/WEB-INF/wsdl/SpitterService.wsdl",
                  targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService") 
public class SpitterService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", "SpitterService");
    public final static QName SpitterServiceEndpointPort = new QName("http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", "SpitterServiceEndpointPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Miei/Eclipse_Workspaces/SpringInAction/SpringInActionChapter10_remoting-jax-ws_SpringBeanAutowiringSupport/webroot/WEB-INF/wsdl/SpitterService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SpitterService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Miei/Eclipse_Workspaces/SpringInAction/SpringInActionChapter10_remoting-jax-ws_SpringBeanAutowiringSupport/webroot/WEB-INF/wsdl/SpitterService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SpitterService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SpitterService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpitterService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SpitterService
     */
    @WebEndpoint(name = "SpitterServiceEndpointPort")
    public SpitterService getSpitterServiceEndpointPort() {
        return super.getPort(SpitterServiceEndpointPort, SpitterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpitterService
     */
    @WebEndpoint(name = "SpitterServiceEndpointPort")
    public SpitterService getSpitterServiceEndpointPort(WebServiceFeature... features) {
        return super.getPort(SpitterServiceEndpointPort, SpitterService.class, features);
    }

}
