package com.habuma.spitter.remoting.jaxws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-16T13:50:52.644-07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", name = "SpitterServiceEndpointInterf")
@XmlSeeAlso({ObjectFactory.class})
public interface SpitterServiceEndpointInterf {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSpittleById", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpittleById")
    @WebMethod
    @ResponseWrapper(localName = "getSpittleByIdResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpittleByIdResponse")
    public com.habuma.spitter.remoting.jaxws.server.Spittle getSpittleById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSpittlesForSpitter", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpittlesForSpitter")
    @WebMethod
    @ResponseWrapper(localName = "getSpittlesForSpitterResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpittlesForSpitterResponse")
    public java.util.List<com.habuma.spitter.remoting.jaxws.server.Spittle> getSpittlesForSpitter(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "saveSpitter", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.SaveSpitter")
    @WebMethod
    @ResponseWrapper(localName = "saveSpitterResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.SaveSpitterResponse")
    public void saveSpitter(
        @WebParam(name = "arg0", targetNamespace = "")
        com.habuma.spitter.remoting.jaxws.server.Spitter arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSpittlesForSpitterBySpitter", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpittlesForSpitterBySpitter")
    @WebMethod
    @ResponseWrapper(localName = "getSpittlesForSpitterBySpitterResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpittlesForSpitterBySpitterResponse")
    public java.util.List<com.habuma.spitter.remoting.jaxws.server.Spittle> getSpittlesForSpitterBySpitter(
        @WebParam(name = "arg0", targetNamespace = "")
        com.habuma.spitter.remoting.jaxws.server.Spitter arg0
    );

    @RequestWrapper(localName = "saveSpittle", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.SaveSpittle")
    @WebMethod
    @ResponseWrapper(localName = "saveSpittleResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.SaveSpittleResponse")
    public void saveSpittle(
        @WebParam(name = "arg0", targetNamespace = "")
        com.habuma.spitter.remoting.jaxws.server.Spittle arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRecentSpittles", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetRecentSpittles")
    @WebMethod
    @ResponseWrapper(localName = "getRecentSpittlesResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetRecentSpittlesResponse")
    public java.util.List<com.habuma.spitter.remoting.jaxws.server.Spittle> getRecentSpittles(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllSpitters", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetAllSpitters")
    @WebMethod
    @ResponseWrapper(localName = "getAllSpittersResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetAllSpittersResponse")
    public java.util.List<com.habuma.spitter.remoting.jaxws.server.Spitter> getAllSpitters();

    @RequestWrapper(localName = "deleteSpittle", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.DeleteSpittle")
    @WebMethod
    @ResponseWrapper(localName = "deleteSpittleResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.DeleteSpittleResponse")
    public void deleteSpittle(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSpitter", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpitter")
    @WebMethod
    @ResponseWrapper(localName = "getSpitterResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpitterResponse")
    public com.habuma.spitter.remoting.jaxws.server.Spitter getSpitter(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSpitterById", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpitterById")
    @WebMethod
    @ResponseWrapper(localName = "getSpitterByIdResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpitterByIdResponse")
    public com.habuma.spitter.remoting.jaxws.server.Spitter getSpitterById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @RequestWrapper(localName = "startFollowing", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.StartFollowing")
    @WebMethod
    @ResponseWrapper(localName = "startFollowingResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.StartFollowingResponse")
    public void startFollowing(
        @WebParam(name = "arg0", targetNamespace = "")
        com.habuma.spitter.remoting.jaxws.server.Spitter arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.habuma.spitter.remoting.jaxws.server.Spitter arg1
    );
}
