package com.habuma.spitter.remoting.jaxws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-10-07T13:57:32.639-07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", name = "SpitterService")
@XmlSeeAlso({ObjectFactory.class})
public interface SpitterService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSpitterById", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpitterById")
    @WebMethod
    @ResponseWrapper(localName = "getSpitterByIdResponse", targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/SpitterService", className = "com.habuma.spitter.remoting.jaxws.server.GetSpitterByIdResponse")
    public com.habuma.spitter.remoting.jaxws.server.Spitter getSpitterById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );
}
