
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.habuma.spitter.remoting.jaxws.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-18T16:29:19.993-07:00
 * Generated source version: 2.4.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SpitterService",
                      portName = "SpitterServiceEndpointPort",
                      targetNamespace = "http://pippo/SpitterService",
                      wsdlLocation = "file:/C:/Miei/Eclipse_Workspaces/SpringInAction/SpringInActionChapter10_remoting-jax-ws_SpringBeanAutowiringSupport/webroot/WEB-INF/wsdl/SpitterService.wsdl",
                      endpointInterface = "com.habuma.spitter.remoting.jaxws.server.SpitterServiceEndpointInterf")
                      
public class SpitterServiceEndpointInterfImpl implements SpitterServiceEndpointInterf {

    private static final Logger LOG = Logger.getLogger(SpitterServiceEndpointInterfImpl.class.getName());

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.server.SpitterServiceEndpointInterf#getSpittlesForSpitter(com.habuma.spitter.remoting.jaxws.server.Spitter  spitter )*
     */
    public java.util.List<com.habuma.spitter.remoting.jaxws.server.Spittle> getSpittlesForSpitter(com.habuma.spitter.remoting.jaxws.server.Spitter spitter) { 
        LOG.info("Executing operation getSpittlesForSpitter");
        System.out.println(spitter);
        try {
            java.util.List<com.habuma.spitter.remoting.jaxws.server.Spittle> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.server.SpitterServiceEndpointInterf#addSpittle(com.habuma.spitter.remoting.jaxws.server.Spittle  spittle )*
     */
    public void addSpittle(com.habuma.spitter.remoting.jaxws.server.Spittle spittle) { 
        LOG.info("Executing operation addSpittle");
        System.out.println(spittle);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.server.SpitterServiceEndpointInterf#deleteSpittle(long  arg0 )*
     */
    public void deleteSpittle(long arg0) { 
        LOG.info("Executing operation deleteSpittle");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.server.SpitterServiceEndpointInterf#getRecentSpittles(int  spittleCount )*
     */
    public java.util.List<com.habuma.spitter.remoting.jaxws.server.Spittle> getRecentSpittles(int spittleCount) { 
        LOG.info("Executing operation getRecentSpittles");
        System.out.println(spittleCount);
        try {
            java.util.List<com.habuma.spitter.remoting.jaxws.server.Spittle> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
