
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.habuma.spitter.remoting.jaxws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-08-17T15:04:54.653-07:00
 * Generated source version: 2.4.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SpitterService",
                      portName = "SpitterServiceEndpointPort",
                      targetNamespace = "http://SEI.jaxws.remoting.spitter.habuma.com/",
                      wsdlLocation = "file:/C:/Miei/Eclipse_Workspaces/SpringInAction/SpringInActionChapter10_remoting-jax-ws_SpringBeanAutowiringSupport/webroot/WEB-INF/wsdl/SpitterService.wsdl",
                      endpointInterface = "com.habuma.spitter.remoting.jaxws.SpitterServiceEndpoint")
                      
public class SpitterServiceEndpointImpl implements SpitterServiceEndpoint {

    private static final Logger LOG = Logger.getLogger(SpitterServiceEndpointImpl.class.getName());

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.SpitterServiceEndpoint#getSpittleById(long  arg0 )*
     */
    public com.habuma.spitter.remoting.jaxws.Spittle getSpittleById(long arg0) { 
        LOG.info("Executing operation getSpittleById");
        System.out.println(arg0);
        try {
            com.habuma.spitter.remoting.jaxws.Spittle _return = new com.habuma.spitter.remoting.jaxws.Spittle();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.SpitterServiceEndpoint#getSpitter(long  arg0 )*
     */
    public com.habuma.spitter.remoting.jaxws.Spitter getSpitter(long arg0) { 
        LOG.info("Executing operation getSpitter");
        System.out.println(arg0);
        try {
            com.habuma.spitter.remoting.jaxws.Spitter _return = new com.habuma.spitter.remoting.jaxws.Spitter();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.SpitterServiceEndpoint#startFollowing(com.habuma.spitter.remoting.jaxws.Spitter  arg0 ,)com.habuma.spitter.remoting.jaxws.Spitter  arg1 )*
     */
    public void startFollowing(com.habuma.spitter.remoting.jaxws.Spitter arg0,com.habuma.spitter.remoting.jaxws.Spitter arg1) { 
        LOG.info("Executing operation startFollowing");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.SpitterServiceEndpoint#saveSpittle(com.habuma.spitter.remoting.jaxws.Spittle  arg0 )*
     */
    public void saveSpittle(com.habuma.spitter.remoting.jaxws.Spittle arg0) { 
        LOG.info("Executing operation saveSpittle");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.SpitterServiceEndpoint#getSpittlesForSpitter(com.habuma.spitter.remoting.jaxws.Spitter  arg0 )*
     */
    public java.util.List<com.habuma.spitter.remoting.jaxws.Spittle> getSpittlesForSpitter(com.habuma.spitter.remoting.jaxws.Spitter arg0) { 
        LOG.info("Executing operation getSpittlesForSpitter");
        System.out.println(arg0);
        try {
            java.util.List<com.habuma.spitter.remoting.jaxws.Spittle> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.SpitterServiceEndpoint#getRecentSpittles(int  arg0 )*
     */
    public java.util.List<com.habuma.spitter.remoting.jaxws.Spittle> getRecentSpittles(int arg0) { 
        LOG.info("Executing operation getRecentSpittles");
        System.out.println(arg0);
        try {
            java.util.List<com.habuma.spitter.remoting.jaxws.Spittle> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.SpitterServiceEndpoint#getAllSpitters(*
     */
    public java.util.List<com.habuma.spitter.remoting.jaxws.Spitter> getAllSpitters() { 
        LOG.info("Executing operation getAllSpitters");
        try {
            java.util.List<com.habuma.spitter.remoting.jaxws.Spitter> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.habuma.spitter.remoting.jaxws.SpitterServiceEndpoint#deleteSpittle(long  arg0 )*
     */
    public void deleteSpittle(long arg0) { 
        LOG.info("Executing operation deleteSpittle");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
