package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.util.*;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BatchTransactionType generated by hbm2java
 */
@Entity
@Table(name="BATCH_TRANSACTION_TYPE"
    ,schema="DORIS"
)
public class BatchTransactionType extends Base.BaseEntity implements java.io.Serializable {


     private String transactionType;
     private String description;

    public BatchTransactionType() {
    }

	
    public BatchTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    public BatchTransactionType(String transactionType, String description) {
       this.transactionType = transactionType;
       this.description = description;
    }
   
     @Id 
    
    @Column(name="TRANSACTION_TYPE", nullable=false, length=2)
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


