package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.*;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchMessage generated by hbm2java
 */
@Entity
@Table(name="BATCH_MESSAGE"
    ,schema="DORIS"
)
public class BatchMessage extends Base.BaseEntity implements java.io.Serializable {


     private BigDecimal seqMessageId;
     private BatchMaster batchMaster;
     private BigDecimal transactionId;
     private BigDecimal additionalKey;
     private BigDecimal messageId;
     private char messageType;
     private String messageText;
     private String keyId1;
     private String keyId2;
     private String keyId3;
     private String keyId4;
     private String keyId5;
     private String keyId6;
     private String keyId7;
     private String keyId8;
     private String keyId9;
     private String keyId10;
     private String keyId11;
     private String keyId12;
     private String keyId13;
     private String keyId14;
     private String keyId15;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;

    public BatchMessage() {
    }

	
    public BatchMessage(BigDecimal seqMessageId, BatchMaster batchMaster, BigDecimal transactionId, BigDecimal additionalKey, BigDecimal messageId, char messageType) {
        this.seqMessageId = seqMessageId;
        this.batchMaster = batchMaster;
        this.transactionId = transactionId;
        this.additionalKey = additionalKey;
        this.messageId = messageId;
        this.messageType = messageType;
    }
    public BatchMessage(BigDecimal seqMessageId, BatchMaster batchMaster, BigDecimal transactionId, BigDecimal additionalKey, BigDecimal messageId, char messageType, String messageText, String keyId1, String keyId2, String keyId3, String keyId4, String keyId5, String keyId6, String keyId7, String keyId8, String keyId9, String keyId10, String keyId11, String keyId12, String keyId13, String keyId14, String keyId15, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess) {
       this.seqMessageId = seqMessageId;
       this.batchMaster = batchMaster;
       this.transactionId = transactionId;
       this.additionalKey = additionalKey;
       this.messageId = messageId;
       this.messageType = messageType;
       this.messageText = messageText;
       this.keyId1 = keyId1;
       this.keyId2 = keyId2;
       this.keyId3 = keyId3;
       this.keyId4 = keyId4;
       this.keyId5 = keyId5;
       this.keyId6 = keyId6;
       this.keyId7 = keyId7;
       this.keyId8 = keyId8;
       this.keyId9 = keyId9;
       this.keyId10 = keyId10;
       this.keyId11 = keyId11;
       this.keyId12 = keyId12;
       this.keyId13 = keyId13;
       this.keyId14 = keyId14;
       this.keyId15 = keyId15;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
    }
   
     @Id 
    
    @Column(name="SEQ_MESSAGE_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getSeqMessageId() {
        return this.seqMessageId;
    }
    
    public void setSeqMessageId(BigDecimal seqMessageId) {
        this.seqMessageId = seqMessageId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BATCH_ID", nullable=false)
    public BatchMaster getBatchMaster() {
        return this.batchMaster;
    }
    
    public void setBatchMaster(BatchMaster batchMaster) {
        this.batchMaster = batchMaster;
    }
    
    @Column(name="TRANSACTION_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(BigDecimal transactionId) {
        this.transactionId = transactionId;
    }
    
    @Column(name="ADDITIONAL_KEY", nullable=false, precision=22, scale=0)
    public BigDecimal getAdditionalKey() {
        return this.additionalKey;
    }
    
    public void setAdditionalKey(BigDecimal additionalKey) {
        this.additionalKey = additionalKey;
    }
    
    @Column(name="MESSAGE_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(BigDecimal messageId) {
        this.messageId = messageId;
    }
    
    @Column(name="MESSAGE_TYPE", nullable=false, length=1)
    public char getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(char messageType) {
        this.messageType = messageType;
    }
    
    @Column(name="MESSAGE_TEXT", length=256)
    public String getMessageText() {
        return this.messageText;
    }
    
    public void setMessageText(String messageText) {
        this.messageText = messageText;
    }
    
    @Column(name="KEY_ID_1", length=40)
    public String getKeyId1() {
        return this.keyId1;
    }
    
    public void setKeyId1(String keyId1) {
        this.keyId1 = keyId1;
    }
    
    @Column(name="KEY_ID_2", length=40)
    public String getKeyId2() {
        return this.keyId2;
    }
    
    public void setKeyId2(String keyId2) {
        this.keyId2 = keyId2;
    }
    
    @Column(name="KEY_ID_3", length=40)
    public String getKeyId3() {
        return this.keyId3;
    }
    
    public void setKeyId3(String keyId3) {
        this.keyId3 = keyId3;
    }
    
    @Column(name="KEY_ID_4", length=40)
    public String getKeyId4() {
        return this.keyId4;
    }
    
    public void setKeyId4(String keyId4) {
        this.keyId4 = keyId4;
    }
    
    @Column(name="KEY_ID_5", length=40)
    public String getKeyId5() {
        return this.keyId5;
    }
    
    public void setKeyId5(String keyId5) {
        this.keyId5 = keyId5;
    }
    
    @Column(name="KEY_ID_6", length=40)
    public String getKeyId6() {
        return this.keyId6;
    }
    
    public void setKeyId6(String keyId6) {
        this.keyId6 = keyId6;
    }
    
    @Column(name="KEY_ID_7", length=40)
    public String getKeyId7() {
        return this.keyId7;
    }
    
    public void setKeyId7(String keyId7) {
        this.keyId7 = keyId7;
    }
    
    @Column(name="KEY_ID_8", length=40)
    public String getKeyId8() {
        return this.keyId8;
    }
    
    public void setKeyId8(String keyId8) {
        this.keyId8 = keyId8;
    }
    
    @Column(name="KEY_ID_9", length=40)
    public String getKeyId9() {
        return this.keyId9;
    }
    
    public void setKeyId9(String keyId9) {
        this.keyId9 = keyId9;
    }
    
    @Column(name="KEY_ID_10", length=40)
    public String getKeyId10() {
        return this.keyId10;
    }
    
    public void setKeyId10(String keyId10) {
        this.keyId10 = keyId10;
    }
    
    @Column(name="KEY_ID_11", length=40)
    public String getKeyId11() {
        return this.keyId11;
    }
    
    public void setKeyId11(String keyId11) {
        this.keyId11 = keyId11;
    }
    
    @Column(name="KEY_ID_12", length=40)
    public String getKeyId12() {
        return this.keyId12;
    }
    
    public void setKeyId12(String keyId12) {
        this.keyId12 = keyId12;
    }
    
    @Column(name="KEY_ID_13", length=40)
    public String getKeyId13() {
        return this.keyId13;
    }
    
    public void setKeyId13(String keyId13) {
        this.keyId13 = keyId13;
    }
    
    @Column(name="KEY_ID_14", length=40)
    public String getKeyId14() {
        return this.keyId14;
    }
    
    public void setKeyId14(String keyId14) {
        this.keyId14 = keyId14;
    }
    
    @Column(name="KEY_ID_15", length=40)
    public String getKeyId15() {
        return this.keyId15;
    }
    
    public void setKeyId15(String keyId15) {
        this.keyId15 = keyId15;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }




}


