package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.util.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchMaster generated by hbm2java
 */
@Entity
@Table(name="BATCH_MASTER"
    ,schema="DORIS"
)
public class BatchMaster extends Base.BaseEntity implements java.io.Serializable {


     private String batchId;
     private BatchStatus batchStatus;
     private BatchTransactionType transactionType;
     private TradingPartnerMaster tradingPartnerMaster;
     private String x12ControlNumber;
     private String comments;
     private Date receivedDatetime;
     private String receivedUser;
     private Date finalizeDatetime;
     private String finalizeUser;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private Set<BatchMessage> batchMessages = new HashSet<BatchMessage>(0);

    public BatchMaster() {
    }

	
    public BatchMaster(String batchId, BatchStatus batchStatus, BatchTransactionType transactionType, TradingPartnerMaster tradingPartnerMaster) {
        this.batchId = batchId;
        this.batchStatus = batchStatus;
        this.transactionType = transactionType;
        this.tradingPartnerMaster = tradingPartnerMaster;
    }
    public BatchMaster(String batchId, BatchStatus batchStatus, BatchTransactionType transactionType, TradingPartnerMaster tradingPartnerMaster, String x12ControlNumber, String comments, Date receivedDatetime, String receivedUser, Date finalizeDatetime, String finalizeUser, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, Set<BatchMessage> batchMessages) {
       this.batchId = batchId;
       this.batchStatus = batchStatus;
       this.transactionType = transactionType;
       this.tradingPartnerMaster = tradingPartnerMaster;
       this.x12ControlNumber = x12ControlNumber;
       this.comments = comments;
       this.receivedDatetime = receivedDatetime;
       this.receivedUser = receivedUser;
       this.finalizeDatetime = finalizeDatetime;
       this.finalizeUser = finalizeUser;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.batchMessages = batchMessages;
    }
   
     @Id 
    
    @Column(name="BATCH_ID", nullable=false, length=9)
    public String getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public BatchStatus getBatchStatus() {
        return this.batchStatus;
    }
    
    public void setBatchStatus(BatchStatus batchStatus) {
        this.batchStatus = batchStatus;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TRANSACTION_TYPE", nullable=false)
    public BatchTransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(BatchTransactionType transactionType) {
        this.transactionType = transactionType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TRADING_PARTNER_ID", nullable=false)
    public TradingPartnerMaster getTradingPartnerMaster() {
        return this.tradingPartnerMaster;
    }
    
    public void setTradingPartnerMaster(TradingPartnerMaster tradingPartnerMaster) {
        this.tradingPartnerMaster = tradingPartnerMaster;
    }
    
    @Column(name="X12_CONTROL_NUMBER", length=9)
    public String getX12ControlNumber() {
        return this.x12ControlNumber;
    }
    
    public void setX12ControlNumber(String x12ControlNumber) {
        this.x12ControlNumber = x12ControlNumber;
    }
    
    @Column(name="COMMENTS", length=256)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="RECEIVED_DATETIME", length=7)
    public Date getReceivedDatetime() {
        return this.receivedDatetime;
    }
    
    public void setReceivedDatetime(Date receivedDatetime) {
        this.receivedDatetime = receivedDatetime;
    }
    
    @Column(name="RECEIVED_USER", length=8)
    public String getReceivedUser() {
        return this.receivedUser;
    }
    
    public void setReceivedUser(String receivedUser) {
        this.receivedUser = receivedUser;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FINALIZE_DATETIME", length=7)
    public Date getFinalizeDatetime() {
        return this.finalizeDatetime;
    }
    
    public void setFinalizeDatetime(Date finalizeDatetime) {
        this.finalizeDatetime = finalizeDatetime;
    }
    
    @Column(name="FINALIZE_USER", length=8)
    public String getFinalizeUser() {
        return this.finalizeUser;
    }
    
    public void setFinalizeUser(String finalizeUser) {
        this.finalizeUser = finalizeUser;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="batchMaster")
    public Set<BatchMessage> getBatchMessages() {
        return this.batchMessages;
    }
    
    public void setBatchMessages(Set<BatchMessage> batchMessages) {
        this.batchMessages = batchMessages;
    }



  // The following is extra code specified in the hbm.xml files

			
                private Set<StageBenefPackageMstr> stagedBenefitPackageMasterSet  = new HashSet<StageBenefPackageMstr>(0); ;

				@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="batchMaster")
			    public Set<StageBenefPackageMstr> getStagedBenefitPackageMasterSet() {
			        return this.stagedBenefitPackageMasterSet;
			    }
			    
			    public void setStagedBenefitPackageMasterSet(Set<StageBenefPackageMstr> stagedBenefitPackageMasterSet) {
			        this.stagedBenefitPackageMasterSet = stagedBenefitPackageMasterSet;
			    }  
			    
			    
                private Set<StageGroupMaster> stagedGroupMasterSet  = new HashSet<StageGroupMaster>(0); ;

				@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="batchMaster")
			    public Set<StageGroupMaster> getStagedGroupMasterSet() {
			        return this.stagedGroupMasterSet;
			    }
			    
			    public void setStagedGroupMasterSet(Set<StageGroupMaster> stagedGroupMasterSet) {
			        this.stagedGroupMasterSet = stagedGroupMasterSet;
			    }  			    
			    
			    
			
  // end of extra code specified in the hbm.xml files

}


