package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.*;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BenefitRuleMaint generated by hbm2java
 */
@Entity
@Table(name="BENEFIT_RULE_MAINT"
    ,schema="DORIS"
)
public class BenefitRuleMaint extends Base.BaseEntity implements java.io.Serializable {


     private BigDecimal seqBenefitRuleMaintId;
     private BenefitPackageDetail benefitPackageDetail;
     private BenefitRule brule;
     private String type;
     private char operator;
     private String fromValue;
     private String thruValue;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private String riderContractFrom;
     private String riderContractThru;

    public BenefitRuleMaint() {
    }

	
    public BenefitRuleMaint(BigDecimal seqBenefitRuleMaintId, BenefitPackageDetail benefitPackageDetail, BenefitRule brule, String type, char operator, String fromValue) {
        this.seqBenefitRuleMaintId = seqBenefitRuleMaintId;
        this.benefitPackageDetail = benefitPackageDetail;
        this.brule = brule;
        this.type = type;
        this.operator = operator;
        this.fromValue = fromValue;
    }
    public BenefitRuleMaint(BigDecimal seqBenefitRuleMaintId, BenefitPackageDetail benefitPackageDetail, BenefitRule brule, String type, char operator, String fromValue, String thruValue, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, String riderContractFrom, String riderContractThru) {
       this.seqBenefitRuleMaintId = seqBenefitRuleMaintId;
       this.benefitPackageDetail = benefitPackageDetail;
       this.brule = brule;
       this.type = type;
       this.operator = operator;
       this.fromValue = fromValue;
       this.thruValue = thruValue;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.riderContractFrom = riderContractFrom;
       this.riderContractThru = riderContractThru;
    }
   
     @Id 
    
    @Column(name="SEQ_BENEFIT_RULE_MAINT_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getSeqBenefitRuleMaintId() {
        return this.seqBenefitRuleMaintId;
    }
    
    public void setSeqBenefitRuleMaintId(BigDecimal seqBenefitRuleMaintId) {
        this.seqBenefitRuleMaintId = seqBenefitRuleMaintId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="BENEFIT_PACKAGE_ID", referencedColumnName="BENEFIT_PACKAGE_ID", nullable=false), 
        @JoinColumn(name="SEQ_BEN_PACKAGE", referencedColumnName="SEQ_BEN_PACKAGE", nullable=false) } )
    public BenefitPackageDetail getBenefitPackageDetail() {
        return this.benefitPackageDetail;
    }
    
    public void setBenefitPackageDetail(BenefitPackageDetail benefitPackageDetail) {
        this.benefitPackageDetail = benefitPackageDetail;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BENEFIT_RULE", nullable=false)
    public BenefitRule getBrule() {
        return this.brule;
    }
    
    public void setBrule(BenefitRule brule) {
        this.brule = brule;
    }
    
    @Column(name="TYPE", nullable=false, length=1)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="OPERATOR", nullable=false, length=1)
    public char getOperator() {
        return this.operator;
    }
    
    public void setOperator(char operator) {
        this.operator = operator;
    }
    
    @Column(name="FROM_VALUE", nullable=false, length=10)
    public String getFromValue() {
        return this.fromValue;
    }
    
    public void setFromValue(String fromValue) {
        this.fromValue = fromValue;
    }
    
    @Column(name="THRU_VALUE", length=10)
    public String getThruValue() {
        return this.thruValue;
    }
    
    public void setThruValue(String thruValue) {
        this.thruValue = thruValue;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="RIDER_CONTRACT_FROM", length=10)
    public String getRiderContractFrom() {
        return this.riderContractFrom;
    }
    
    public void setRiderContractFrom(String riderContractFrom) {
        this.riderContractFrom = riderContractFrom;
    }
    
    @Column(name="RIDER_CONTRACT_THRU", length=10)
    public String getRiderContractThru() {
        return this.riderContractThru;
    }
    
    public void setRiderContractThru(String riderContractThru) {
        this.riderContractThru = riderContractThru;
    }




}


