package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.util.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BenefitPackageDetail generated by hbm2java
 */
@Entity
@Table(name="BENEFIT_PACKAGE_DETAIL"
    ,schema="DORIS"
)
public class BenefitPackageDetail extends Base.BaseEntity implements java.io.Serializable {


     private BenefitPackageDetailId id;
     private BenefitPackageMaster benefitPackageMaster;
     private BenefitRule brule;
     private Date startDate;
     private Date endDate;
     private Character parProvReq;
     private Character authReq;
     private String riderReqFilter;
     private Character supDepRule;
     private Short noMosContFrom;
     private Short noMosContThru;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private int processingOrder;
     private String riderOperator;
     private Character adjustForOcPaid;
     private String parOperator;
     private String authOperator;
     private Character applyPar;
     private Character authLevel;
     private Character applyRider;
     private String weightedValueAccum;
     private String applyPatlib;
     private Integer seqAlbenId;
     private String patientLiabCompareInd;
     private String applyContractType;
     private Character altSchedId;
     private String reasonCode;
     private String crossAccum;
     private String applyClmInd1;
     private String applyClmInd2;
     private Set<BenefitRuleMaint> benefitRuleMaints = new HashSet<BenefitRuleMaint>(0);

    public BenefitPackageDetail() {
    }

	
    public BenefitPackageDetail(BenefitPackageDetailId id, BenefitPackageMaster benefitPackageMaster, BenefitRule brule, int processingOrder) {
        this.id = id;
        this.benefitPackageMaster = benefitPackageMaster;
        this.brule = brule;
        this.processingOrder = processingOrder;
    }
    public BenefitPackageDetail(BenefitPackageDetailId id, BenefitPackageMaster benefitPackageMaster, BenefitRule brule, Date startDate, Date endDate, Character parProvReq, Character authReq, String riderReqFilter, Character supDepRule, Short noMosContFrom, Short noMosContThru, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, int processingOrder, String riderOperator, Character adjustForOcPaid, String parOperator, String authOperator, Character applyPar, Character authLevel, Character applyRider, String weightedValueAccum, String applyPatlib, Integer seqAlbenId, String patientLiabCompareInd, String applyContractType, Character altSchedId, String reasonCode, String crossAccum, String applyClmInd1, String applyClmInd2, Set<BenefitRuleMaint> benefitRuleMaints) {
       this.id = id;
       this.benefitPackageMaster = benefitPackageMaster;
       this.brule = brule;
       this.startDate = startDate;
       this.endDate = endDate;
       this.parProvReq = parProvReq;
       this.authReq = authReq;
       this.riderReqFilter = riderReqFilter;
       this.supDepRule = supDepRule;
       this.noMosContFrom = noMosContFrom;
       this.noMosContThru = noMosContThru;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.processingOrder = processingOrder;
       this.riderOperator = riderOperator;
       this.adjustForOcPaid = adjustForOcPaid;
       this.parOperator = parOperator;
       this.authOperator = authOperator;
       this.applyPar = applyPar;
       this.authLevel = authLevel;
       this.applyRider = applyRider;
       this.weightedValueAccum = weightedValueAccum;
       this.applyPatlib = applyPatlib;
       this.seqAlbenId = seqAlbenId;
       this.patientLiabCompareInd = patientLiabCompareInd;
       this.applyContractType = applyContractType;
       this.altSchedId = altSchedId;
       this.reasonCode = reasonCode;
       this.crossAccum = crossAccum;
       this.applyClmInd1 = applyClmInd1;
       this.applyClmInd2 = applyClmInd2;
       this.benefitRuleMaints = benefitRuleMaints;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="benefitPackageId", column=@Column(name="BENEFIT_PACKAGE_ID", nullable=false, length=8) ), 
        @AttributeOverride(name="seqBenPackage", column=@Column(name="SEQ_BEN_PACKAGE", nullable=false, precision=9, scale=0) ) } )
    public BenefitPackageDetailId getId() {
        return this.id;
    }
    
    public void setId(BenefitPackageDetailId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BENEFIT_PACKAGE_ID", nullable=false, insertable=false, updatable=false)
    public BenefitPackageMaster getBenefitPackageMaster() {
        return this.benefitPackageMaster;
    }
    
    public void setBenefitPackageMaster(BenefitPackageMaster benefitPackageMaster) {
        this.benefitPackageMaster = benefitPackageMaster;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BENEFIT_RULE", nullable=false)
    public BenefitRule getBrule() {
        return this.brule;
    }
    
    public void setBrule(BenefitRule brule) {
        this.brule = brule;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=7)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=7)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
    @Column(name="PAR_PROV_REQ", length=1)
    public Character getParProvReq() {
        return this.parProvReq;
    }
    
    public void setParProvReq(Character parProvReq) {
        this.parProvReq = parProvReq;
    }
    
    @Column(name="AUTH_REQ", length=1)
    public Character getAuthReq() {
        return this.authReq;
    }
    
    public void setAuthReq(Character authReq) {
        this.authReq = authReq;
    }
    
    @Column(name="RIDER_REQ_FILTER", length=20)
    public String getRiderReqFilter() {
        return this.riderReqFilter;
    }
    
    public void setRiderReqFilter(String riderReqFilter) {
        this.riderReqFilter = riderReqFilter;
    }
    
    @Column(name="SUP_DEP_RULE", length=1)
    public Character getSupDepRule() {
        return this.supDepRule;
    }
    
    public void setSupDepRule(Character supDepRule) {
        this.supDepRule = supDepRule;
    }
    
    @Column(name="NO_MOS_CONT_FROM", precision=3, scale=0)
    public Short getNoMosContFrom() {
        return this.noMosContFrom;
    }
    
    public void setNoMosContFrom(Short noMosContFrom) {
        this.noMosContFrom = noMosContFrom;
    }
    
    @Column(name="NO_MOS_CONT_THRU", precision=3, scale=0)
    public Short getNoMosContThru() {
        return this.noMosContThru;
    }
    
    public void setNoMosContThru(Short noMosContThru) {
        this.noMosContThru = noMosContThru;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="PROCESSING_ORDER", nullable=false, precision=7, scale=0)
    public int getProcessingOrder() {
        return this.processingOrder;
    }
    
    public void setProcessingOrder(int processingOrder) {
        this.processingOrder = processingOrder;
    }
    
    @Column(name="RIDER_OPERATOR", length=2)
    public String getRiderOperator() {
        return this.riderOperator;
    }
    
    public void setRiderOperator(String riderOperator) {
        this.riderOperator = riderOperator;
    }
    
    @Column(name="ADJUST_FOR_OC_PAID", length=1)
    public Character getAdjustForOcPaid() {
        return this.adjustForOcPaid;
    }
    
    public void setAdjustForOcPaid(Character adjustForOcPaid) {
        this.adjustForOcPaid = adjustForOcPaid;
    }
    
    @Column(name="PAR_OPERATOR", length=2)
    public String getParOperator() {
        return this.parOperator;
    }
    
    public void setParOperator(String parOperator) {
        this.parOperator = parOperator;
    }
    
    @Column(name="AUTH_OPERATOR", length=2)
    public String getAuthOperator() {
        return this.authOperator;
    }
    
    public void setAuthOperator(String authOperator) {
        this.authOperator = authOperator;
    }
    
    @Column(name="APPLY_PAR", length=1)
    public Character getApplyPar() {
        return this.applyPar;
    }
    
    public void setApplyPar(Character applyPar) {
        this.applyPar = applyPar;
    }
    
    @Column(name="AUTH_LEVEL", length=1)
    public Character getAuthLevel() {
        return this.authLevel;
    }
    
    public void setAuthLevel(Character authLevel) {
        this.authLevel = authLevel;
    }
    
    @Column(name="APPLY_RIDER", length=1)
    public Character getApplyRider() {
        return this.applyRider;
    }
    
    public void setApplyRider(Character applyRider) {
        this.applyRider = applyRider;
    }
    
    @Column(name="WEIGHTED_VALUE_ACCUM", length=8)
    public String getWeightedValueAccum() {
        return this.weightedValueAccum;
    }
    
    public void setWeightedValueAccum(String weightedValueAccum) {
        this.weightedValueAccum = weightedValueAccum;
    }
    
    @Column(name="APPLY_PATLIB", length=1)
    public String getApplyPatlib() {
        return this.applyPatlib;
    }
    
    public void setApplyPatlib(String applyPatlib) {
        this.applyPatlib = applyPatlib;
    }
    
    @Column(name="SEQ_ALBEN_ID", precision=9, scale=0)
    public Integer getSeqAlbenId() {
        return this.seqAlbenId;
    }
    
    public void setSeqAlbenId(Integer seqAlbenId) {
        this.seqAlbenId = seqAlbenId;
    }
    
    @Column(name="PATIENT_LIAB_COMPARE_IND", length=1)
    public String getPatientLiabCompareInd() {
        return this.patientLiabCompareInd;
    }
    
    public void setPatientLiabCompareInd(String patientLiabCompareInd) {
        this.patientLiabCompareInd = patientLiabCompareInd;
    }
    
    @Column(name="APPLY_CONTRACT_TYPE", length=1)
    public String getApplyContractType() {
        return this.applyContractType;
    }
    
    public void setApplyContractType(String applyContractType) {
        this.applyContractType = applyContractType;
    }
    
    @Column(name="ALT_SCHED_ID", length=1)
    public Character getAltSchedId() {
        return this.altSchedId;
    }
    
    public void setAltSchedId(Character altSchedId) {
        this.altSchedId = altSchedId;
    }
    
    @Column(name="REASON_CODE", length=5)
    public String getReasonCode() {
        return this.reasonCode;
    }
    
    public void setReasonCode(String reasonCode) {
        this.reasonCode = reasonCode;
    }
    
    @Column(name="CROSS_ACCUM", length=1)
    public String getCrossAccum() {
        return this.crossAccum;
    }
    
    public void setCrossAccum(String crossAccum) {
        this.crossAccum = crossAccum;
    }
    
    @Column(name="APPLY_CLM_IND_1", length=1)
    public String getApplyClmInd1() {
        return this.applyClmInd1;
    }
    
    public void setApplyClmInd1(String applyClmInd1) {
        this.applyClmInd1 = applyClmInd1;
    }
    
    @Column(name="APPLY_CLM_IND_2", length=1)
    public String getApplyClmInd2() {
        return this.applyClmInd2;
    }
    
    public void setApplyClmInd2(String applyClmInd2) {
        this.applyClmInd2 = applyClmInd2;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="benefitPackageDetail")
    public Set<BenefitRuleMaint> getBenefitRuleMaints() {
        return this.benefitRuleMaints;
    }
    
    public void setBenefitRuleMaints(Set<BenefitRuleMaint> benefitRuleMaints) {
        this.benefitRuleMaints = benefitRuleMaints;
    }




}


