package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BenefitPackageMaster generated by hbm2java
 */
@Entity
@Table(name="BENEFIT_PACKAGE_MASTER"
    ,schema="DORIS"
)
public class BenefitPackageMaster extends Base.BaseEntity implements java.io.Serializable {


     private String benefitPackageId;
     private String shortDescription;
     private String narrative;
     private Short subPeNotCovDays;
     private Short subPeConditnDays;
     private Short depPeNotCovDays;
     private Short depPeConditnDays;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private int seqProcessingOrderId;
     private Character applyPatlibTo;
     private Character patientLiability;
     private BigDecimal patlibPercent;
     private Date userDate1;
     private Date userDate2;
     private Date userDate3;
     private Date userDate4;
     private Date userDate5;
     private Date userDate6;
     private Date userDate7;
     private Date userDate8;
     private Date userDate9;
     private Date userDate10;
     private Date userDate11;
     private Date userDate12;
     private Date userDate13;
     private Date userDate14;
     private Date userDate15;
     private Date userDate16;
     private Date userDate17;
     private Date userDate18;
     private Date userDate19;
     private Date userDate20;
     private String userDefined1;
     private String userDefined2;
     private String userDefined3;
     private String userDefined4;
     private String userDefined5;
     private String userDefined6;
     private String userDefined7;
     private String userDefined8;
     private String userDefined9;
     private String userDefined10;
     private String userDefined11;
     private String userDefined12;
     private String userDefined13;
     private String userDefined14;
     private String userDefined15;
     private String userDefined16;
     private String userDefined17;
     private String userDefined18;
     private String userDefined19;
     private String userDefined20;
     private String packageType;
     private Integer seqAlbenId;
     private String patientLiabComparison;
     private String patientLiabType1;
     private String patientLiabType2;
     private String altSchedId;
     private String altRegionId;
     private Character modifSearchOrder;
     private String mappingString;
     private Set<CobBankBenef> cobBankBenefs = new HashSet<CobBankBenef>(0);
     private Set<BenefitPackageDetail> benefitPackageDetails = new HashSet<BenefitPackageDetail>(0);
     private Set<PremiumMaster> premiumMasters = new HashSet<PremiumMaster>(0);

    public BenefitPackageMaster() {
    }

	
    public BenefitPackageMaster(String benefitPackageId, String shortDescription, int seqProcessingOrderId) {
        this.benefitPackageId = benefitPackageId;
        this.shortDescription = shortDescription;
        this.seqProcessingOrderId = seqProcessingOrderId;
    }
    public BenefitPackageMaster(String benefitPackageId, String shortDescription, String narrative, Short subPeNotCovDays, Short subPeConditnDays, Short depPeNotCovDays, Short depPeConditnDays, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, int seqProcessingOrderId, Character applyPatlibTo, Character patientLiability, BigDecimal patlibPercent, Date userDate1, Date userDate2, Date userDate3, Date userDate4, Date userDate5, Date userDate6, Date userDate7, Date userDate8, Date userDate9, Date userDate10, Date userDate11, Date userDate12, Date userDate13, Date userDate14, Date userDate15, Date userDate16, Date userDate17, Date userDate18, Date userDate19, Date userDate20, String userDefined1, String userDefined2, String userDefined3, String userDefined4, String userDefined5, String userDefined6, String userDefined7, String userDefined8, String userDefined9, String userDefined10, String userDefined11, String userDefined12, String userDefined13, String userDefined14, String userDefined15, String userDefined16, String userDefined17, String userDefined18, String userDefined19, String userDefined20, String packageType, Integer seqAlbenId, String patientLiabComparison, String patientLiabType1, String patientLiabType2, String altSchedId, String altRegionId, Character modifSearchOrder, String mappingString, Set<CobBankBenef> cobBankBenefs, Set<BenefitPackageDetail> benefitPackageDetails, Set<PremiumMaster> premiumMasters) {
       this.benefitPackageId = benefitPackageId;
       this.shortDescription = shortDescription;
       this.narrative = narrative;
       this.subPeNotCovDays = subPeNotCovDays;
       this.subPeConditnDays = subPeConditnDays;
       this.depPeNotCovDays = depPeNotCovDays;
       this.depPeConditnDays = depPeConditnDays;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.seqProcessingOrderId = seqProcessingOrderId;
       this.applyPatlibTo = applyPatlibTo;
       this.patientLiability = patientLiability;
       this.patlibPercent = patlibPercent;
       this.userDate1 = userDate1;
       this.userDate2 = userDate2;
       this.userDate3 = userDate3;
       this.userDate4 = userDate4;
       this.userDate5 = userDate5;
       this.userDate6 = userDate6;
       this.userDate7 = userDate7;
       this.userDate8 = userDate8;
       this.userDate9 = userDate9;
       this.userDate10 = userDate10;
       this.userDate11 = userDate11;
       this.userDate12 = userDate12;
       this.userDate13 = userDate13;
       this.userDate14 = userDate14;
       this.userDate15 = userDate15;
       this.userDate16 = userDate16;
       this.userDate17 = userDate17;
       this.userDate18 = userDate18;
       this.userDate19 = userDate19;
       this.userDate20 = userDate20;
       this.userDefined1 = userDefined1;
       this.userDefined2 = userDefined2;
       this.userDefined3 = userDefined3;
       this.userDefined4 = userDefined4;
       this.userDefined5 = userDefined5;
       this.userDefined6 = userDefined6;
       this.userDefined7 = userDefined7;
       this.userDefined8 = userDefined8;
       this.userDefined9 = userDefined9;
       this.userDefined10 = userDefined10;
       this.userDefined11 = userDefined11;
       this.userDefined12 = userDefined12;
       this.userDefined13 = userDefined13;
       this.userDefined14 = userDefined14;
       this.userDefined15 = userDefined15;
       this.userDefined16 = userDefined16;
       this.userDefined17 = userDefined17;
       this.userDefined18 = userDefined18;
       this.userDefined19 = userDefined19;
       this.userDefined20 = userDefined20;
       this.packageType = packageType;
       this.seqAlbenId = seqAlbenId;
       this.patientLiabComparison = patientLiabComparison;
       this.patientLiabType1 = patientLiabType1;
       this.patientLiabType2 = patientLiabType2;
       this.altSchedId = altSchedId;
       this.altRegionId = altRegionId;
       this.modifSearchOrder = modifSearchOrder;
       this.mappingString = mappingString;
       this.cobBankBenefs = cobBankBenefs;
       this.benefitPackageDetails = benefitPackageDetails;
       this.premiumMasters = premiumMasters;
    }
   
     @Id 
    
    @Column(name="BENEFIT_PACKAGE_ID", nullable=false, length=8)
    public String getBenefitPackageId() {
        return this.benefitPackageId;
    }
    
    public void setBenefitPackageId(String benefitPackageId) {
        this.benefitPackageId = benefitPackageId;
    }
    
    @Column(name="SHORT_DESCRIPTION", nullable=false, length=15)
    public String getShortDescription() {
        return this.shortDescription;
    }
    
    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }
    
    @Column(name="NARRATIVE", length=240)
    public String getNarrative() {
        return this.narrative;
    }
    
    public void setNarrative(String narrative) {
        this.narrative = narrative;
    }
    
    @Column(name="SUB_PE_NOT_COV_DAYS", precision=4, scale=0)
    public Short getSubPeNotCovDays() {
        return this.subPeNotCovDays;
    }
    
    public void setSubPeNotCovDays(Short subPeNotCovDays) {
        this.subPeNotCovDays = subPeNotCovDays;
    }
    
    @Column(name="SUB_PE_CONDITN_DAYS", precision=4, scale=0)
    public Short getSubPeConditnDays() {
        return this.subPeConditnDays;
    }
    
    public void setSubPeConditnDays(Short subPeConditnDays) {
        this.subPeConditnDays = subPeConditnDays;
    }
    
    @Column(name="DEP_PE_NOT_COV_DAYS", precision=4, scale=0)
    public Short getDepPeNotCovDays() {
        return this.depPeNotCovDays;
    }
    
    public void setDepPeNotCovDays(Short depPeNotCovDays) {
        this.depPeNotCovDays = depPeNotCovDays;
    }
    
    @Column(name="DEP_PE_CONDITN_DAYS", precision=4, scale=0)
    public Short getDepPeConditnDays() {
        return this.depPeConditnDays;
    }
    
    public void setDepPeConditnDays(Short depPeConditnDays) {
        this.depPeConditnDays = depPeConditnDays;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="SEQ_PROCESSING_ORDER_ID", nullable=false, precision=9, scale=0)
    public int getSeqProcessingOrderId() {
        return this.seqProcessingOrderId;
    }
    
    public void setSeqProcessingOrderId(int seqProcessingOrderId) {
        this.seqProcessingOrderId = seqProcessingOrderId;
    }
    
    @Column(name="APPLY_PATLIB_TO", length=1)
    public Character getApplyPatlibTo() {
        return this.applyPatlibTo;
    }
    
    public void setApplyPatlibTo(Character applyPatlibTo) {
        this.applyPatlibTo = applyPatlibTo;
    }
    
    @Column(name="PATIENT_LIABILITY", length=1)
    public Character getPatientLiability() {
        return this.patientLiability;
    }
    
    public void setPatientLiability(Character patientLiability) {
        this.patientLiability = patientLiability;
    }
    
    @Column(name="PATLIB_PERCENT", precision=5, scale=4)
    public BigDecimal getPatlibPercent() {
        return this.patlibPercent;
    }
    
    public void setPatlibPercent(BigDecimal patlibPercent) {
        this.patlibPercent = patlibPercent;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_1", length=7)
    public Date getUserDate1() {
        return this.userDate1;
    }
    
    public void setUserDate1(Date userDate1) {
        this.userDate1 = userDate1;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_2", length=7)
    public Date getUserDate2() {
        return this.userDate2;
    }
    
    public void setUserDate2(Date userDate2) {
        this.userDate2 = userDate2;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_3", length=7)
    public Date getUserDate3() {
        return this.userDate3;
    }
    
    public void setUserDate3(Date userDate3) {
        this.userDate3 = userDate3;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_4", length=7)
    public Date getUserDate4() {
        return this.userDate4;
    }
    
    public void setUserDate4(Date userDate4) {
        this.userDate4 = userDate4;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_5", length=7)
    public Date getUserDate5() {
        return this.userDate5;
    }
    
    public void setUserDate5(Date userDate5) {
        this.userDate5 = userDate5;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_6", length=7)
    public Date getUserDate6() {
        return this.userDate6;
    }
    
    public void setUserDate6(Date userDate6) {
        this.userDate6 = userDate6;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_7", length=7)
    public Date getUserDate7() {
        return this.userDate7;
    }
    
    public void setUserDate7(Date userDate7) {
        this.userDate7 = userDate7;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_8", length=7)
    public Date getUserDate8() {
        return this.userDate8;
    }
    
    public void setUserDate8(Date userDate8) {
        this.userDate8 = userDate8;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_9", length=7)
    public Date getUserDate9() {
        return this.userDate9;
    }
    
    public void setUserDate9(Date userDate9) {
        this.userDate9 = userDate9;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_10", length=7)
    public Date getUserDate10() {
        return this.userDate10;
    }
    
    public void setUserDate10(Date userDate10) {
        this.userDate10 = userDate10;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_11", length=7)
    public Date getUserDate11() {
        return this.userDate11;
    }
    
    public void setUserDate11(Date userDate11) {
        this.userDate11 = userDate11;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_12", length=7)
    public Date getUserDate12() {
        return this.userDate12;
    }
    
    public void setUserDate12(Date userDate12) {
        this.userDate12 = userDate12;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_13", length=7)
    public Date getUserDate13() {
        return this.userDate13;
    }
    
    public void setUserDate13(Date userDate13) {
        this.userDate13 = userDate13;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_14", length=7)
    public Date getUserDate14() {
        return this.userDate14;
    }
    
    public void setUserDate14(Date userDate14) {
        this.userDate14 = userDate14;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_15", length=7)
    public Date getUserDate15() {
        return this.userDate15;
    }
    
    public void setUserDate15(Date userDate15) {
        this.userDate15 = userDate15;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_16", length=7)
    public Date getUserDate16() {
        return this.userDate16;
    }
    
    public void setUserDate16(Date userDate16) {
        this.userDate16 = userDate16;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_17", length=7)
    public Date getUserDate17() {
        return this.userDate17;
    }
    
    public void setUserDate17(Date userDate17) {
        this.userDate17 = userDate17;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_18", length=7)
    public Date getUserDate18() {
        return this.userDate18;
    }
    
    public void setUserDate18(Date userDate18) {
        this.userDate18 = userDate18;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_19", length=7)
    public Date getUserDate19() {
        return this.userDate19;
    }
    
    public void setUserDate19(Date userDate19) {
        this.userDate19 = userDate19;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_20", length=7)
    public Date getUserDate20() {
        return this.userDate20;
    }
    
    public void setUserDate20(Date userDate20) {
        this.userDate20 = userDate20;
    }
    
    @Column(name="USER_DEFINED_1", length=30)
    public String getUserDefined1() {
        return this.userDefined1;
    }
    
    public void setUserDefined1(String userDefined1) {
        this.userDefined1 = userDefined1;
    }
    
    @Column(name="USER_DEFINED_2", length=30)
    public String getUserDefined2() {
        return this.userDefined2;
    }
    
    public void setUserDefined2(String userDefined2) {
        this.userDefined2 = userDefined2;
    }
    
    @Column(name="USER_DEFINED_3", length=30)
    public String getUserDefined3() {
        return this.userDefined3;
    }
    
    public void setUserDefined3(String userDefined3) {
        this.userDefined3 = userDefined3;
    }
    
    @Column(name="USER_DEFINED_4", length=30)
    public String getUserDefined4() {
        return this.userDefined4;
    }
    
    public void setUserDefined4(String userDefined4) {
        this.userDefined4 = userDefined4;
    }
    
    @Column(name="USER_DEFINED_5", length=30)
    public String getUserDefined5() {
        return this.userDefined5;
    }
    
    public void setUserDefined5(String userDefined5) {
        this.userDefined5 = userDefined5;
    }
    
    @Column(name="USER_DEFINED_6", length=30)
    public String getUserDefined6() {
        return this.userDefined6;
    }
    
    public void setUserDefined6(String userDefined6) {
        this.userDefined6 = userDefined6;
    }
    
    @Column(name="USER_DEFINED_7", length=30)
    public String getUserDefined7() {
        return this.userDefined7;
    }
    
    public void setUserDefined7(String userDefined7) {
        this.userDefined7 = userDefined7;
    }
    
    @Column(name="USER_DEFINED_8", length=30)
    public String getUserDefined8() {
        return this.userDefined8;
    }
    
    public void setUserDefined8(String userDefined8) {
        this.userDefined8 = userDefined8;
    }
    
    @Column(name="USER_DEFINED_9", length=30)
    public String getUserDefined9() {
        return this.userDefined9;
    }
    
    public void setUserDefined9(String userDefined9) {
        this.userDefined9 = userDefined9;
    }
    
    @Column(name="USER_DEFINED_10", length=30)
    public String getUserDefined10() {
        return this.userDefined10;
    }
    
    public void setUserDefined10(String userDefined10) {
        this.userDefined10 = userDefined10;
    }
    
    @Column(name="USER_DEFINED_11", length=30)
    public String getUserDefined11() {
        return this.userDefined11;
    }
    
    public void setUserDefined11(String userDefined11) {
        this.userDefined11 = userDefined11;
    }
    
    @Column(name="USER_DEFINED_12", length=30)
    public String getUserDefined12() {
        return this.userDefined12;
    }
    
    public void setUserDefined12(String userDefined12) {
        this.userDefined12 = userDefined12;
    }
    
    @Column(name="USER_DEFINED_13", length=30)
    public String getUserDefined13() {
        return this.userDefined13;
    }
    
    public void setUserDefined13(String userDefined13) {
        this.userDefined13 = userDefined13;
    }
    
    @Column(name="USER_DEFINED_14", length=30)
    public String getUserDefined14() {
        return this.userDefined14;
    }
    
    public void setUserDefined14(String userDefined14) {
        this.userDefined14 = userDefined14;
    }
    
    @Column(name="USER_DEFINED_15", length=30)
    public String getUserDefined15() {
        return this.userDefined15;
    }
    
    public void setUserDefined15(String userDefined15) {
        this.userDefined15 = userDefined15;
    }
    
    @Column(name="USER_DEFINED_16", length=30)
    public String getUserDefined16() {
        return this.userDefined16;
    }
    
    public void setUserDefined16(String userDefined16) {
        this.userDefined16 = userDefined16;
    }
    
    @Column(name="USER_DEFINED_17", length=30)
    public String getUserDefined17() {
        return this.userDefined17;
    }
    
    public void setUserDefined17(String userDefined17) {
        this.userDefined17 = userDefined17;
    }
    
    @Column(name="USER_DEFINED_18", length=30)
    public String getUserDefined18() {
        return this.userDefined18;
    }
    
    public void setUserDefined18(String userDefined18) {
        this.userDefined18 = userDefined18;
    }
    
    @Column(name="USER_DEFINED_19", length=30)
    public String getUserDefined19() {
        return this.userDefined19;
    }
    
    public void setUserDefined19(String userDefined19) {
        this.userDefined19 = userDefined19;
    }
    
    @Column(name="USER_DEFINED_20", length=30)
    public String getUserDefined20() {
        return this.userDefined20;
    }
    
    public void setUserDefined20(String userDefined20) {
        this.userDefined20 = userDefined20;
    }
    
    @Column(name="PACKAGE_TYPE", length=1)
    public String getPackageType() {
        return this.packageType;
    }
    
    public void setPackageType(String packageType) {
        this.packageType = packageType;
    }
    
    @Column(name="SEQ_ALBEN_ID", precision=9, scale=0)
    public Integer getSeqAlbenId() {
        return this.seqAlbenId;
    }
    
    public void setSeqAlbenId(Integer seqAlbenId) {
        this.seqAlbenId = seqAlbenId;
    }
    
    @Column(name="PATIENT_LIAB_COMPARISON", length=2)
    public String getPatientLiabComparison() {
        return this.patientLiabComparison;
    }
    
    public void setPatientLiabComparison(String patientLiabComparison) {
        this.patientLiabComparison = patientLiabComparison;
    }
    
    @Column(name="PATIENT_LIAB_TYPE_1", length=2)
    public String getPatientLiabType1() {
        return this.patientLiabType1;
    }
    
    public void setPatientLiabType1(String patientLiabType1) {
        this.patientLiabType1 = patientLiabType1;
    }
    
    @Column(name="PATIENT_LIAB_TYPE_2", length=2)
    public String getPatientLiabType2() {
        return this.patientLiabType2;
    }
    
    public void setPatientLiabType2(String patientLiabType2) {
        this.patientLiabType2 = patientLiabType2;
    }
    
    @Column(name="ALT_SCHED_ID", length=3)
    public String getAltSchedId() {
        return this.altSchedId;
    }
    
    public void setAltSchedId(String altSchedId) {
        this.altSchedId = altSchedId;
    }
    
    @Column(name="ALT_REGION_ID", length=3)
    public String getAltRegionId() {
        return this.altRegionId;
    }
    
    public void setAltRegionId(String altRegionId) {
        this.altRegionId = altRegionId;
    }
    
    @Column(name="MODIF_SEARCH_ORDER", length=1)
    public Character getModifSearchOrder() {
        return this.modifSearchOrder;
    }
    
    public void setModifSearchOrder(Character modifSearchOrder) {
        this.modifSearchOrder = modifSearchOrder;
    }
    
    @Column(name="MAPPING_STRING", length=2000)
    public String getMappingString() {
        return this.mappingString;
    }
    
    public void setMappingString(String mappingString) {
        this.mappingString = mappingString;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="benefitPackageMaster")
    public Set<CobBankBenef> getCobBankBenefs() {
        return this.cobBankBenefs;
    }
    
    public void setCobBankBenefs(Set<CobBankBenef> cobBankBenefs) {
        this.cobBankBenefs = cobBankBenefs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="benefitPackageMaster")
    public Set<BenefitPackageDetail> getBenefitPackageDetails() {
        return this.benefitPackageDetails;
    }
    
    public void setBenefitPackageDetails(Set<BenefitPackageDetail> benefitPackageDetails) {
        this.benefitPackageDetails = benefitPackageDetails;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="benefitPackageMaster")
    public Set<PremiumMaster> getPremiumMasters() {
        return this.premiumMasters;
    }
    
    public void setPremiumMasters(Set<PremiumMaster> premiumMasters) {
        this.premiumMasters = premiumMasters;
    }




}


