package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BenefitRuleUserDefId generated by hbm2java
 */
@Embeddable
public class BenefitRuleUserDefId  implements java.io.Serializable {


     private String ruleId;
     private BigDecimal seqBruleUserDef;

    public BenefitRuleUserDefId() {
    }

    public BenefitRuleUserDefId(String ruleId, BigDecimal seqBruleUserDef) {
       this.ruleId = ruleId;
       this.seqBruleUserDef = seqBruleUserDef;
    }
   

    @Column(name="RULE_ID", nullable=false, length=10)
    public String getRuleId() {
        return this.ruleId;
    }
    
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId;
    }

    @Column(name="SEQ_BRULE_USER_DEF", nullable=false, precision=22, scale=0)
    public BigDecimal getSeqBruleUserDef() {
        return this.seqBruleUserDef;
    }
    
    public void setSeqBruleUserDef(BigDecimal seqBruleUserDef) {
        this.seqBruleUserDef = seqBruleUserDef;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BenefitRuleUserDefId) ) return false;
		 BenefitRuleUserDefId castOther = ( BenefitRuleUserDefId ) other; 
         
		 return ( (this.getRuleId()==castOther.getRuleId()) || ( this.getRuleId()!=null && castOther.getRuleId()!=null && this.getRuleId().equals(castOther.getRuleId()) ) )
 && ( (this.getSeqBruleUserDef()==castOther.getSeqBruleUserDef()) || ( this.getSeqBruleUserDef()!=null && castOther.getSeqBruleUserDef()!=null && this.getSeqBruleUserDef().equals(castOther.getSeqBruleUserDef()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRuleId() == null ? 0 : this.getRuleId().hashCode() );
         result = 37 * result + ( getSeqBruleUserDef() == null ? 0 : this.getSeqBruleUserDef().hashCode() );
         return result;
   }   


}


