package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BenefitPackageDetailId generated by hbm2java
 */
@Embeddable
public class BenefitPackageDetailId  implements java.io.Serializable {


     private String benefitPackageId;
     private int seqBenPackage;

    public BenefitPackageDetailId() {
    }

    public BenefitPackageDetailId(String benefitPackageId, int seqBenPackage) {
       this.benefitPackageId = benefitPackageId;
       this.seqBenPackage = seqBenPackage;
    }
   

    @Column(name="BENEFIT_PACKAGE_ID", nullable=false, length=8)
    public String getBenefitPackageId() {
        return this.benefitPackageId;
    }
    
    public void setBenefitPackageId(String benefitPackageId) {
        this.benefitPackageId = benefitPackageId;
    }

    @Column(name="SEQ_BEN_PACKAGE", nullable=false, precision=9, scale=0)
    public int getSeqBenPackage() {
        return this.seqBenPackage;
    }
    
    public void setSeqBenPackage(int seqBenPackage) {
        this.seqBenPackage = seqBenPackage;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BenefitPackageDetailId) ) return false;
		 BenefitPackageDetailId castOther = ( BenefitPackageDetailId ) other; 
         
		 return ( (this.getBenefitPackageId()==castOther.getBenefitPackageId()) || ( this.getBenefitPackageId()!=null && castOther.getBenefitPackageId()!=null && this.getBenefitPackageId().equals(castOther.getBenefitPackageId()) ) )
 && (this.getSeqBenPackage()==castOther.getSeqBenPackage());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBenefitPackageId() == null ? 0 : this.getBenefitPackageId().hashCode() );
         result = 37 * result + this.getSeqBenPackage();
         return result;
   }   


}


