package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BenefitRule generated by hbm2java
 */
@Entity
@Table(name="BENEFIT_RULE"
    ,schema="DORIS"
)
public class BenefitRule extends Base.BaseEntity implements java.io.Serializable {


     private String ruleId;
     private String ruleType;
     private String shortDescription;
     private String medDefFilter;
     private String narrative;
     private String attributeChar1;
     private String attributeChar2;
     private String attributeChar3;
     private String attributeChar4;
     private String attributeChar5;
     private String attributeChar6;
     private String attributeChar7;
     private String attributeChar8;
     private String attributeChar9;
     private String attributeChar10;
     private String attributeChar11;
     private String attributeChar12;
     private String attributeChar13;
     private String attributeChar14;
     private String attributeChar15;
     private BigDecimal attributeNum1;
     private BigDecimal attributeNum2;
     private BigDecimal attributeNum3;
     private BigDecimal attributeNum4;
     private BigDecimal attributeNum5;
     private Integer attributeNum6;
     private Integer attributeNum7;
     private Integer attributeNum8;
     private Integer attributeNum9;
     private Integer attributeNum10;
     private Date attributeDate1;
     private Date attributeDate2;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private Character multiplyByQty;
     private String attributeChar16;
     private BigDecimal attributeNum11;
     private BigDecimal attributeNum12;
     private String applyToInterimBill;
     private String attributeChar17;
     private String attributeChar18;
     private BigDecimal attributeNum13;
     private BigDecimal attributeNum14;
     private Integer attributeNum15;
     private String attributeChar19;
     private String oneCopayPerDay;
     private String oneCopayMethod;
     private String attributeChar20;
     private String prevTierRuleId;
     private String userDefined1;
     private String altCoins;
     private String eobIndicator;
     private Set<BenefitRuleUserDef> benefitRuleUserDefs = new HashSet<BenefitRuleUserDef>(0);
     private Set<BenefitRuleMaint> benefitRuleMaints = new HashSet<BenefitRuleMaint>(0);

    public BenefitRule() {
    }

	
    public BenefitRule(String ruleId, String ruleType, String shortDescription, String medDefFilter) {
        this.ruleId = ruleId;
        this.ruleType = ruleType;
        this.shortDescription = shortDescription;
        this.medDefFilter = medDefFilter;
    }
    public BenefitRule(String ruleId, String ruleType, String shortDescription, String medDefFilter, String narrative, String attributeChar1, String attributeChar2, String attributeChar3, String attributeChar4, String attributeChar5, String attributeChar6, String attributeChar7, String attributeChar8, String attributeChar9, String attributeChar10, String attributeChar11, String attributeChar12, String attributeChar13, String attributeChar14, String attributeChar15, BigDecimal attributeNum1, BigDecimal attributeNum2, BigDecimal attributeNum3, BigDecimal attributeNum4, BigDecimal attributeNum5, Integer attributeNum6, Integer attributeNum7, Integer attributeNum8, Integer attributeNum9, Integer attributeNum10, Date attributeDate1, Date attributeDate2, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, Character multiplyByQty, String attributeChar16, BigDecimal attributeNum11, BigDecimal attributeNum12, String applyToInterimBill, String attributeChar17, String attributeChar18, BigDecimal attributeNum13, BigDecimal attributeNum14, Integer attributeNum15, String attributeChar19, String oneCopayPerDay, String oneCopayMethod, String attributeChar20, String prevTierRuleId, String userDefined1, String altCoins, String eobIndicator, Set<BenefitRuleUserDef> benefitRuleUserDefs, Set<BenefitRuleMaint> benefitRuleMaints) {
       this.ruleId = ruleId;
       this.ruleType = ruleType;
       this.shortDescription = shortDescription;
       this.medDefFilter = medDefFilter;
       this.narrative = narrative;
       this.attributeChar1 = attributeChar1;
       this.attributeChar2 = attributeChar2;
       this.attributeChar3 = attributeChar3;
       this.attributeChar4 = attributeChar4;
       this.attributeChar5 = attributeChar5;
       this.attributeChar6 = attributeChar6;
       this.attributeChar7 = attributeChar7;
       this.attributeChar8 = attributeChar8;
       this.attributeChar9 = attributeChar9;
       this.attributeChar10 = attributeChar10;
       this.attributeChar11 = attributeChar11;
       this.attributeChar12 = attributeChar12;
       this.attributeChar13 = attributeChar13;
       this.attributeChar14 = attributeChar14;
       this.attributeChar15 = attributeChar15;
       this.attributeNum1 = attributeNum1;
       this.attributeNum2 = attributeNum2;
       this.attributeNum3 = attributeNum3;
       this.attributeNum4 = attributeNum4;
       this.attributeNum5 = attributeNum5;
       this.attributeNum6 = attributeNum6;
       this.attributeNum7 = attributeNum7;
       this.attributeNum8 = attributeNum8;
       this.attributeNum9 = attributeNum9;
       this.attributeNum10 = attributeNum10;
       this.attributeDate1 = attributeDate1;
       this.attributeDate2 = attributeDate2;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.multiplyByQty = multiplyByQty;
       this.attributeChar16 = attributeChar16;
       this.attributeNum11 = attributeNum11;
       this.attributeNum12 = attributeNum12;
       this.applyToInterimBill = applyToInterimBill;
       this.attributeChar17 = attributeChar17;
       this.attributeChar18 = attributeChar18;
       this.attributeNum13 = attributeNum13;
       this.attributeNum14 = attributeNum14;
       this.attributeNum15 = attributeNum15;
       this.attributeChar19 = attributeChar19;
       this.oneCopayPerDay = oneCopayPerDay;
       this.oneCopayMethod = oneCopayMethod;
       this.attributeChar20 = attributeChar20;
       this.prevTierRuleId = prevTierRuleId;
       this.userDefined1 = userDefined1;
       this.altCoins = altCoins;
       this.eobIndicator = eobIndicator;
       this.benefitRuleUserDefs = benefitRuleUserDefs;
       this.benefitRuleMaints = benefitRuleMaints;
    }
   
     @Id 
    
    @Column(name="RULE_ID", nullable=false, length=10)
    public String getRuleId() {
        return this.ruleId;
    }
    
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId;
    }
    
    @Column(name="RULE_TYPE", nullable=false, length=2)
    public String getRuleType() {
        return this.ruleType;
    }
    
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType;
    }
    
    @Column(name="SHORT_DESCRIPTION", nullable=false, length=20)
    public String getShortDescription() {
        return this.shortDescription;
    }
    
    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }
    
    @Column(name="MED_DEF_FILTER", nullable=false, length=60)
    public String getMedDefFilter() {
        return this.medDefFilter;
    }
    
    public void setMedDefFilter(String medDefFilter) {
        this.medDefFilter = medDefFilter;
    }
    
    @Column(name="NARRATIVE", length=240)
    public String getNarrative() {
        return this.narrative;
    }
    
    public void setNarrative(String narrative) {
        this.narrative = narrative;
    }
    
    @Column(name="ATTRIBUTE_CHAR_1", length=10)
    public String getAttributeChar1() {
        return this.attributeChar1;
    }
    
    public void setAttributeChar1(String attributeChar1) {
        this.attributeChar1 = attributeChar1;
    }
    
    @Column(name="ATTRIBUTE_CHAR_2", length=10)
    public String getAttributeChar2() {
        return this.attributeChar2;
    }
    
    public void setAttributeChar2(String attributeChar2) {
        this.attributeChar2 = attributeChar2;
    }
    
    @Column(name="ATTRIBUTE_CHAR_3", length=10)
    public String getAttributeChar3() {
        return this.attributeChar3;
    }
    
    public void setAttributeChar3(String attributeChar3) {
        this.attributeChar3 = attributeChar3;
    }
    
    @Column(name="ATTRIBUTE_CHAR_4", length=25)
    public String getAttributeChar4() {
        return this.attributeChar4;
    }
    
    public void setAttributeChar4(String attributeChar4) {
        this.attributeChar4 = attributeChar4;
    }
    
    @Column(name="ATTRIBUTE_CHAR_5", length=50)
    public String getAttributeChar5() {
        return this.attributeChar5;
    }
    
    public void setAttributeChar5(String attributeChar5) {
        this.attributeChar5 = attributeChar5;
    }
    
    @Column(name="ATTRIBUTE_CHAR_6", length=10)
    public String getAttributeChar6() {
        return this.attributeChar6;
    }
    
    public void setAttributeChar6(String attributeChar6) {
        this.attributeChar6 = attributeChar6;
    }
    
    @Column(name="ATTRIBUTE_CHAR_7", length=10)
    public String getAttributeChar7() {
        return this.attributeChar7;
    }
    
    public void setAttributeChar7(String attributeChar7) {
        this.attributeChar7 = attributeChar7;
    }
    
    @Column(name="ATTRIBUTE_CHAR_8", length=10)
    public String getAttributeChar8() {
        return this.attributeChar8;
    }
    
    public void setAttributeChar8(String attributeChar8) {
        this.attributeChar8 = attributeChar8;
    }
    
    @Column(name="ATTRIBUTE_CHAR_9", length=25)
    public String getAttributeChar9() {
        return this.attributeChar9;
    }
    
    public void setAttributeChar9(String attributeChar9) {
        this.attributeChar9 = attributeChar9;
    }
    
    @Column(name="ATTRIBUTE_CHAR_10", length=50)
    public String getAttributeChar10() {
        return this.attributeChar10;
    }
    
    public void setAttributeChar10(String attributeChar10) {
        this.attributeChar10 = attributeChar10;
    }
    
    @Column(name="ATTRIBUTE_CHAR_11", length=10)
    public String getAttributeChar11() {
        return this.attributeChar11;
    }
    
    public void setAttributeChar11(String attributeChar11) {
        this.attributeChar11 = attributeChar11;
    }
    
    @Column(name="ATTRIBUTE_CHAR_12", length=10)
    public String getAttributeChar12() {
        return this.attributeChar12;
    }
    
    public void setAttributeChar12(String attributeChar12) {
        this.attributeChar12 = attributeChar12;
    }
    
    @Column(name="ATTRIBUTE_CHAR_13", length=10)
    public String getAttributeChar13() {
        return this.attributeChar13;
    }
    
    public void setAttributeChar13(String attributeChar13) {
        this.attributeChar13 = attributeChar13;
    }
    
    @Column(name="ATTRIBUTE_CHAR_14", length=25)
    public String getAttributeChar14() {
        return this.attributeChar14;
    }
    
    public void setAttributeChar14(String attributeChar14) {
        this.attributeChar14 = attributeChar14;
    }
    
    @Column(name="ATTRIBUTE_CHAR_15", length=50)
    public String getAttributeChar15() {
        return this.attributeChar15;
    }
    
    public void setAttributeChar15(String attributeChar15) {
        this.attributeChar15 = attributeChar15;
    }
    
    @Column(name="ATTRIBUTE_NUM_1", precision=18)
    public BigDecimal getAttributeNum1() {
        return this.attributeNum1;
    }
    
    public void setAttributeNum1(BigDecimal attributeNum1) {
        this.attributeNum1 = attributeNum1;
    }
    
    @Column(name="ATTRIBUTE_NUM_2", precision=18)
    public BigDecimal getAttributeNum2() {
        return this.attributeNum2;
    }
    
    public void setAttributeNum2(BigDecimal attributeNum2) {
        this.attributeNum2 = attributeNum2;
    }
    
    @Column(name="ATTRIBUTE_NUM_3", precision=18)
    public BigDecimal getAttributeNum3() {
        return this.attributeNum3;
    }
    
    public void setAttributeNum3(BigDecimal attributeNum3) {
        this.attributeNum3 = attributeNum3;
    }
    
    @Column(name="ATTRIBUTE_NUM_4", precision=18)
    public BigDecimal getAttributeNum4() {
        return this.attributeNum4;
    }
    
    public void setAttributeNum4(BigDecimal attributeNum4) {
        this.attributeNum4 = attributeNum4;
    }
    
    @Column(name="ATTRIBUTE_NUM_5", precision=18)
    public BigDecimal getAttributeNum5() {
        return this.attributeNum5;
    }
    
    public void setAttributeNum5(BigDecimal attributeNum5) {
        this.attributeNum5 = attributeNum5;
    }
    
    @Column(name="ATTRIBUTE_NUM_6", precision=5, scale=0)
    public Integer getAttributeNum6() {
        return this.attributeNum6;
    }
    
    public void setAttributeNum6(Integer attributeNum6) {
        this.attributeNum6 = attributeNum6;
    }
    
    @Column(name="ATTRIBUTE_NUM_7", precision=5, scale=0)
    public Integer getAttributeNum7() {
        return this.attributeNum7;
    }
    
    public void setAttributeNum7(Integer attributeNum7) {
        this.attributeNum7 = attributeNum7;
    }
    
    @Column(name="ATTRIBUTE_NUM_8", precision=5, scale=0)
    public Integer getAttributeNum8() {
        return this.attributeNum8;
    }
    
    public void setAttributeNum8(Integer attributeNum8) {
        this.attributeNum8 = attributeNum8;
    }
    
    @Column(name="ATTRIBUTE_NUM_9", precision=5, scale=0)
    public Integer getAttributeNum9() {
        return this.attributeNum9;
    }
    
    public void setAttributeNum9(Integer attributeNum9) {
        this.attributeNum9 = attributeNum9;
    }
    
    @Column(name="ATTRIBUTE_NUM_10", precision=5, scale=0)
    public Integer getAttributeNum10() {
        return this.attributeNum10;
    }
    
    public void setAttributeNum10(Integer attributeNum10) {
        this.attributeNum10 = attributeNum10;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="ATTRIBUTE_DATE_1", length=7)
    public Date getAttributeDate1() {
        return this.attributeDate1;
    }
    
    public void setAttributeDate1(Date attributeDate1) {
        this.attributeDate1 = attributeDate1;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="ATTRIBUTE_DATE_2", length=7)
    public Date getAttributeDate2() {
        return this.attributeDate2;
    }
    
    public void setAttributeDate2(Date attributeDate2) {
        this.attributeDate2 = attributeDate2;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="MULTIPLY_BY_QTY", length=1)
    public Character getMultiplyByQty() {
        return this.multiplyByQty;
    }
    
    public void setMultiplyByQty(Character multiplyByQty) {
        this.multiplyByQty = multiplyByQty;
    }
    
    @Column(name="ATTRIBUTE_CHAR_16", length=15)
    public String getAttributeChar16() {
        return this.attributeChar16;
    }
    
    public void setAttributeChar16(String attributeChar16) {
        this.attributeChar16 = attributeChar16;
    }
    
    @Column(name="ATTRIBUTE_NUM_11", precision=18)
    public BigDecimal getAttributeNum11() {
        return this.attributeNum11;
    }
    
    public void setAttributeNum11(BigDecimal attributeNum11) {
        this.attributeNum11 = attributeNum11;
    }
    
    @Column(name="ATTRIBUTE_NUM_12", precision=18)
    public BigDecimal getAttributeNum12() {
        return this.attributeNum12;
    }
    
    public void setAttributeNum12(BigDecimal attributeNum12) {
        this.attributeNum12 = attributeNum12;
    }
    
    @Column(name="APPLY_TO_INTERIM_BILL", length=1)
    public String getApplyToInterimBill() {
        return this.applyToInterimBill;
    }
    
    public void setApplyToInterimBill(String applyToInterimBill) {
        this.applyToInterimBill = applyToInterimBill;
    }
    
    @Column(name="ATTRIBUTE_CHAR_17", length=1)
    public String getAttributeChar17() {
        return this.attributeChar17;
    }
    
    public void setAttributeChar17(String attributeChar17) {
        this.attributeChar17 = attributeChar17;
    }
    
    @Column(name="ATTRIBUTE_CHAR_18", length=1)
    public String getAttributeChar18() {
        return this.attributeChar18;
    }
    
    public void setAttributeChar18(String attributeChar18) {
        this.attributeChar18 = attributeChar18;
    }
    
    @Column(name="ATTRIBUTE_NUM_13", precision=18)
    public BigDecimal getAttributeNum13() {
        return this.attributeNum13;
    }
    
    public void setAttributeNum13(BigDecimal attributeNum13) {
        this.attributeNum13 = attributeNum13;
    }
    
    @Column(name="ATTRIBUTE_NUM_14", precision=18)
    public BigDecimal getAttributeNum14() {
        return this.attributeNum14;
    }
    
    public void setAttributeNum14(BigDecimal attributeNum14) {
        this.attributeNum14 = attributeNum14;
    }
    
    @Column(name="ATTRIBUTE_NUM_15", precision=5, scale=0)
    public Integer getAttributeNum15() {
        return this.attributeNum15;
    }
    
    public void setAttributeNum15(Integer attributeNum15) {
        this.attributeNum15 = attributeNum15;
    }
    
    @Column(name="ATTRIBUTE_CHAR_19", length=1)
    public String getAttributeChar19() {
        return this.attributeChar19;
    }
    
    public void setAttributeChar19(String attributeChar19) {
        this.attributeChar19 = attributeChar19;
    }
    
    @Column(name="ONE_COPAY_PER_DAY", length=1)
    public String getOneCopayPerDay() {
        return this.oneCopayPerDay;
    }
    
    public void setOneCopayPerDay(String oneCopayPerDay) {
        this.oneCopayPerDay = oneCopayPerDay;
    }
    
    @Column(name="ONE_COPAY_METHOD", length=1)
    public String getOneCopayMethod() {
        return this.oneCopayMethod;
    }
    
    public void setOneCopayMethod(String oneCopayMethod) {
        this.oneCopayMethod = oneCopayMethod;
    }
    
    @Column(name="ATTRIBUTE_CHAR_20", length=1)
    public String getAttributeChar20() {
        return this.attributeChar20;
    }
    
    public void setAttributeChar20(String attributeChar20) {
        this.attributeChar20 = attributeChar20;
    }
    
    @Column(name="PREV_TIER_RULE_ID", length=10)
    public String getPrevTierRuleId() {
        return this.prevTierRuleId;
    }
    
    public void setPrevTierRuleId(String prevTierRuleId) {
        this.prevTierRuleId = prevTierRuleId;
    }
    
    @Column(name="USER_DEFINED_1", length=30)
    public String getUserDefined1() {
        return this.userDefined1;
    }
    
    public void setUserDefined1(String userDefined1) {
        this.userDefined1 = userDefined1;
    }
    
    @Column(name="ALT_COINS", length=1)
    public String getAltCoins() {
        return this.altCoins;
    }
    
    public void setAltCoins(String altCoins) {
        this.altCoins = altCoins;
    }
    
    @Column(name="EOB_INDICATOR", length=5)
    public String getEobIndicator() {
        return this.eobIndicator;
    }
    
    public void setEobIndicator(String eobIndicator) {
        this.eobIndicator = eobIndicator;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="benefitRule")
    public Set<BenefitRuleUserDef> getBenefitRuleUserDefs() {
        return this.benefitRuleUserDefs;
    }
    
    public void setBenefitRuleUserDefs(Set<BenefitRuleUserDef> benefitRuleUserDefs) {
        this.benefitRuleUserDefs = benefitRuleUserDefs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="brule")
    public Set<BenefitRuleMaint> getBenefitRuleMaints() {
        return this.benefitRuleMaints;
    }
    
    public void setBenefitRuleMaints(Set<BenefitRuleMaint> benefitRuleMaints) {
        this.benefitRuleMaints = benefitRuleMaints;
    }




}


