package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.util.*;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BenefitRuleUserDef generated by hbm2java
 */
@Entity
@Table(name="BENEFIT_RULE_USER_DEF"
    ,schema="DORIS"
)
public class BenefitRuleUserDef extends Base.BaseEntity implements java.io.Serializable {


     private BenefitRuleUserDefId id;
     private BenefitRule benefitRule;
     private Date effectiveDate;
     private Date termDate;
     private String termReason;
     private String userDefined1;
     private String userDefined2;
     private String userDefined3;
     private String userDefined4;
     private String userDefined5;
     private String userDefined6;
     private String userDefined7;
     private String userDefined8;
     private String userDefined9;
     private String userDefined10;
     private String userDefined11;
     private String userDefined12;
     private String userDefined13;
     private String userDefined14;
     private String userDefined15;
     private String userDefined16;
     private String userDefined17;
     private String userDefined18;
     private String userDefined19;
     private String userDefined20;
     private String userDefined21;
     private String userDefined22;
     private String userDefined23;
     private String userDefined24;
     private String userDefined25;
     private String userDefined26;
     private String userDefined27;
     private String userDefined28;
     private String userDefined29;
     private String userDefined30;
     private String userDefined31;
     private String userDefined32;
     private String userDefined33;
     private String userDefined34;
     private String userDefined35;
     private String userDefined36;
     private String userDefined37;
     private String userDefined38;
     private String userDefined39;
     private String userDefined40;
     private Date userDate1;
     private Date userDate2;
     private Date userDate3;
     private Date userDate4;
     private Date userDate5;
     private Date userDate6;
     private Date userDate7;
     private Date userDate8;
     private Date userDate9;
     private Date userDate10;
     private Date userDate11;
     private Date userDate12;
     private Date userDate13;
     private Date userDate14;
     private Date userDate15;
     private Date userDate16;
     private Date userDate17;
     private Date userDate18;
     private Date userDate19;
     private Date userDate20;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;

    public BenefitRuleUserDef() {
    }

	
    public BenefitRuleUserDef(BenefitRuleUserDefId id, BenefitRule benefitRule) {
        this.id = id;
        this.benefitRule = benefitRule;
    }
    public BenefitRuleUserDef(BenefitRuleUserDefId id, BenefitRule benefitRule, Date effectiveDate, Date termDate, String termReason, String userDefined1, String userDefined2, String userDefined3, String userDefined4, String userDefined5, String userDefined6, String userDefined7, String userDefined8, String userDefined9, String userDefined10, String userDefined11, String userDefined12, String userDefined13, String userDefined14, String userDefined15, String userDefined16, String userDefined17, String userDefined18, String userDefined19, String userDefined20, String userDefined21, String userDefined22, String userDefined23, String userDefined24, String userDefined25, String userDefined26, String userDefined27, String userDefined28, String userDefined29, String userDefined30, String userDefined31, String userDefined32, String userDefined33, String userDefined34, String userDefined35, String userDefined36, String userDefined37, String userDefined38, String userDefined39, String userDefined40, Date userDate1, Date userDate2, Date userDate3, Date userDate4, Date userDate5, Date userDate6, Date userDate7, Date userDate8, Date userDate9, Date userDate10, Date userDate11, Date userDate12, Date userDate13, Date userDate14, Date userDate15, Date userDate16, Date userDate17, Date userDate18, Date userDate19, Date userDate20, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess) {
       this.id = id;
       this.benefitRule = benefitRule;
       this.effectiveDate = effectiveDate;
       this.termDate = termDate;
       this.termReason = termReason;
       this.userDefined1 = userDefined1;
       this.userDefined2 = userDefined2;
       this.userDefined3 = userDefined3;
       this.userDefined4 = userDefined4;
       this.userDefined5 = userDefined5;
       this.userDefined6 = userDefined6;
       this.userDefined7 = userDefined7;
       this.userDefined8 = userDefined8;
       this.userDefined9 = userDefined9;
       this.userDefined10 = userDefined10;
       this.userDefined11 = userDefined11;
       this.userDefined12 = userDefined12;
       this.userDefined13 = userDefined13;
       this.userDefined14 = userDefined14;
       this.userDefined15 = userDefined15;
       this.userDefined16 = userDefined16;
       this.userDefined17 = userDefined17;
       this.userDefined18 = userDefined18;
       this.userDefined19 = userDefined19;
       this.userDefined20 = userDefined20;
       this.userDefined21 = userDefined21;
       this.userDefined22 = userDefined22;
       this.userDefined23 = userDefined23;
       this.userDefined24 = userDefined24;
       this.userDefined25 = userDefined25;
       this.userDefined26 = userDefined26;
       this.userDefined27 = userDefined27;
       this.userDefined28 = userDefined28;
       this.userDefined29 = userDefined29;
       this.userDefined30 = userDefined30;
       this.userDefined31 = userDefined31;
       this.userDefined32 = userDefined32;
       this.userDefined33 = userDefined33;
       this.userDefined34 = userDefined34;
       this.userDefined35 = userDefined35;
       this.userDefined36 = userDefined36;
       this.userDefined37 = userDefined37;
       this.userDefined38 = userDefined38;
       this.userDefined39 = userDefined39;
       this.userDefined40 = userDefined40;
       this.userDate1 = userDate1;
       this.userDate2 = userDate2;
       this.userDate3 = userDate3;
       this.userDate4 = userDate4;
       this.userDate5 = userDate5;
       this.userDate6 = userDate6;
       this.userDate7 = userDate7;
       this.userDate8 = userDate8;
       this.userDate9 = userDate9;
       this.userDate10 = userDate10;
       this.userDate11 = userDate11;
       this.userDate12 = userDate12;
       this.userDate13 = userDate13;
       this.userDate14 = userDate14;
       this.userDate15 = userDate15;
       this.userDate16 = userDate16;
       this.userDate17 = userDate17;
       this.userDate18 = userDate18;
       this.userDate19 = userDate19;
       this.userDate20 = userDate20;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="ruleId", column=@Column(name="RULE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="seqBruleUserDef", column=@Column(name="SEQ_BRULE_USER_DEF", nullable=false, precision=22, scale=0) ) } )
    public BenefitRuleUserDefId getId() {
        return this.id;
    }
    
    public void setId(BenefitRuleUserDefId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RULE_ID", nullable=false, insertable=false, updatable=false)
    public BenefitRule getBenefitRule() {
        return this.benefitRule;
    }
    
    public void setBenefitRule(BenefitRule benefitRule) {
        this.benefitRule = benefitRule;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", length=7)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="TERM_DATE", length=7)
    public Date getTermDate() {
        return this.termDate;
    }
    
    public void setTermDate(Date termDate) {
        this.termDate = termDate;
    }
    
    @Column(name="TERM_REASON", length=5)
    public String getTermReason() {
        return this.termReason;
    }
    
    public void setTermReason(String termReason) {
        this.termReason = termReason;
    }
    
    @Column(name="USER_DEFINED_1", length=30)
    public String getUserDefined1() {
        return this.userDefined1;
    }
    
    public void setUserDefined1(String userDefined1) {
        this.userDefined1 = userDefined1;
    }
    
    @Column(name="USER_DEFINED_2", length=30)
    public String getUserDefined2() {
        return this.userDefined2;
    }
    
    public void setUserDefined2(String userDefined2) {
        this.userDefined2 = userDefined2;
    }
    
    @Column(name="USER_DEFINED_3", length=30)
    public String getUserDefined3() {
        return this.userDefined3;
    }
    
    public void setUserDefined3(String userDefined3) {
        this.userDefined3 = userDefined3;
    }
    
    @Column(name="USER_DEFINED_4", length=30)
    public String getUserDefined4() {
        return this.userDefined4;
    }
    
    public void setUserDefined4(String userDefined4) {
        this.userDefined4 = userDefined4;
    }
    
    @Column(name="USER_DEFINED_5", length=30)
    public String getUserDefined5() {
        return this.userDefined5;
    }
    
    public void setUserDefined5(String userDefined5) {
        this.userDefined5 = userDefined5;
    }
    
    @Column(name="USER_DEFINED_6", length=30)
    public String getUserDefined6() {
        return this.userDefined6;
    }
    
    public void setUserDefined6(String userDefined6) {
        this.userDefined6 = userDefined6;
    }
    
    @Column(name="USER_DEFINED_7", length=30)
    public String getUserDefined7() {
        return this.userDefined7;
    }
    
    public void setUserDefined7(String userDefined7) {
        this.userDefined7 = userDefined7;
    }
    
    @Column(name="USER_DEFINED_8", length=30)
    public String getUserDefined8() {
        return this.userDefined8;
    }
    
    public void setUserDefined8(String userDefined8) {
        this.userDefined8 = userDefined8;
    }
    
    @Column(name="USER_DEFINED_9", length=30)
    public String getUserDefined9() {
        return this.userDefined9;
    }
    
    public void setUserDefined9(String userDefined9) {
        this.userDefined9 = userDefined9;
    }
    
    @Column(name="USER_DEFINED_10", length=30)
    public String getUserDefined10() {
        return this.userDefined10;
    }
    
    public void setUserDefined10(String userDefined10) {
        this.userDefined10 = userDefined10;
    }
    
    @Column(name="USER_DEFINED_11", length=30)
    public String getUserDefined11() {
        return this.userDefined11;
    }
    
    public void setUserDefined11(String userDefined11) {
        this.userDefined11 = userDefined11;
    }
    
    @Column(name="USER_DEFINED_12", length=30)
    public String getUserDefined12() {
        return this.userDefined12;
    }
    
    public void setUserDefined12(String userDefined12) {
        this.userDefined12 = userDefined12;
    }
    
    @Column(name="USER_DEFINED_13", length=30)
    public String getUserDefined13() {
        return this.userDefined13;
    }
    
    public void setUserDefined13(String userDefined13) {
        this.userDefined13 = userDefined13;
    }
    
    @Column(name="USER_DEFINED_14", length=30)
    public String getUserDefined14() {
        return this.userDefined14;
    }
    
    public void setUserDefined14(String userDefined14) {
        this.userDefined14 = userDefined14;
    }
    
    @Column(name="USER_DEFINED_15", length=30)
    public String getUserDefined15() {
        return this.userDefined15;
    }
    
    public void setUserDefined15(String userDefined15) {
        this.userDefined15 = userDefined15;
    }
    
    @Column(name="USER_DEFINED_16", length=30)
    public String getUserDefined16() {
        return this.userDefined16;
    }
    
    public void setUserDefined16(String userDefined16) {
        this.userDefined16 = userDefined16;
    }
    
    @Column(name="USER_DEFINED_17", length=30)
    public String getUserDefined17() {
        return this.userDefined17;
    }
    
    public void setUserDefined17(String userDefined17) {
        this.userDefined17 = userDefined17;
    }
    
    @Column(name="USER_DEFINED_18", length=30)
    public String getUserDefined18() {
        return this.userDefined18;
    }
    
    public void setUserDefined18(String userDefined18) {
        this.userDefined18 = userDefined18;
    }
    
    @Column(name="USER_DEFINED_19", length=30)
    public String getUserDefined19() {
        return this.userDefined19;
    }
    
    public void setUserDefined19(String userDefined19) {
        this.userDefined19 = userDefined19;
    }
    
    @Column(name="USER_DEFINED_20", length=30)
    public String getUserDefined20() {
        return this.userDefined20;
    }
    
    public void setUserDefined20(String userDefined20) {
        this.userDefined20 = userDefined20;
    }
    
    @Column(name="USER_DEFINED_21", length=30)
    public String getUserDefined21() {
        return this.userDefined21;
    }
    
    public void setUserDefined21(String userDefined21) {
        this.userDefined21 = userDefined21;
    }
    
    @Column(name="USER_DEFINED_22", length=30)
    public String getUserDefined22() {
        return this.userDefined22;
    }
    
    public void setUserDefined22(String userDefined22) {
        this.userDefined22 = userDefined22;
    }
    
    @Column(name="USER_DEFINED_23", length=30)
    public String getUserDefined23() {
        return this.userDefined23;
    }
    
    public void setUserDefined23(String userDefined23) {
        this.userDefined23 = userDefined23;
    }
    
    @Column(name="USER_DEFINED_24", length=30)
    public String getUserDefined24() {
        return this.userDefined24;
    }
    
    public void setUserDefined24(String userDefined24) {
        this.userDefined24 = userDefined24;
    }
    
    @Column(name="USER_DEFINED_25", length=30)
    public String getUserDefined25() {
        return this.userDefined25;
    }
    
    public void setUserDefined25(String userDefined25) {
        this.userDefined25 = userDefined25;
    }
    
    @Column(name="USER_DEFINED_26", length=30)
    public String getUserDefined26() {
        return this.userDefined26;
    }
    
    public void setUserDefined26(String userDefined26) {
        this.userDefined26 = userDefined26;
    }
    
    @Column(name="USER_DEFINED_27", length=30)
    public String getUserDefined27() {
        return this.userDefined27;
    }
    
    public void setUserDefined27(String userDefined27) {
        this.userDefined27 = userDefined27;
    }
    
    @Column(name="USER_DEFINED_28", length=30)
    public String getUserDefined28() {
        return this.userDefined28;
    }
    
    public void setUserDefined28(String userDefined28) {
        this.userDefined28 = userDefined28;
    }
    
    @Column(name="USER_DEFINED_29", length=30)
    public String getUserDefined29() {
        return this.userDefined29;
    }
    
    public void setUserDefined29(String userDefined29) {
        this.userDefined29 = userDefined29;
    }
    
    @Column(name="USER_DEFINED_30", length=30)
    public String getUserDefined30() {
        return this.userDefined30;
    }
    
    public void setUserDefined30(String userDefined30) {
        this.userDefined30 = userDefined30;
    }
    
    @Column(name="USER_DEFINED_31", length=30)
    public String getUserDefined31() {
        return this.userDefined31;
    }
    
    public void setUserDefined31(String userDefined31) {
        this.userDefined31 = userDefined31;
    }
    
    @Column(name="USER_DEFINED_32", length=30)
    public String getUserDefined32() {
        return this.userDefined32;
    }
    
    public void setUserDefined32(String userDefined32) {
        this.userDefined32 = userDefined32;
    }
    
    @Column(name="USER_DEFINED_33", length=30)
    public String getUserDefined33() {
        return this.userDefined33;
    }
    
    public void setUserDefined33(String userDefined33) {
        this.userDefined33 = userDefined33;
    }
    
    @Column(name="USER_DEFINED_34", length=30)
    public String getUserDefined34() {
        return this.userDefined34;
    }
    
    public void setUserDefined34(String userDefined34) {
        this.userDefined34 = userDefined34;
    }
    
    @Column(name="USER_DEFINED_35", length=30)
    public String getUserDefined35() {
        return this.userDefined35;
    }
    
    public void setUserDefined35(String userDefined35) {
        this.userDefined35 = userDefined35;
    }
    
    @Column(name="USER_DEFINED_36", length=30)
    public String getUserDefined36() {
        return this.userDefined36;
    }
    
    public void setUserDefined36(String userDefined36) {
        this.userDefined36 = userDefined36;
    }
    
    @Column(name="USER_DEFINED_37", length=30)
    public String getUserDefined37() {
        return this.userDefined37;
    }
    
    public void setUserDefined37(String userDefined37) {
        this.userDefined37 = userDefined37;
    }
    
    @Column(name="USER_DEFINED_38", length=30)
    public String getUserDefined38() {
        return this.userDefined38;
    }
    
    public void setUserDefined38(String userDefined38) {
        this.userDefined38 = userDefined38;
    }
    
    @Column(name="USER_DEFINED_39", length=30)
    public String getUserDefined39() {
        return this.userDefined39;
    }
    
    public void setUserDefined39(String userDefined39) {
        this.userDefined39 = userDefined39;
    }
    
    @Column(name="USER_DEFINED_40", length=30)
    public String getUserDefined40() {
        return this.userDefined40;
    }
    
    public void setUserDefined40(String userDefined40) {
        this.userDefined40 = userDefined40;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_1", length=7)
    public Date getUserDate1() {
        return this.userDate1;
    }
    
    public void setUserDate1(Date userDate1) {
        this.userDate1 = userDate1;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_2", length=7)
    public Date getUserDate2() {
        return this.userDate2;
    }
    
    public void setUserDate2(Date userDate2) {
        this.userDate2 = userDate2;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_3", length=7)
    public Date getUserDate3() {
        return this.userDate3;
    }
    
    public void setUserDate3(Date userDate3) {
        this.userDate3 = userDate3;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_4", length=7)
    public Date getUserDate4() {
        return this.userDate4;
    }
    
    public void setUserDate4(Date userDate4) {
        this.userDate4 = userDate4;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_5", length=7)
    public Date getUserDate5() {
        return this.userDate5;
    }
    
    public void setUserDate5(Date userDate5) {
        this.userDate5 = userDate5;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_6", length=7)
    public Date getUserDate6() {
        return this.userDate6;
    }
    
    public void setUserDate6(Date userDate6) {
        this.userDate6 = userDate6;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_7", length=7)
    public Date getUserDate7() {
        return this.userDate7;
    }
    
    public void setUserDate7(Date userDate7) {
        this.userDate7 = userDate7;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_8", length=7)
    public Date getUserDate8() {
        return this.userDate8;
    }
    
    public void setUserDate8(Date userDate8) {
        this.userDate8 = userDate8;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_9", length=7)
    public Date getUserDate9() {
        return this.userDate9;
    }
    
    public void setUserDate9(Date userDate9) {
        this.userDate9 = userDate9;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_10", length=7)
    public Date getUserDate10() {
        return this.userDate10;
    }
    
    public void setUserDate10(Date userDate10) {
        this.userDate10 = userDate10;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_11", length=7)
    public Date getUserDate11() {
        return this.userDate11;
    }
    
    public void setUserDate11(Date userDate11) {
        this.userDate11 = userDate11;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_12", length=7)
    public Date getUserDate12() {
        return this.userDate12;
    }
    
    public void setUserDate12(Date userDate12) {
        this.userDate12 = userDate12;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_13", length=7)
    public Date getUserDate13() {
        return this.userDate13;
    }
    
    public void setUserDate13(Date userDate13) {
        this.userDate13 = userDate13;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_14", length=7)
    public Date getUserDate14() {
        return this.userDate14;
    }
    
    public void setUserDate14(Date userDate14) {
        this.userDate14 = userDate14;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_15", length=7)
    public Date getUserDate15() {
        return this.userDate15;
    }
    
    public void setUserDate15(Date userDate15) {
        this.userDate15 = userDate15;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_16", length=7)
    public Date getUserDate16() {
        return this.userDate16;
    }
    
    public void setUserDate16(Date userDate16) {
        this.userDate16 = userDate16;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_17", length=7)
    public Date getUserDate17() {
        return this.userDate17;
    }
    
    public void setUserDate17(Date userDate17) {
        this.userDate17 = userDate17;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_18", length=7)
    public Date getUserDate18() {
        return this.userDate18;
    }
    
    public void setUserDate18(Date userDate18) {
        this.userDate18 = userDate18;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_19", length=7)
    public Date getUserDate19() {
        return this.userDate19;
    }
    
    public void setUserDate19(Date userDate19) {
        this.userDate19 = userDate19;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_20", length=7)
    public Date getUserDate20() {
        return this.userDate20;
    }
    
    public void setUserDate20(Date userDate20) {
        this.userDate20 = userDate20;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }




}


