package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.*;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CobBank generated by hbm2java
 */
@Entity
@Table(name="COB_BANK"
    ,schema="DORIS"
)
public class CobBank extends Base.BaseEntity implements java.io.Serializable {


     private BigDecimal seqCobbkId;
     private ReasonCodeMaster reasonCodeMaster;
     private String cobBankCode;
     private String shortDescription;
     private String description1;
     private String description2;
     private Date effectiveDate;
     private Date termDate;
     private String termReason;
     private String timeFrame;
     private Integer noTfYearsDays;
     private String carryOver;
     private Integer noCoYearsDays;
     private String bankClaimAction;
     private String allGroups;
     private String userDefined1;
     private Date userDate1;
     private String userDefined2;
     private Date userDate2;
     private String securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private Integer seqProcessingOrderId;

    public CobBank() {
    }

	
    public CobBank(BigDecimal seqCobbkId, String cobBankCode, String shortDescription) {
        this.seqCobbkId = seqCobbkId;
        this.cobBankCode = cobBankCode;
        this.shortDescription = shortDescription;
    }
    public CobBank(BigDecimal seqCobbkId, ReasonCodeMaster reasonCodeMaster, String cobBankCode, String shortDescription, String description1, String description2, Date effectiveDate, Date termDate, String termReason, String timeFrame, Integer noTfYearsDays, String carryOver, Integer noCoYearsDays, String bankClaimAction, String allGroups, String userDefined1, Date userDate1, String userDefined2, Date userDate2, String securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, Integer seqProcessingOrderId) {
       this.seqCobbkId = seqCobbkId;
       this.reasonCodeMaster = reasonCodeMaster;
       this.cobBankCode = cobBankCode;
       this.shortDescription = shortDescription;
       this.description1 = description1;
       this.description2 = description2;
       this.effectiveDate = effectiveDate;
       this.termDate = termDate;
       this.termReason = termReason;
       this.timeFrame = timeFrame;
       this.noTfYearsDays = noTfYearsDays;
       this.carryOver = carryOver;
       this.noCoYearsDays = noCoYearsDays;
       this.bankClaimAction = bankClaimAction;
       this.allGroups = allGroups;
       this.userDefined1 = userDefined1;
       this.userDate1 = userDate1;
       this.userDefined2 = userDefined2;
       this.userDate2 = userDate2;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.seqProcessingOrderId = seqProcessingOrderId;
    }
   
     @Id 
    
    @Column(name="SEQ_COBBK_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getSeqCobbkId() {
        return this.seqCobbkId;
    }
    
    public void setSeqCobbkId(BigDecimal seqCobbkId) {
        this.seqCobbkId = seqCobbkId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REASON_CODE")
    public ReasonCodeMaster getReasonCodeMaster() {
        return this.reasonCodeMaster;
    }
    
    public void setReasonCodeMaster(ReasonCodeMaster reasonCodeMaster) {
        this.reasonCodeMaster = reasonCodeMaster;
    }
    
    @Column(name="COB_BANK_CODE", nullable=false, length=5)
    public String getCobBankCode() {
        return this.cobBankCode;
    }
    
    public void setCobBankCode(String cobBankCode) {
        this.cobBankCode = cobBankCode;
    }
    
    @Column(name="SHORT_DESCRIPTION", nullable=false, length=20)
    public String getShortDescription() {
        return this.shortDescription;
    }
    
    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }
    
    @Column(name="DESCRIPTION_1", length=60)
    public String getDescription1() {
        return this.description1;
    }
    
    public void setDescription1(String description1) {
        this.description1 = description1;
    }
    
    @Column(name="DESCRIPTION_2", length=60)
    public String getDescription2() {
        return this.description2;
    }
    
    public void setDescription2(String description2) {
        this.description2 = description2;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", length=7)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="TERM_DATE", length=7)
    public Date getTermDate() {
        return this.termDate;
    }
    
    public void setTermDate(Date termDate) {
        this.termDate = termDate;
    }
    
    @Column(name="TERM_REASON", length=5)
    public String getTermReason() {
        return this.termReason;
    }
    
    public void setTermReason(String termReason) {
        this.termReason = termReason;
    }
    
    @Column(name="TIME_FRAME", length=5)
    public String getTimeFrame() {
        return this.timeFrame;
    }
    
    public void setTimeFrame(String timeFrame) {
        this.timeFrame = timeFrame;
    }
    
    @Column(name="NO_TF_YEARS_DAYS", precision=5, scale=0)
    public Integer getNoTfYearsDays() {
        return this.noTfYearsDays;
    }
    
    public void setNoTfYearsDays(Integer noTfYearsDays) {
        this.noTfYearsDays = noTfYearsDays;
    }
    
    @Column(name="CARRY_OVER", length=5)
    public String getCarryOver() {
        return this.carryOver;
    }
    
    public void setCarryOver(String carryOver) {
        this.carryOver = carryOver;
    }
    
    @Column(name="NO_CO_YEARS_DAYS", precision=5, scale=0)
    public Integer getNoCoYearsDays() {
        return this.noCoYearsDays;
    }
    
    public void setNoCoYearsDays(Integer noCoYearsDays) {
        this.noCoYearsDays = noCoYearsDays;
    }
    
    @Column(name="BANK_CLAIM_ACTION", length=5)
    public String getBankClaimAction() {
        return this.bankClaimAction;
    }
    
    public void setBankClaimAction(String bankClaimAction) {
        this.bankClaimAction = bankClaimAction;
    }
    
    @Column(name="ALL_GROUPS", length=1)
    public String getAllGroups() {
        return this.allGroups;
    }
    
    public void setAllGroups(String allGroups) {
        this.allGroups = allGroups;
    }
    
    @Column(name="USER_DEFINED_1", length=30)
    public String getUserDefined1() {
        return this.userDefined1;
    }
    
    public void setUserDefined1(String userDefined1) {
        this.userDefined1 = userDefined1;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_1", length=7)
    public Date getUserDate1() {
        return this.userDate1;
    }
    
    public void setUserDate1(Date userDate1) {
        this.userDate1 = userDate1;
    }
    
    @Column(name="USER_DEFINED_2", length=30)
    public String getUserDefined2() {
        return this.userDefined2;
    }
    
    public void setUserDefined2(String userDefined2) {
        this.userDefined2 = userDefined2;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_2", length=7)
    public Date getUserDate2() {
        return this.userDate2;
    }
    
    public void setUserDate2(Date userDate2) {
        this.userDate2 = userDate2;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public String getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="SEQ_PROCESSING_ORDER_ID", precision=9, scale=0)
    public Integer getSeqProcessingOrderId() {
        return this.seqProcessingOrderId;
    }
    
    public void setSeqProcessingOrderId(Integer seqProcessingOrderId) {
        this.seqProcessingOrderId = seqProcessingOrderId;
    }




}


