package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.*;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CobBankBenef generated by hbm2java
 */
@Entity
@Table(name="COB_BANK_BENEF"
    ,schema="DORIS"
)
public class CobBankBenef extends Base.BaseEntity implements java.io.Serializable {


     private BigDecimal seqCobbkbenId;
     private BenefitPackageMaster benefitPackageMaster;
     private ReasonCodeMaster reasonCodeMaster;
     private CobBank cobBank;
     private BigDecimal bankOrder;
     private Date effectiveDate;
     private Date termDate;
     private String securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;

    public CobBankBenef() {
    }

	
    public CobBankBenef(BigDecimal seqCobbkbenId, BenefitPackageMaster benefitPackageMaster, CobBank cobBank) {
        this.seqCobbkbenId = seqCobbkbenId;
        this.benefitPackageMaster = benefitPackageMaster;
        this.cobBank = cobBank;
    }
    public CobBankBenef(BigDecimal seqCobbkbenId, BenefitPackageMaster benefitPackageMaster, ReasonCodeMaster reasonCodeMaster, CobBank cobBank, BigDecimal bankOrder, Date effectiveDate, Date termDate, String securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess) {
       this.seqCobbkbenId = seqCobbkbenId;
       this.benefitPackageMaster = benefitPackageMaster;
       this.reasonCodeMaster = reasonCodeMaster;
       this.cobBank = cobBank;
       this.bankOrder = bankOrder;
       this.effectiveDate = effectiveDate;
       this.termDate = termDate;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
    }
   
     @Id 
    
    @Column(name="SEQ_COBBKBEN_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getSeqCobbkbenId() {
        return this.seqCobbkbenId;
    }
    
    public void setSeqCobbkbenId(BigDecimal seqCobbkbenId) {
        this.seqCobbkbenId = seqCobbkbenId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BENEFIT_PACKAGE_ID", nullable=false)
    public BenefitPackageMaster getBenefitPackageMaster() {
        return this.benefitPackageMaster;
    }
    
    public void setBenefitPackageMaster(BenefitPackageMaster benefitPackageMaster) {
        this.benefitPackageMaster = benefitPackageMaster;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TERM_REASON")
    public ReasonCodeMaster getReasonCodeMaster() {
        return this.reasonCodeMaster;
    }
    
    public void setReasonCodeMaster(ReasonCodeMaster reasonCodeMaster) {
        this.reasonCodeMaster = reasonCodeMaster;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SEQ_COBBK_ID", nullable=false)
    public CobBank getCobBank() {
        return this.cobBank;
    }
    
    public void setCobBank(CobBank cobBank) {
        this.cobBank = cobBank;
    }
    
    @Column(name="BANK_ORDER", precision=22, scale=0)
    public BigDecimal getBankOrder() {
        return this.bankOrder;
    }
    
    public void setBankOrder(BigDecimal bankOrder) {
        this.bankOrder = bankOrder;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", length=7)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="TERM_DATE", length=7)
    public Date getTermDate() {
        return this.termDate;
    }
    
    public void setTermDate(Date termDate) {
        this.termDate = termDate;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public String getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }




}


