package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.*;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupContract generated by hbm2java
 */
@Entity
@Table(name="GROUP_CONTRACT"
    ,schema="DORIS"
)
public class GroupContract extends Base.BaseEntity implements java.io.Serializable {


     private GroupContractId id;
     private ReasonCodeMaster reasonCodeMasterByNewbornOthContRsn;
     private ReasonCodeMaster reasonCodeMasterByNewbornProcRsn;
     private ReasonCodeMaster reasonCodeMasterByTermReason;
     private GroupMaster group;
     private ReasonCodeMaster reasonCodeMasterByClaimReason;
     private Date effectiveDate;
     private Date termDate;
     private String brokerName;
     private String salespersonName;
     private Date openEnrollStart;
     private Date openEnrollEnd;
     private Integer numberOfEmployees;
     private Short waitingPeriod;
     private Byte studentAgeFrom;
     private Byte studentAgeTo;
     private Character contractType;
     private String userDefined1;
     private String userDefined2;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private Integer seqAgentId;
     private String userDefined3;
     private String userDefined4;
     private String userDefined5;
     private String userDefined6;
     private String userDefined7;
     private String userDefined8;
     private String userDefined9;
     private String userDefined10;
     private Date userDate1;
     private Date userDate2;
     private Date userDate3;
     private Date userDate4;
     private Date userDate5;
     private Date userDate6;
     private Date userDate7;
     private Date userDate8;
     private Date userDate9;
     private Date userDate10;
     private Short newbornAgeDays;
     private String newbornAutoAdd;
     private String newbornProcMthd;
     private String newbornOthContMthd;
     private String depAgeLimitAction;
     private String depAgeLimitReason;
     private String stuAgeLimitAction;
     private String stuAgeLimitReason;
     private String stuNoVerificationAction;
     private String stuNoVerificationReason;
     private String handcapNoVerfcnAgeAction;
     private String handcapNoVerfcnAgeReason;
     private Integer seqFormatId;
     private BigDecimal claimGraceDays;
     private String claimActionCode;
     private String recordStatus;
     private String depConvOption;
     private String depConvAction;
     private String stuConvOption;
     private String stuConvAction;
     private String comments;

    public GroupContract() {
    }

	
    public GroupContract(GroupContractId id, GroupMaster group, Date effectiveDate) {
        this.id = id;
        this.group = group;
        this.effectiveDate = effectiveDate;
    }
    public GroupContract(GroupContractId id, ReasonCodeMaster reasonCodeMasterByNewbornOthContRsn, ReasonCodeMaster reasonCodeMasterByNewbornProcRsn, ReasonCodeMaster reasonCodeMasterByTermReason, GroupMaster group, ReasonCodeMaster reasonCodeMasterByClaimReason, Date effectiveDate, Date termDate, String brokerName, String salespersonName, Date openEnrollStart, Date openEnrollEnd, Integer numberOfEmployees, Short waitingPeriod, Byte studentAgeFrom, Byte studentAgeTo, Character contractType, String userDefined1, String userDefined2, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, Integer seqAgentId, String userDefined3, String userDefined4, String userDefined5, String userDefined6, String userDefined7, String userDefined8, String userDefined9, String userDefined10, Date userDate1, Date userDate2, Date userDate3, Date userDate4, Date userDate5, Date userDate6, Date userDate7, Date userDate8, Date userDate9, Date userDate10, Short newbornAgeDays, String newbornAutoAdd, String newbornProcMthd, String newbornOthContMthd, String depAgeLimitAction, String depAgeLimitReason, String stuAgeLimitAction, String stuAgeLimitReason, String stuNoVerificationAction, String stuNoVerificationReason, String handcapNoVerfcnAgeAction, String handcapNoVerfcnAgeReason, Integer seqFormatId, BigDecimal claimGraceDays, String claimActionCode, String recordStatus, String depConvOption, String depConvAction, String stuConvOption, String stuConvAction, String comments) {
       this.id = id;
       this.reasonCodeMasterByNewbornOthContRsn = reasonCodeMasterByNewbornOthContRsn;
       this.reasonCodeMasterByNewbornProcRsn = reasonCodeMasterByNewbornProcRsn;
       this.reasonCodeMasterByTermReason = reasonCodeMasterByTermReason;
       this.group = group;
       this.reasonCodeMasterByClaimReason = reasonCodeMasterByClaimReason;
       this.effectiveDate = effectiveDate;
       this.termDate = termDate;
       this.brokerName = brokerName;
       this.salespersonName = salespersonName;
       this.openEnrollStart = openEnrollStart;
       this.openEnrollEnd = openEnrollEnd;
       this.numberOfEmployees = numberOfEmployees;
       this.waitingPeriod = waitingPeriod;
       this.studentAgeFrom = studentAgeFrom;
       this.studentAgeTo = studentAgeTo;
       this.contractType = contractType;
       this.userDefined1 = userDefined1;
       this.userDefined2 = userDefined2;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.seqAgentId = seqAgentId;
       this.userDefined3 = userDefined3;
       this.userDefined4 = userDefined4;
       this.userDefined5 = userDefined5;
       this.userDefined6 = userDefined6;
       this.userDefined7 = userDefined7;
       this.userDefined8 = userDefined8;
       this.userDefined9 = userDefined9;
       this.userDefined10 = userDefined10;
       this.userDate1 = userDate1;
       this.userDate2 = userDate2;
       this.userDate3 = userDate3;
       this.userDate4 = userDate4;
       this.userDate5 = userDate5;
       this.userDate6 = userDate6;
       this.userDate7 = userDate7;
       this.userDate8 = userDate8;
       this.userDate9 = userDate9;
       this.userDate10 = userDate10;
       this.newbornAgeDays = newbornAgeDays;
       this.newbornAutoAdd = newbornAutoAdd;
       this.newbornProcMthd = newbornProcMthd;
       this.newbornOthContMthd = newbornOthContMthd;
       this.depAgeLimitAction = depAgeLimitAction;
       this.depAgeLimitReason = depAgeLimitReason;
       this.stuAgeLimitAction = stuAgeLimitAction;
       this.stuAgeLimitReason = stuAgeLimitReason;
       this.stuNoVerificationAction = stuNoVerificationAction;
       this.stuNoVerificationReason = stuNoVerificationReason;
       this.handcapNoVerfcnAgeAction = handcapNoVerfcnAgeAction;
       this.handcapNoVerfcnAgeReason = handcapNoVerfcnAgeReason;
       this.seqFormatId = seqFormatId;
       this.claimGraceDays = claimGraceDays;
       this.claimActionCode = claimActionCode;
       this.recordStatus = recordStatus;
       this.depConvOption = depConvOption;
       this.depConvAction = depConvAction;
       this.stuConvOption = stuConvOption;
       this.stuConvAction = stuConvAction;
       this.comments = comments;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="seqGroupId", column=@Column(name="SEQ_GROUP_ID", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="seqGroupContract", column=@Column(name="SEQ_GROUP_CONTRACT", nullable=false, precision=9, scale=0) ) } )
    public GroupContractId getId() {
        return this.id;
    }
    
    public void setId(GroupContractId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NEWBORN_OTH_CONT_RSN")
    public ReasonCodeMaster getReasonCodeMasterByNewbornOthContRsn() {
        return this.reasonCodeMasterByNewbornOthContRsn;
    }
    
    public void setReasonCodeMasterByNewbornOthContRsn(ReasonCodeMaster reasonCodeMasterByNewbornOthContRsn) {
        this.reasonCodeMasterByNewbornOthContRsn = reasonCodeMasterByNewbornOthContRsn;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NEWBORN_PROC_RSN")
    public ReasonCodeMaster getReasonCodeMasterByNewbornProcRsn() {
        return this.reasonCodeMasterByNewbornProcRsn;
    }
    
    public void setReasonCodeMasterByNewbornProcRsn(ReasonCodeMaster reasonCodeMasterByNewbornProcRsn) {
        this.reasonCodeMasterByNewbornProcRsn = reasonCodeMasterByNewbornProcRsn;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TERM_REASON")
    public ReasonCodeMaster getReasonCodeMasterByTermReason() {
        return this.reasonCodeMasterByTermReason;
    }
    
    public void setReasonCodeMasterByTermReason(ReasonCodeMaster reasonCodeMasterByTermReason) {
        this.reasonCodeMasterByTermReason = reasonCodeMasterByTermReason;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SEQ_GROUP_ID", nullable=false, insertable=false, updatable=false)
    public GroupMaster getGroup() {
        return this.group;
    }
    
    public void setGroup(GroupMaster group) {
        this.group = group;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLAIM_REASON")
    public ReasonCodeMaster getReasonCodeMasterByClaimReason() {
        return this.reasonCodeMasterByClaimReason;
    }
    
    public void setReasonCodeMasterByClaimReason(ReasonCodeMaster reasonCodeMasterByClaimReason) {
        this.reasonCodeMasterByClaimReason = reasonCodeMasterByClaimReason;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", nullable=false, length=7)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="TERM_DATE", length=7)
    public Date getTermDate() {
        return this.termDate;
    }
    
    public void setTermDate(Date termDate) {
        this.termDate = termDate;
    }
    
    @Column(name="BROKER_NAME", length=30)
    public String getBrokerName() {
        return this.brokerName;
    }
    
    public void setBrokerName(String brokerName) {
        this.brokerName = brokerName;
    }
    
    @Column(name="SALESPERSON_NAME", length=30)
    public String getSalespersonName() {
        return this.salespersonName;
    }
    
    public void setSalespersonName(String salespersonName) {
        this.salespersonName = salespersonName;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="OPEN_ENROLL_START", length=7)
    public Date getOpenEnrollStart() {
        return this.openEnrollStart;
    }
    
    public void setOpenEnrollStart(Date openEnrollStart) {
        this.openEnrollStart = openEnrollStart;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="OPEN_ENROLL_END", length=7)
    public Date getOpenEnrollEnd() {
        return this.openEnrollEnd;
    }
    
    public void setOpenEnrollEnd(Date openEnrollEnd) {
        this.openEnrollEnd = openEnrollEnd;
    }
    
    @Column(name="NUMBER_OF_EMPLOYEES", precision=6, scale=0)
    public Integer getNumberOfEmployees() {
        return this.numberOfEmployees;
    }
    
    public void setNumberOfEmployees(Integer numberOfEmployees) {
        this.numberOfEmployees = numberOfEmployees;
    }
    
    @Column(name="WAITING_PERIOD", precision=3, scale=0)
    public Short getWaitingPeriod() {
        return this.waitingPeriod;
    }
    
    public void setWaitingPeriod(Short waitingPeriod) {
        this.waitingPeriod = waitingPeriod;
    }
    
    @Column(name="STUDENT_AGE_FROM", precision=2, scale=0)
    public Byte getStudentAgeFrom() {
        return this.studentAgeFrom;
    }
    
    public void setStudentAgeFrom(Byte studentAgeFrom) {
        this.studentAgeFrom = studentAgeFrom;
    }
    
    @Column(name="STUDENT_AGE_TO", precision=2, scale=0)
    public Byte getStudentAgeTo() {
        return this.studentAgeTo;
    }
    
    public void setStudentAgeTo(Byte studentAgeTo) {
        this.studentAgeTo = studentAgeTo;
    }
    
    @Column(name="CONTRACT_TYPE", length=1)
    public Character getContractType() {
        return this.contractType;
    }
    
    public void setContractType(Character contractType) {
        this.contractType = contractType;
    }
    
    @Column(name="USER_DEFINED_1", length=15)
    public String getUserDefined1() {
        return this.userDefined1;
    }
    
    public void setUserDefined1(String userDefined1) {
        this.userDefined1 = userDefined1;
    }
    
    @Column(name="USER_DEFINED_2", length=15)
    public String getUserDefined2() {
        return this.userDefined2;
    }
    
    public void setUserDefined2(String userDefined2) {
        this.userDefined2 = userDefined2;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="SEQ_AGENT_ID", precision=9, scale=0)
    public Integer getSeqAgentId() {
        return this.seqAgentId;
    }
    
    public void setSeqAgentId(Integer seqAgentId) {
        this.seqAgentId = seqAgentId;
    }
    
    @Column(name="USER_DEFINED_3", length=30)
    public String getUserDefined3() {
        return this.userDefined3;
    }
    
    public void setUserDefined3(String userDefined3) {
        this.userDefined3 = userDefined3;
    }
    
    @Column(name="USER_DEFINED_4", length=30)
    public String getUserDefined4() {
        return this.userDefined4;
    }
    
    public void setUserDefined4(String userDefined4) {
        this.userDefined4 = userDefined4;
    }
    
    @Column(name="USER_DEFINED_5", length=30)
    public String getUserDefined5() {
        return this.userDefined5;
    }
    
    public void setUserDefined5(String userDefined5) {
        this.userDefined5 = userDefined5;
    }
    
    @Column(name="USER_DEFINED_6", length=30)
    public String getUserDefined6() {
        return this.userDefined6;
    }
    
    public void setUserDefined6(String userDefined6) {
        this.userDefined6 = userDefined6;
    }
    
    @Column(name="USER_DEFINED_7", length=30)
    public String getUserDefined7() {
        return this.userDefined7;
    }
    
    public void setUserDefined7(String userDefined7) {
        this.userDefined7 = userDefined7;
    }
    
    @Column(name="USER_DEFINED_8", length=30)
    public String getUserDefined8() {
        return this.userDefined8;
    }
    
    public void setUserDefined8(String userDefined8) {
        this.userDefined8 = userDefined8;
    }
    
    @Column(name="USER_DEFINED_9", length=30)
    public String getUserDefined9() {
        return this.userDefined9;
    }
    
    public void setUserDefined9(String userDefined9) {
        this.userDefined9 = userDefined9;
    }
    
    @Column(name="USER_DEFINED_10", length=30)
    public String getUserDefined10() {
        return this.userDefined10;
    }
    
    public void setUserDefined10(String userDefined10) {
        this.userDefined10 = userDefined10;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_1", length=7)
    public Date getUserDate1() {
        return this.userDate1;
    }
    
    public void setUserDate1(Date userDate1) {
        this.userDate1 = userDate1;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_2", length=7)
    public Date getUserDate2() {
        return this.userDate2;
    }
    
    public void setUserDate2(Date userDate2) {
        this.userDate2 = userDate2;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_3", length=7)
    public Date getUserDate3() {
        return this.userDate3;
    }
    
    public void setUserDate3(Date userDate3) {
        this.userDate3 = userDate3;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_4", length=7)
    public Date getUserDate4() {
        return this.userDate4;
    }
    
    public void setUserDate4(Date userDate4) {
        this.userDate4 = userDate4;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_5", length=7)
    public Date getUserDate5() {
        return this.userDate5;
    }
    
    public void setUserDate5(Date userDate5) {
        this.userDate5 = userDate5;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_6", length=7)
    public Date getUserDate6() {
        return this.userDate6;
    }
    
    public void setUserDate6(Date userDate6) {
        this.userDate6 = userDate6;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_7", length=7)
    public Date getUserDate7() {
        return this.userDate7;
    }
    
    public void setUserDate7(Date userDate7) {
        this.userDate7 = userDate7;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_8", length=7)
    public Date getUserDate8() {
        return this.userDate8;
    }
    
    public void setUserDate8(Date userDate8) {
        this.userDate8 = userDate8;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_9", length=7)
    public Date getUserDate9() {
        return this.userDate9;
    }
    
    public void setUserDate9(Date userDate9) {
        this.userDate9 = userDate9;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_10", length=7)
    public Date getUserDate10() {
        return this.userDate10;
    }
    
    public void setUserDate10(Date userDate10) {
        this.userDate10 = userDate10;
    }
    
    @Column(name="NEWBORN_AGE_DAYS", precision=3, scale=0)
    public Short getNewbornAgeDays() {
        return this.newbornAgeDays;
    }
    
    public void setNewbornAgeDays(Short newbornAgeDays) {
        this.newbornAgeDays = newbornAgeDays;
    }
    
    @Column(name="NEWBORN_AUTO_ADD", length=1)
    public String getNewbornAutoAdd() {
        return this.newbornAutoAdd;
    }
    
    public void setNewbornAutoAdd(String newbornAutoAdd) {
        this.newbornAutoAdd = newbornAutoAdd;
    }
    
    @Column(name="NEWBORN_PROC_MTHD", length=1)
    public String getNewbornProcMthd() {
        return this.newbornProcMthd;
    }
    
    public void setNewbornProcMthd(String newbornProcMthd) {
        this.newbornProcMthd = newbornProcMthd;
    }
    
    @Column(name="NEWBORN_OTH_CONT_MTHD", length=1)
    public String getNewbornOthContMthd() {
        return this.newbornOthContMthd;
    }
    
    public void setNewbornOthContMthd(String newbornOthContMthd) {
        this.newbornOthContMthd = newbornOthContMthd;
    }
    
    @Column(name="DEP_AGE_LIMIT_ACTION", length=5)
    public String getDepAgeLimitAction() {
        return this.depAgeLimitAction;
    }
    
    public void setDepAgeLimitAction(String depAgeLimitAction) {
        this.depAgeLimitAction = depAgeLimitAction;
    }
    
    @Column(name="DEP_AGE_LIMIT_REASON", length=5)
    public String getDepAgeLimitReason() {
        return this.depAgeLimitReason;
    }
    
    public void setDepAgeLimitReason(String depAgeLimitReason) {
        this.depAgeLimitReason = depAgeLimitReason;
    }
    
    @Column(name="STU_AGE_LIMIT_ACTION", length=5)
    public String getStuAgeLimitAction() {
        return this.stuAgeLimitAction;
    }
    
    public void setStuAgeLimitAction(String stuAgeLimitAction) {
        this.stuAgeLimitAction = stuAgeLimitAction;
    }
    
    @Column(name="STU_AGE_LIMIT_REASON", length=5)
    public String getStuAgeLimitReason() {
        return this.stuAgeLimitReason;
    }
    
    public void setStuAgeLimitReason(String stuAgeLimitReason) {
        this.stuAgeLimitReason = stuAgeLimitReason;
    }
    
    @Column(name="STU_NO_VERIFICATION_ACTION", length=5)
    public String getStuNoVerificationAction() {
        return this.stuNoVerificationAction;
    }
    
    public void setStuNoVerificationAction(String stuNoVerificationAction) {
        this.stuNoVerificationAction = stuNoVerificationAction;
    }
    
    @Column(name="STU_NO_VERIFICATION_REASON", length=5)
    public String getStuNoVerificationReason() {
        return this.stuNoVerificationReason;
    }
    
    public void setStuNoVerificationReason(String stuNoVerificationReason) {
        this.stuNoVerificationReason = stuNoVerificationReason;
    }
    
    @Column(name="HANDCAP_NO_VERFCN_AGE_ACTION", length=5)
    public String getHandcapNoVerfcnAgeAction() {
        return this.handcapNoVerfcnAgeAction;
    }
    
    public void setHandcapNoVerfcnAgeAction(String handcapNoVerfcnAgeAction) {
        this.handcapNoVerfcnAgeAction = handcapNoVerfcnAgeAction;
    }
    
    @Column(name="HANDCAP_NO_VERFCN_AGE_REASON", length=5)
    public String getHandcapNoVerfcnAgeReason() {
        return this.handcapNoVerfcnAgeReason;
    }
    
    public void setHandcapNoVerfcnAgeReason(String handcapNoVerfcnAgeReason) {
        this.handcapNoVerfcnAgeReason = handcapNoVerfcnAgeReason;
    }
    
    @Column(name="SEQ_FORMAT_ID", precision=9, scale=0)
    public Integer getSeqFormatId() {
        return this.seqFormatId;
    }
    
    public void setSeqFormatId(Integer seqFormatId) {
        this.seqFormatId = seqFormatId;
    }
    
    @Column(name="CLAIM_GRACE_DAYS", precision=22, scale=0)
    public BigDecimal getClaimGraceDays() {
        return this.claimGraceDays;
    }
    
    public void setClaimGraceDays(BigDecimal claimGraceDays) {
        this.claimGraceDays = claimGraceDays;
    }
    
    @Column(name="CLAIM_ACTION_CODE", length=4)
    public String getClaimActionCode() {
        return this.claimActionCode;
    }
    
    public void setClaimActionCode(String claimActionCode) {
        this.claimActionCode = claimActionCode;
    }
    
    @Column(name="RECORD_STATUS", length=15)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }
    
    @Column(name="DEP_CONV_OPTION", length=15)
    public String getDepConvOption() {
        return this.depConvOption;
    }
    
    public void setDepConvOption(String depConvOption) {
        this.depConvOption = depConvOption;
    }
    
    @Column(name="DEP_CONV_ACTION", length=15)
    public String getDepConvAction() {
        return this.depConvAction;
    }
    
    public void setDepConvAction(String depConvAction) {
        this.depConvAction = depConvAction;
    }
    
    @Column(name="STU_CONV_OPTION", length=15)
    public String getStuConvOption() {
        return this.stuConvOption;
    }
    
    public void setStuConvOption(String stuConvOption) {
        this.stuConvOption = stuConvOption;
    }
    
    @Column(name="STU_CONV_ACTION", length=15)
    public String getStuConvAction() {
        return this.stuConvAction;
    }
    
    public void setStuConvAction(String stuConvAction) {
        this.stuConvAction = stuConvAction;
    }
    
    @Column(name="COMMENTS", length=80)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


