package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LineOfBusinessMaster generated by hbm2java
 */
@Entity
@Table(name="LINE_OF_BUSINESS_MASTER"
    ,schema="DORIS"
)
public class LineOfBusinessMaster extends Base.BaseEntity implements java.io.Serializable {


     private String lineOfBusiness;
     private ReasonCodeMaster reasonCodeMasterByNonParReasonCode;
     private ReasonCodeMaster reasonCodeMasterByNewbornProcRsn;
     private ReasonCodeMaster reasonCodeMasterByTargetRevReason;
     private ReasonCodeMaster reasonCodeMasterByParReasonCode;
     private String description;
     private String name;
     private String addressLine1;
     private String addressLine2;
     private String city;
     private String state;
     private String zipCode;
     private String phoneNumber;
     private String faxNumber;
     private Character pricePriorityRule;
     private Integer providerDefault;
     private Character pcpRequired;
     private Character eobPrintFlag;
     private Character subDepEditSwitch;
     private String claimDupRule;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private Character performAuthClaimMatch;
     private Short authClaimMatchDaysBefore;
     private Short authClaimMatchDaysAfter;
     private Character coveringProvInd;
     private String country;
     private char inclmSwitch;
     private Character performAuthWaive;
     private Character authLevel;
     private char allowedGreaterThanBilled;
     private Character targetRevCodeEditFlg;
     private String targetRevAction;
     private Integer indPcpMaxEnrollLmt;
     private BigDecimal indPcpThreshold;
     private BigDecimal seqDefPcp;
     private BigDecimal seqFailPcp;
     private Short idcardReinstDays;
     private char familyAffiliation;
     private char useApcEditor;
     private Character editType;
     private char useApcGrouper;
     private Character grouperAction;
     private String grouperReasonCode;
     private char useApcPricer;
     private Character pricerAction;
     private String pricerReasonCode;
     private String pricerNotCovReason;
     private Character interestDeterminant;
     private Character useResetDateFlag;
     private Character intDscntPaySub;
     private Character calcIntDscnt;
     private Character applyUncleanInd;
     private String userDefined1;
     private String userDefined2;
     private Date userDate1;
     private Date userDate2;
     private Character certifiedFlg;
     private Short ageFrom;
     private Short ageThrough;
     private Character siteFlg;
     private String waiveMatchOrder;
     private Character penApplyUncleanInd;
     private Character mcIndicator;
     private Character dateOfDeathRule;
     private String newbornProcessing;
     private BigDecimal newbornAgeDays;
     private String newbornProcMthd;
     private String intrDetrProcess;
     private String discDetrProcess;
     private String autoPayeeDeterm;
     private String applyGraceDays;
     private BigDecimal defaultGraceDays;
     private String dualBsAwaiveReq;
     private String dualBsAuthLevel;
     private String dualBsAwaiveMorder;
     private BigDecimal seqId;
     private String cobBank;
     private String authDetail;
     private String interimBillOutsideEligAct;
     private String interimBillOutsideEligRsn;
     private String benefitCarryoverInd;
     private String resetAuthParCode;
     private String resetAuthRsnCode;
     private String resetClaimParCode;
     private String resetClaimRsnCode;
     private String memberAddressUpdates;
     private String defaultAddrEffDate;
     private String tfwavRuleId;
     private String referral;
     private String refprov;
     private String attprov;
     private String evaluateMbrSvcArea;
     private String action;
     private String reasonCode;
     private String rxBin;
     private String rxPcn;
     private String rxGroup;
     private String pbpNumber;
     private String pricerAllowedReason;
     private String surgeryRule;
     private String surgeryRuleInst;
     private String surgeryHierarchyInst;
     private String ocOffsetReason;
     private Set<PremiumMaster> premiumMasters = new HashSet<PremiumMaster>(0);

    public LineOfBusinessMaster() {
    }

	
    public LineOfBusinessMaster(String lineOfBusiness, String description, char inclmSwitch, char allowedGreaterThanBilled, char familyAffiliation, char useApcEditor, char useApcGrouper, char useApcPricer, String intrDetrProcess, String discDetrProcess, BigDecimal seqId) {
        this.lineOfBusiness = lineOfBusiness;
        this.description = description;
        this.inclmSwitch = inclmSwitch;
        this.allowedGreaterThanBilled = allowedGreaterThanBilled;
        this.familyAffiliation = familyAffiliation;
        this.useApcEditor = useApcEditor;
        this.useApcGrouper = useApcGrouper;
        this.useApcPricer = useApcPricer;
        this.intrDetrProcess = intrDetrProcess;
        this.discDetrProcess = discDetrProcess;
        this.seqId = seqId;
    }
    public LineOfBusinessMaster(String lineOfBusiness, ReasonCodeMaster reasonCodeMasterByNonParReasonCode, ReasonCodeMaster reasonCodeMasterByNewbornProcRsn, ReasonCodeMaster reasonCodeMasterByTargetRevReason, ReasonCodeMaster reasonCodeMasterByParReasonCode, String description, String name, String addressLine1, String addressLine2, String city, String state, String zipCode, String phoneNumber, String faxNumber, Character pricePriorityRule, Integer providerDefault, Character pcpRequired, Character eobPrintFlag, Character subDepEditSwitch, String claimDupRule, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, Character performAuthClaimMatch, Short authClaimMatchDaysBefore, Short authClaimMatchDaysAfter, Character coveringProvInd, String country, char inclmSwitch, Character performAuthWaive, Character authLevel, char allowedGreaterThanBilled, Character targetRevCodeEditFlg, String targetRevAction, Integer indPcpMaxEnrollLmt, BigDecimal indPcpThreshold, BigDecimal seqDefPcp, BigDecimal seqFailPcp, Short idcardReinstDays, char familyAffiliation, char useApcEditor, Character editType, char useApcGrouper, Character grouperAction, String grouperReasonCode, char useApcPricer, Character pricerAction, String pricerReasonCode, String pricerNotCovReason, Character interestDeterminant, Character useResetDateFlag, Character intDscntPaySub, Character calcIntDscnt, Character applyUncleanInd, String userDefined1, String userDefined2, Date userDate1, Date userDate2, Character certifiedFlg, Short ageFrom, Short ageThrough, Character siteFlg, String waiveMatchOrder, Character penApplyUncleanInd, Character mcIndicator, Character dateOfDeathRule, String newbornProcessing, BigDecimal newbornAgeDays, String newbornProcMthd, String intrDetrProcess, String discDetrProcess, String autoPayeeDeterm, String applyGraceDays, BigDecimal defaultGraceDays, String dualBsAwaiveReq, String dualBsAuthLevel, String dualBsAwaiveMorder, BigDecimal seqId, String cobBank, String authDetail, String interimBillOutsideEligAct, String interimBillOutsideEligRsn, String benefitCarryoverInd, String resetAuthParCode, String resetAuthRsnCode, String resetClaimParCode, String resetClaimRsnCode, String memberAddressUpdates, String defaultAddrEffDate, String tfwavRuleId, String referral, String refprov, String attprov, String evaluateMbrSvcArea, String action, String reasonCode, String rxBin, String rxPcn, String rxGroup, String pbpNumber, String pricerAllowedReason, String surgeryRule, String surgeryRuleInst, String surgeryHierarchyInst, String ocOffsetReason, Set<PremiumMaster> premiumMasters) {
       this.lineOfBusiness = lineOfBusiness;
       this.reasonCodeMasterByNonParReasonCode = reasonCodeMasterByNonParReasonCode;
       this.reasonCodeMasterByNewbornProcRsn = reasonCodeMasterByNewbornProcRsn;
       this.reasonCodeMasterByTargetRevReason = reasonCodeMasterByTargetRevReason;
       this.reasonCodeMasterByParReasonCode = reasonCodeMasterByParReasonCode;
       this.description = description;
       this.name = name;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.city = city;
       this.state = state;
       this.zipCode = zipCode;
       this.phoneNumber = phoneNumber;
       this.faxNumber = faxNumber;
       this.pricePriorityRule = pricePriorityRule;
       this.providerDefault = providerDefault;
       this.pcpRequired = pcpRequired;
       this.eobPrintFlag = eobPrintFlag;
       this.subDepEditSwitch = subDepEditSwitch;
       this.claimDupRule = claimDupRule;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.performAuthClaimMatch = performAuthClaimMatch;
       this.authClaimMatchDaysBefore = authClaimMatchDaysBefore;
       this.authClaimMatchDaysAfter = authClaimMatchDaysAfter;
       this.coveringProvInd = coveringProvInd;
       this.country = country;
       this.inclmSwitch = inclmSwitch;
       this.performAuthWaive = performAuthWaive;
       this.authLevel = authLevel;
       this.allowedGreaterThanBilled = allowedGreaterThanBilled;
       this.targetRevCodeEditFlg = targetRevCodeEditFlg;
       this.targetRevAction = targetRevAction;
       this.indPcpMaxEnrollLmt = indPcpMaxEnrollLmt;
       this.indPcpThreshold = indPcpThreshold;
       this.seqDefPcp = seqDefPcp;
       this.seqFailPcp = seqFailPcp;
       this.idcardReinstDays = idcardReinstDays;
       this.familyAffiliation = familyAffiliation;
       this.useApcEditor = useApcEditor;
       this.editType = editType;
       this.useApcGrouper = useApcGrouper;
       this.grouperAction = grouperAction;
       this.grouperReasonCode = grouperReasonCode;
       this.useApcPricer = useApcPricer;
       this.pricerAction = pricerAction;
       this.pricerReasonCode = pricerReasonCode;
       this.pricerNotCovReason = pricerNotCovReason;
       this.interestDeterminant = interestDeterminant;
       this.useResetDateFlag = useResetDateFlag;
       this.intDscntPaySub = intDscntPaySub;
       this.calcIntDscnt = calcIntDscnt;
       this.applyUncleanInd = applyUncleanInd;
       this.userDefined1 = userDefined1;
       this.userDefined2 = userDefined2;
       this.userDate1 = userDate1;
       this.userDate2 = userDate2;
       this.certifiedFlg = certifiedFlg;
       this.ageFrom = ageFrom;
       this.ageThrough = ageThrough;
       this.siteFlg = siteFlg;
       this.waiveMatchOrder = waiveMatchOrder;
       this.penApplyUncleanInd = penApplyUncleanInd;
       this.mcIndicator = mcIndicator;
       this.dateOfDeathRule = dateOfDeathRule;
       this.newbornProcessing = newbornProcessing;
       this.newbornAgeDays = newbornAgeDays;
       this.newbornProcMthd = newbornProcMthd;
       this.intrDetrProcess = intrDetrProcess;
       this.discDetrProcess = discDetrProcess;
       this.autoPayeeDeterm = autoPayeeDeterm;
       this.applyGraceDays = applyGraceDays;
       this.defaultGraceDays = defaultGraceDays;
       this.dualBsAwaiveReq = dualBsAwaiveReq;
       this.dualBsAuthLevel = dualBsAuthLevel;
       this.dualBsAwaiveMorder = dualBsAwaiveMorder;
       this.seqId = seqId;
       this.cobBank = cobBank;
       this.authDetail = authDetail;
       this.interimBillOutsideEligAct = interimBillOutsideEligAct;
       this.interimBillOutsideEligRsn = interimBillOutsideEligRsn;
       this.benefitCarryoverInd = benefitCarryoverInd;
       this.resetAuthParCode = resetAuthParCode;
       this.resetAuthRsnCode = resetAuthRsnCode;
       this.resetClaimParCode = resetClaimParCode;
       this.resetClaimRsnCode = resetClaimRsnCode;
       this.memberAddressUpdates = memberAddressUpdates;
       this.defaultAddrEffDate = defaultAddrEffDate;
       this.tfwavRuleId = tfwavRuleId;
       this.referral = referral;
       this.refprov = refprov;
       this.attprov = attprov;
       this.evaluateMbrSvcArea = evaluateMbrSvcArea;
       this.action = action;
       this.reasonCode = reasonCode;
       this.rxBin = rxBin;
       this.rxPcn = rxPcn;
       this.rxGroup = rxGroup;
       this.pbpNumber = pbpNumber;
       this.pricerAllowedReason = pricerAllowedReason;
       this.surgeryRule = surgeryRule;
       this.surgeryRuleInst = surgeryRuleInst;
       this.surgeryHierarchyInst = surgeryHierarchyInst;
       this.ocOffsetReason = ocOffsetReason;
       this.premiumMasters = premiumMasters;
    }
   
     @Id 
    
    @Column(name="LINE_OF_BUSINESS", nullable=false, length=3)
    public String getLineOfBusiness() {
        return this.lineOfBusiness;
    }
    
    public void setLineOfBusiness(String lineOfBusiness) {
        this.lineOfBusiness = lineOfBusiness;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NON_PAR_REASON_CODE")
    public ReasonCodeMaster getReasonCodeMasterByNonParReasonCode() {
        return this.reasonCodeMasterByNonParReasonCode;
    }
    
    public void setReasonCodeMasterByNonParReasonCode(ReasonCodeMaster reasonCodeMasterByNonParReasonCode) {
        this.reasonCodeMasterByNonParReasonCode = reasonCodeMasterByNonParReasonCode;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NEWBORN_PROC_RSN")
    public ReasonCodeMaster getReasonCodeMasterByNewbornProcRsn() {
        return this.reasonCodeMasterByNewbornProcRsn;
    }
    
    public void setReasonCodeMasterByNewbornProcRsn(ReasonCodeMaster reasonCodeMasterByNewbornProcRsn) {
        this.reasonCodeMasterByNewbornProcRsn = reasonCodeMasterByNewbornProcRsn;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TARGET_REV_REASON")
    public ReasonCodeMaster getReasonCodeMasterByTargetRevReason() {
        return this.reasonCodeMasterByTargetRevReason;
    }
    
    public void setReasonCodeMasterByTargetRevReason(ReasonCodeMaster reasonCodeMasterByTargetRevReason) {
        this.reasonCodeMasterByTargetRevReason = reasonCodeMasterByTargetRevReason;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAR_REASON_CODE")
    public ReasonCodeMaster getReasonCodeMasterByParReasonCode() {
        return this.reasonCodeMasterByParReasonCode;
    }
    
    public void setReasonCodeMasterByParReasonCode(ReasonCodeMaster reasonCodeMasterByParReasonCode) {
        this.reasonCodeMasterByParReasonCode = reasonCodeMasterByParReasonCode;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=30)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="NAME", length=40)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="ADDRESS_LINE_1", length=40)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    
    @Column(name="ADDRESS_LINE_2", length=40)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    
    @Column(name="CITY", length=30)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="STATE", length=6)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="ZIP_CODE", length=15)
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    
    @Column(name="PHONE_NUMBER", length=20)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    @Column(name="FAX_NUMBER", length=20)
    public String getFaxNumber() {
        return this.faxNumber;
    }
    
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }
    
    @Column(name="PRICE_PRIORITY_RULE", length=1)
    public Character getPricePriorityRule() {
        return this.pricePriorityRule;
    }
    
    public void setPricePriorityRule(Character pricePriorityRule) {
        this.pricePriorityRule = pricePriorityRule;
    }
    
    @Column(name="PROVIDER_DEFAULT", precision=9, scale=0)
    public Integer getProviderDefault() {
        return this.providerDefault;
    }
    
    public void setProviderDefault(Integer providerDefault) {
        this.providerDefault = providerDefault;
    }
    
    @Column(name="PCP_REQUIRED", length=1)
    public Character getPcpRequired() {
        return this.pcpRequired;
    }
    
    public void setPcpRequired(Character pcpRequired) {
        this.pcpRequired = pcpRequired;
    }
    
    @Column(name="EOB_PRINT_FLAG", length=1)
    public Character getEobPrintFlag() {
        return this.eobPrintFlag;
    }
    
    public void setEobPrintFlag(Character eobPrintFlag) {
        this.eobPrintFlag = eobPrintFlag;
    }
    
    @Column(name="SUB_DEP_EDIT_SWITCH", length=1)
    public Character getSubDepEditSwitch() {
        return this.subDepEditSwitch;
    }
    
    public void setSubDepEditSwitch(Character subDepEditSwitch) {
        this.subDepEditSwitch = subDepEditSwitch;
    }
    
    @Column(name="CLAIM_DUP_RULE", length=2)
    public String getClaimDupRule() {
        return this.claimDupRule;
    }
    
    public void setClaimDupRule(String claimDupRule) {
        this.claimDupRule = claimDupRule;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="PERFORM_AUTH_CLAIM_MATCH", length=1)
    public Character getPerformAuthClaimMatch() {
        return this.performAuthClaimMatch;
    }
    
    public void setPerformAuthClaimMatch(Character performAuthClaimMatch) {
        this.performAuthClaimMatch = performAuthClaimMatch;
    }
    
    @Column(name="AUTH_CLAIM_MATCH_DAYS_BEFORE", precision=3, scale=0)
    public Short getAuthClaimMatchDaysBefore() {
        return this.authClaimMatchDaysBefore;
    }
    
    public void setAuthClaimMatchDaysBefore(Short authClaimMatchDaysBefore) {
        this.authClaimMatchDaysBefore = authClaimMatchDaysBefore;
    }
    
    @Column(name="AUTH_CLAIM_MATCH_DAYS_AFTER", precision=3, scale=0)
    public Short getAuthClaimMatchDaysAfter() {
        return this.authClaimMatchDaysAfter;
    }
    
    public void setAuthClaimMatchDaysAfter(Short authClaimMatchDaysAfter) {
        this.authClaimMatchDaysAfter = authClaimMatchDaysAfter;
    }
    
    @Column(name="COVERING_PROV_IND", length=1)
    public Character getCoveringProvInd() {
        return this.coveringProvInd;
    }
    
    public void setCoveringProvInd(Character coveringProvInd) {
        this.coveringProvInd = coveringProvInd;
    }
    
    @Column(name="COUNTRY", length=20)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="INCLM_SWITCH", nullable=false, length=1)
    public char getInclmSwitch() {
        return this.inclmSwitch;
    }
    
    public void setInclmSwitch(char inclmSwitch) {
        this.inclmSwitch = inclmSwitch;
    }
    
    @Column(name="PERFORM_AUTH_WAIVE", length=1)
    public Character getPerformAuthWaive() {
        return this.performAuthWaive;
    }
    
    public void setPerformAuthWaive(Character performAuthWaive) {
        this.performAuthWaive = performAuthWaive;
    }
    
    @Column(name="AUTH_LEVEL", length=1)
    public Character getAuthLevel() {
        return this.authLevel;
    }
    
    public void setAuthLevel(Character authLevel) {
        this.authLevel = authLevel;
    }
    
    @Column(name="ALLOWED_GREATER_THAN_BILLED", nullable=false, length=1)
    public char getAllowedGreaterThanBilled() {
        return this.allowedGreaterThanBilled;
    }
    
    public void setAllowedGreaterThanBilled(char allowedGreaterThanBilled) {
        this.allowedGreaterThanBilled = allowedGreaterThanBilled;
    }
    
    @Column(name="TARGET_REV_CODE_EDIT_FLG", length=1)
    public Character getTargetRevCodeEditFlg() {
        return this.targetRevCodeEditFlg;
    }
    
    public void setTargetRevCodeEditFlg(Character targetRevCodeEditFlg) {
        this.targetRevCodeEditFlg = targetRevCodeEditFlg;
    }
    
    @Column(name="TARGET_REV_ACTION", length=2)
    public String getTargetRevAction() {
        return this.targetRevAction;
    }
    
    public void setTargetRevAction(String targetRevAction) {
        this.targetRevAction = targetRevAction;
    }
    
    @Column(name="IND_PCP_MAX_ENROLL_LMT", precision=5, scale=0)
    public Integer getIndPcpMaxEnrollLmt() {
        return this.indPcpMaxEnrollLmt;
    }
    
    public void setIndPcpMaxEnrollLmt(Integer indPcpMaxEnrollLmt) {
        this.indPcpMaxEnrollLmt = indPcpMaxEnrollLmt;
    }
    
    @Column(name="IND_PCP_THRESHOLD", precision=5, scale=4)
    public BigDecimal getIndPcpThreshold() {
        return this.indPcpThreshold;
    }
    
    public void setIndPcpThreshold(BigDecimal indPcpThreshold) {
        this.indPcpThreshold = indPcpThreshold;
    }
    
    @Column(name="SEQ_DEF_PCP", precision=22, scale=0)
    public BigDecimal getSeqDefPcp() {
        return this.seqDefPcp;
    }
    
    public void setSeqDefPcp(BigDecimal seqDefPcp) {
        this.seqDefPcp = seqDefPcp;
    }
    
    @Column(name="SEQ_FAIL_PCP", precision=22, scale=0)
    public BigDecimal getSeqFailPcp() {
        return this.seqFailPcp;
    }
    
    public void setSeqFailPcp(BigDecimal seqFailPcp) {
        this.seqFailPcp = seqFailPcp;
    }
    
    @Column(name="IDCARD_REINST_DAYS", precision=3, scale=0)
    public Short getIdcardReinstDays() {
        return this.idcardReinstDays;
    }
    
    public void setIdcardReinstDays(Short idcardReinstDays) {
        this.idcardReinstDays = idcardReinstDays;
    }
    
    @Column(name="FAMILY_AFFILIATION", nullable=false, length=1)
    public char getFamilyAffiliation() {
        return this.familyAffiliation;
    }
    
    public void setFamilyAffiliation(char familyAffiliation) {
        this.familyAffiliation = familyAffiliation;
    }
    
    @Column(name="USE_APC_EDITOR", nullable=false, length=1)
    public char getUseApcEditor() {
        return this.useApcEditor;
    }
    
    public void setUseApcEditor(char useApcEditor) {
        this.useApcEditor = useApcEditor;
    }
    
    @Column(name="EDIT_TYPE", length=1)
    public Character getEditType() {
        return this.editType;
    }
    
    public void setEditType(Character editType) {
        this.editType = editType;
    }
    
    @Column(name="USE_APC_GROUPER", nullable=false, length=1)
    public char getUseApcGrouper() {
        return this.useApcGrouper;
    }
    
    public void setUseApcGrouper(char useApcGrouper) {
        this.useApcGrouper = useApcGrouper;
    }
    
    @Column(name="GROUPER_ACTION", length=1)
    public Character getGrouperAction() {
        return this.grouperAction;
    }
    
    public void setGrouperAction(Character grouperAction) {
        this.grouperAction = grouperAction;
    }
    
    @Column(name="GROUPER_REASON_CODE", length=5)
    public String getGrouperReasonCode() {
        return this.grouperReasonCode;
    }
    
    public void setGrouperReasonCode(String grouperReasonCode) {
        this.grouperReasonCode = grouperReasonCode;
    }
    
    @Column(name="USE_APC_PRICER", nullable=false, length=1)
    public char getUseApcPricer() {
        return this.useApcPricer;
    }
    
    public void setUseApcPricer(char useApcPricer) {
        this.useApcPricer = useApcPricer;
    }
    
    @Column(name="PRICER_ACTION", length=1)
    public Character getPricerAction() {
        return this.pricerAction;
    }
    
    public void setPricerAction(Character pricerAction) {
        this.pricerAction = pricerAction;
    }
    
    @Column(name="PRICER_REASON_CODE", length=5)
    public String getPricerReasonCode() {
        return this.pricerReasonCode;
    }
    
    public void setPricerReasonCode(String pricerReasonCode) {
        this.pricerReasonCode = pricerReasonCode;
    }
    
    @Column(name="PRICER_NOT_COV_REASON", length=5)
    public String getPricerNotCovReason() {
        return this.pricerNotCovReason;
    }
    
    public void setPricerNotCovReason(String pricerNotCovReason) {
        this.pricerNotCovReason = pricerNotCovReason;
    }
    
    @Column(name="INTEREST_DETERMINANT", length=1)
    public Character getInterestDeterminant() {
        return this.interestDeterminant;
    }
    
    public void setInterestDeterminant(Character interestDeterminant) {
        this.interestDeterminant = interestDeterminant;
    }
    
    @Column(name="USE_RESET_DATE_FLAG", length=1)
    public Character getUseResetDateFlag() {
        return this.useResetDateFlag;
    }
    
    public void setUseResetDateFlag(Character useResetDateFlag) {
        this.useResetDateFlag = useResetDateFlag;
    }
    
    @Column(name="INT_DSCNT_PAY_SUB", length=1)
    public Character getIntDscntPaySub() {
        return this.intDscntPaySub;
    }
    
    public void setIntDscntPaySub(Character intDscntPaySub) {
        this.intDscntPaySub = intDscntPaySub;
    }
    
    @Column(name="CALC_INT_DSCNT", length=1)
    public Character getCalcIntDscnt() {
        return this.calcIntDscnt;
    }
    
    public void setCalcIntDscnt(Character calcIntDscnt) {
        this.calcIntDscnt = calcIntDscnt;
    }
    
    @Column(name="APPLY_UNCLEAN_IND", length=1)
    public Character getApplyUncleanInd() {
        return this.applyUncleanInd;
    }
    
    public void setApplyUncleanInd(Character applyUncleanInd) {
        this.applyUncleanInd = applyUncleanInd;
    }
    
    @Column(name="USER_DEFINED_1", length=30)
    public String getUserDefined1() {
        return this.userDefined1;
    }
    
    public void setUserDefined1(String userDefined1) {
        this.userDefined1 = userDefined1;
    }
    
    @Column(name="USER_DEFINED_2", length=30)
    public String getUserDefined2() {
        return this.userDefined2;
    }
    
    public void setUserDefined2(String userDefined2) {
        this.userDefined2 = userDefined2;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_1", length=7)
    public Date getUserDate1() {
        return this.userDate1;
    }
    
    public void setUserDate1(Date userDate1) {
        this.userDate1 = userDate1;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_2", length=7)
    public Date getUserDate2() {
        return this.userDate2;
    }
    
    public void setUserDate2(Date userDate2) {
        this.userDate2 = userDate2;
    }
    
    @Column(name="CERTIFIED_FLG", length=1)
    public Character getCertifiedFlg() {
        return this.certifiedFlg;
    }
    
    public void setCertifiedFlg(Character certifiedFlg) {
        this.certifiedFlg = certifiedFlg;
    }
    
    @Column(name="AGE_FROM", precision=3, scale=0)
    public Short getAgeFrom() {
        return this.ageFrom;
    }
    
    public void setAgeFrom(Short ageFrom) {
        this.ageFrom = ageFrom;
    }
    
    @Column(name="AGE_THROUGH", precision=3, scale=0)
    public Short getAgeThrough() {
        return this.ageThrough;
    }
    
    public void setAgeThrough(Short ageThrough) {
        this.ageThrough = ageThrough;
    }
    
    @Column(name="SITE_FLG", length=1)
    public Character getSiteFlg() {
        return this.siteFlg;
    }
    
    public void setSiteFlg(Character siteFlg) {
        this.siteFlg = siteFlg;
    }
    
    @Column(name="WAIVE_MATCH_ORDER", length=2)
    public String getWaiveMatchOrder() {
        return this.waiveMatchOrder;
    }
    
    public void setWaiveMatchOrder(String waiveMatchOrder) {
        this.waiveMatchOrder = waiveMatchOrder;
    }
    
    @Column(name="PEN_APPLY_UNCLEAN_IND", length=1)
    public Character getPenApplyUncleanInd() {
        return this.penApplyUncleanInd;
    }
    
    public void setPenApplyUncleanInd(Character penApplyUncleanInd) {
        this.penApplyUncleanInd = penApplyUncleanInd;
    }
    
    @Column(name="MC_INDICATOR", length=1)
    public Character getMcIndicator() {
        return this.mcIndicator;
    }
    
    public void setMcIndicator(Character mcIndicator) {
        this.mcIndicator = mcIndicator;
    }
    
    @Column(name="DATE_OF_DEATH_RULE", length=1)
    public Character getDateOfDeathRule() {
        return this.dateOfDeathRule;
    }
    
    public void setDateOfDeathRule(Character dateOfDeathRule) {
        this.dateOfDeathRule = dateOfDeathRule;
    }
    
    @Column(name="NEWBORN_PROCESSING", length=1)
    public String getNewbornProcessing() {
        return this.newbornProcessing;
    }
    
    public void setNewbornProcessing(String newbornProcessing) {
        this.newbornProcessing = newbornProcessing;
    }
    
    @Column(name="NEWBORN_AGE_DAYS", precision=22, scale=0)
    public BigDecimal getNewbornAgeDays() {
        return this.newbornAgeDays;
    }
    
    public void setNewbornAgeDays(BigDecimal newbornAgeDays) {
        this.newbornAgeDays = newbornAgeDays;
    }
    
    @Column(name="NEWBORN_PROC_MTHD", length=1)
    public String getNewbornProcMthd() {
        return this.newbornProcMthd;
    }
    
    public void setNewbornProcMthd(String newbornProcMthd) {
        this.newbornProcMthd = newbornProcMthd;
    }
    
    @Column(name="INTR_DETR_PROCESS", nullable=false, length=1)
    public String getIntrDetrProcess() {
        return this.intrDetrProcess;
    }
    
    public void setIntrDetrProcess(String intrDetrProcess) {
        this.intrDetrProcess = intrDetrProcess;
    }
    
    @Column(name="DISC_DETR_PROCESS", nullable=false, length=1)
    public String getDiscDetrProcess() {
        return this.discDetrProcess;
    }
    
    public void setDiscDetrProcess(String discDetrProcess) {
        this.discDetrProcess = discDetrProcess;
    }
    
    @Column(name="AUTO_PAYEE_DETERM", length=1)
    public String getAutoPayeeDeterm() {
        return this.autoPayeeDeterm;
    }
    
    public void setAutoPayeeDeterm(String autoPayeeDeterm) {
        this.autoPayeeDeterm = autoPayeeDeterm;
    }
    
    @Column(name="APPLY_GRACE_DAYS", length=1)
    public String getApplyGraceDays() {
        return this.applyGraceDays;
    }
    
    public void setApplyGraceDays(String applyGraceDays) {
        this.applyGraceDays = applyGraceDays;
    }
    
    @Column(name="DEFAULT_GRACE_DAYS", precision=22, scale=0)
    public BigDecimal getDefaultGraceDays() {
        return this.defaultGraceDays;
    }
    
    public void setDefaultGraceDays(BigDecimal defaultGraceDays) {
        this.defaultGraceDays = defaultGraceDays;
    }
    
    @Column(name="DUAL_BS_AWAIVE_REQ", length=1)
    public String getDualBsAwaiveReq() {
        return this.dualBsAwaiveReq;
    }
    
    public void setDualBsAwaiveReq(String dualBsAwaiveReq) {
        this.dualBsAwaiveReq = dualBsAwaiveReq;
    }
    
    @Column(name="DUAL_BS_AUTH_LEVEL", length=1)
    public String getDualBsAuthLevel() {
        return this.dualBsAuthLevel;
    }
    
    public void setDualBsAuthLevel(String dualBsAuthLevel) {
        this.dualBsAuthLevel = dualBsAuthLevel;
    }
    
    @Column(name="DUAL_BS_AWAIVE_MORDER", length=2)
    public String getDualBsAwaiveMorder() {
        return this.dualBsAwaiveMorder;
    }
    
    public void setDualBsAwaiveMorder(String dualBsAwaiveMorder) {
        this.dualBsAwaiveMorder = dualBsAwaiveMorder;
    }
    
    @Column(name="SEQ_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getSeqId() {
        return this.seqId;
    }
    
    public void setSeqId(BigDecimal seqId) {
        this.seqId = seqId;
    }
    
    @Column(name="COB_BANK", length=1)
    public String getCobBank() {
        return this.cobBank;
    }
    
    public void setCobBank(String cobBank) {
        this.cobBank = cobBank;
    }
    
    @Column(name="AUTH_DETAIL", length=1)
    public String getAuthDetail() {
        return this.authDetail;
    }
    
    public void setAuthDetail(String authDetail) {
        this.authDetail = authDetail;
    }
    
    @Column(name="INTERIM_BILL_OUTSIDE_ELIG_ACT", length=1)
    public String getInterimBillOutsideEligAct() {
        return this.interimBillOutsideEligAct;
    }
    
    public void setInterimBillOutsideEligAct(String interimBillOutsideEligAct) {
        this.interimBillOutsideEligAct = interimBillOutsideEligAct;
    }
    
    @Column(name="INTERIM_BILL_OUTSIDE_ELIG_RSN", length=5)
    public String getInterimBillOutsideEligRsn() {
        return this.interimBillOutsideEligRsn;
    }
    
    public void setInterimBillOutsideEligRsn(String interimBillOutsideEligRsn) {
        this.interimBillOutsideEligRsn = interimBillOutsideEligRsn;
    }
    
    @Column(name="BENEFIT_CARRYOVER_IND", length=1)
    public String getBenefitCarryoverInd() {
        return this.benefitCarryoverInd;
    }
    
    public void setBenefitCarryoverInd(String benefitCarryoverInd) {
        this.benefitCarryoverInd = benefitCarryoverInd;
    }
    
    @Column(name="RESET_AUTH_PAR_CODE", length=1)
    public String getResetAuthParCode() {
        return this.resetAuthParCode;
    }
    
    public void setResetAuthParCode(String resetAuthParCode) {
        this.resetAuthParCode = resetAuthParCode;
    }
    
    @Column(name="RESET_AUTH_RSN_CODE", length=5)
    public String getResetAuthRsnCode() {
        return this.resetAuthRsnCode;
    }
    
    public void setResetAuthRsnCode(String resetAuthRsnCode) {
        this.resetAuthRsnCode = resetAuthRsnCode;
    }
    
    @Column(name="RESET_CLAIM_PAR_CODE", length=1)
    public String getResetClaimParCode() {
        return this.resetClaimParCode;
    }
    
    public void setResetClaimParCode(String resetClaimParCode) {
        this.resetClaimParCode = resetClaimParCode;
    }
    
    @Column(name="RESET_CLAIM_RSN_CODE", length=5)
    public String getResetClaimRsnCode() {
        return this.resetClaimRsnCode;
    }
    
    public void setResetClaimRsnCode(String resetClaimRsnCode) {
        this.resetClaimRsnCode = resetClaimRsnCode;
    }
    
    @Column(name="MEMBER_ADDRESS_UPDATES", length=1)
    public String getMemberAddressUpdates() {
        return this.memberAddressUpdates;
    }
    
    public void setMemberAddressUpdates(String memberAddressUpdates) {
        this.memberAddressUpdates = memberAddressUpdates;
    }
    
    @Column(name="DEFAULT_ADDR_EFF_DATE", length=2)
    public String getDefaultAddrEffDate() {
        return this.defaultAddrEffDate;
    }
    
    public void setDefaultAddrEffDate(String defaultAddrEffDate) {
        this.defaultAddrEffDate = defaultAddrEffDate;
    }
    
    @Column(name="TFWAV_RULE_ID", length=3)
    public String getTfwavRuleId() {
        return this.tfwavRuleId;
    }
    
    public void setTfwavRuleId(String tfwavRuleId) {
        this.tfwavRuleId = tfwavRuleId;
    }
    
    @Column(name="REFERRAL", length=1)
    public String getReferral() {
        return this.referral;
    }
    
    public void setReferral(String referral) {
        this.referral = referral;
    }
    
    @Column(name="REFPROV", length=1)
    public String getRefprov() {
        return this.refprov;
    }
    
    public void setRefprov(String refprov) {
        this.refprov = refprov;
    }
    
    @Column(name="ATTPROV", length=1)
    public String getAttprov() {
        return this.attprov;
    }
    
    public void setAttprov(String attprov) {
        this.attprov = attprov;
    }
    
    @Column(name="EVALUATE_MBR_SVC_AREA", length=1)
    public String getEvaluateMbrSvcArea() {
        return this.evaluateMbrSvcArea;
    }
    
    public void setEvaluateMbrSvcArea(String evaluateMbrSvcArea) {
        this.evaluateMbrSvcArea = evaluateMbrSvcArea;
    }
    
    @Column(name="ACTION", length=1)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    
    @Column(name="REASON_CODE", length=5)
    public String getReasonCode() {
        return this.reasonCode;
    }
    
    public void setReasonCode(String reasonCode) {
        this.reasonCode = reasonCode;
    }
    
    @Column(name="RX_BIN", length=6)
    public String getRxBin() {
        return this.rxBin;
    }
    
    public void setRxBin(String rxBin) {
        this.rxBin = rxBin;
    }
    
    @Column(name="RX_PCN", length=10)
    public String getRxPcn() {
        return this.rxPcn;
    }
    
    public void setRxPcn(String rxPcn) {
        this.rxPcn = rxPcn;
    }
    
    @Column(name="RX_GROUP", length=15)
    public String getRxGroup() {
        return this.rxGroup;
    }
    
    public void setRxGroup(String rxGroup) {
        this.rxGroup = rxGroup;
    }
    
    @Column(name="PBP_NUMBER", length=3)
    public String getPbpNumber() {
        return this.pbpNumber;
    }
    
    public void setPbpNumber(String pbpNumber) {
        this.pbpNumber = pbpNumber;
    }
    
    @Column(name="PRICER_ALLOWED_REASON", length=5)
    public String getPricerAllowedReason() {
        return this.pricerAllowedReason;
    }
    
    public void setPricerAllowedReason(String pricerAllowedReason) {
        this.pricerAllowedReason = pricerAllowedReason;
    }
    
    @Column(name="SURGERY_RULE", length=5)
    public String getSurgeryRule() {
        return this.surgeryRule;
    }
    
    public void setSurgeryRule(String surgeryRule) {
        this.surgeryRule = surgeryRule;
    }
    
    @Column(name="SURGERY_RULE_INST", length=5)
    public String getSurgeryRuleInst() {
        return this.surgeryRuleInst;
    }
    
    public void setSurgeryRuleInst(String surgeryRuleInst) {
        this.surgeryRuleInst = surgeryRuleInst;
    }
    
    @Column(name="SURGERY_HIERARCHY_INST", length=5)
    public String getSurgeryHierarchyInst() {
        return this.surgeryHierarchyInst;
    }
    
    public void setSurgeryHierarchyInst(String surgeryHierarchyInst) {
        this.surgeryHierarchyInst = surgeryHierarchyInst;
    }
    
    @Column(name="OC_OFFSET_REASON", length=5)
    public String getOcOffsetReason() {
        return this.ocOffsetReason;
    }
    
    public void setOcOffsetReason(String ocOffsetReason) {
        this.ocOffsetReason = ocOffsetReason;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lineOfBusinessMaster")
    public Set<PremiumMaster> getPremiumMasters() {
        return this.premiumMasters;
    }
    
    public void setPremiumMasters(Set<PremiumMaster> premiumMasters) {
        this.premiumMasters = premiumMasters;
    }




}


