package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NavgrpKwId generated by hbm2java
 */
@Embeddable
public class NavgrpKwId  implements java.io.Serializable {


     private String navgrpId;
     private String winId;
     private byte languageId;

    public NavgrpKwId() {
    }

    public NavgrpKwId(String navgrpId, String winId, byte languageId) {
       this.navgrpId = navgrpId;
       this.winId = winId;
       this.languageId = languageId;
    }
   

    @Column(name="NAVGRP_ID", nullable=false, length=8)
    public String getNavgrpId() {
        return this.navgrpId;
    }
    
    public void setNavgrpId(String navgrpId) {
        this.navgrpId = navgrpId;
    }

    @Column(name="WIN_ID", nullable=false, length=8)
    public String getWinId() {
        return this.winId;
    }
    
    public void setWinId(String winId) {
        this.winId = winId;
    }

    @Column(name="LANGUAGE_ID", nullable=false, precision=2, scale=0)
    public byte getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(byte languageId) {
        this.languageId = languageId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NavgrpKwId) ) return false;
		 NavgrpKwId castOther = ( NavgrpKwId ) other; 
         
		 return ( (this.getNavgrpId()==castOther.getNavgrpId()) || ( this.getNavgrpId()!=null && castOther.getNavgrpId()!=null && this.getNavgrpId().equals(castOther.getNavgrpId()) ) )
 && ( (this.getWinId()==castOther.getWinId()) || ( this.getWinId()!=null && castOther.getWinId()!=null && this.getWinId().equals(castOther.getWinId()) ) )
 && (this.getLanguageId()==castOther.getLanguageId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNavgrpId() == null ? 0 : this.getNavgrpId().hashCode() );
         result = 37 * result + ( getWinId() == null ? 0 : this.getWinId().hashCode() );
         result = 37 * result + this.getLanguageId();
         return result;
   }   


}


