package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.util.*;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NavgrpKw generated by hbm2java
 */
@Entity
@Table(name="NAVGRP_KW"
    ,schema="DORIS"
)
public class NavgrpKw extends Base.BaseEntity implements java.io.Serializable {


     private NavgrpKwId id;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private Character auditTrail;

    public NavgrpKw() {
    }

	
    public NavgrpKw(NavgrpKwId id) {
        this.id = id;
    }
    public NavgrpKw(NavgrpKwId id, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, Character auditTrail) {
       this.id = id;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.auditTrail = auditTrail;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="navgrpId", column=@Column(name="NAVGRP_ID", nullable=false, length=8) ), 
        @AttributeOverride(name="winId", column=@Column(name="WIN_ID", nullable=false, length=8) ), 
        @AttributeOverride(name="languageId", column=@Column(name="LANGUAGE_ID", nullable=false, precision=2, scale=0) ) } )
    public NavgrpKwId getId() {
        return this.id;
    }
    
    public void setId(NavgrpKwId id) {
        this.id = id;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="AUDIT_TRAIL", length=1)
    public Character getAuditTrail() {
        return this.auditTrail;
    }
    
    public void setAuditTrail(Character auditTrail) {
        this.auditTrail = auditTrail;
    }




}


