package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.util.*;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlanMaster generated by hbm2java
 */
@Entity
@Table(name="PLAN_MASTER"
    ,schema="DORIS"
)
public class PlanMaster extends Base.BaseEntity implements java.io.Serializable {


     private String planCode;
     private String description;
     private String autoAuditPlanId;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private String productType;
     private String shortDescription;
     private String contractTypeRequired;
     private String applicableForDependent;
     private String userDefined1;
     private String userDefined2;
     private String userDefined3;
     private String userDefined4;
     private Date userDate1;
     private Date userDate2;
     private Date userDate3;
     private Date userDate4;
     private String planType;
     private String userDefined5;
     private String userDefined6;
     private Date userDate5;
     private Date userDate6;
     private String benefitCarryoverInd;
     private String mbrServiceArea;
     private String contractTypeDeterminant;

    public PlanMaster() {
    }

	
    public PlanMaster(String planCode, String description, String shortDescription) {
        this.planCode = planCode;
        this.description = description;
        this.shortDescription = shortDescription;
    }
    public PlanMaster(String planCode, String description, String autoAuditPlanId, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, String productType, String shortDescription, String contractTypeRequired, String applicableForDependent, String userDefined1, String userDefined2, String userDefined3, String userDefined4, Date userDate1, Date userDate2, Date userDate3, Date userDate4, String planType, String userDefined5, String userDefined6, Date userDate5, Date userDate6, String benefitCarryoverInd, String mbrServiceArea, String contractTypeDeterminant) {
       this.planCode = planCode;
       this.description = description;
       this.autoAuditPlanId = autoAuditPlanId;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.productType = productType;
       this.shortDescription = shortDescription;
       this.contractTypeRequired = contractTypeRequired;
       this.applicableForDependent = applicableForDependent;
       this.userDefined1 = userDefined1;
       this.userDefined2 = userDefined2;
       this.userDefined3 = userDefined3;
       this.userDefined4 = userDefined4;
       this.userDate1 = userDate1;
       this.userDate2 = userDate2;
       this.userDate3 = userDate3;
       this.userDate4 = userDate4;
       this.planType = planType;
       this.userDefined5 = userDefined5;
       this.userDefined6 = userDefined6;
       this.userDate5 = userDate5;
       this.userDate6 = userDate6;
       this.benefitCarryoverInd = benefitCarryoverInd;
       this.mbrServiceArea = mbrServiceArea;
       this.contractTypeDeterminant = contractTypeDeterminant;
    }
   
     @Id 
    
    @Column(name="PLAN_CODE", nullable=false, length=10)
    public String getPlanCode() {
        return this.planCode;
    }
    
    public void setPlanCode(String planCode) {
        this.planCode = planCode;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=240)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="AUTO_AUDIT_PLAN_ID", length=4)
    public String getAutoAuditPlanId() {
        return this.autoAuditPlanId;
    }
    
    public void setAutoAuditPlanId(String autoAuditPlanId) {
        this.autoAuditPlanId = autoAuditPlanId;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="PRODUCT_TYPE", length=10)
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    
    @Column(name="SHORT_DESCRIPTION", nullable=false, length=20)
    public String getShortDescription() {
        return this.shortDescription;
    }
    
    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }
    
    @Column(name="CONTRACT_TYPE_REQUIRED", length=1)
    public String getContractTypeRequired() {
        return this.contractTypeRequired;
    }
    
    public void setContractTypeRequired(String contractTypeRequired) {
        this.contractTypeRequired = contractTypeRequired;
    }
    
    @Column(name="APPLICABLE_FOR_DEPENDENT", length=1)
    public String getApplicableForDependent() {
        return this.applicableForDependent;
    }
    
    public void setApplicableForDependent(String applicableForDependent) {
        this.applicableForDependent = applicableForDependent;
    }
    
    @Column(name="USER_DEFINED_1", length=30)
    public String getUserDefined1() {
        return this.userDefined1;
    }
    
    public void setUserDefined1(String userDefined1) {
        this.userDefined1 = userDefined1;
    }
    
    @Column(name="USER_DEFINED_2", length=30)
    public String getUserDefined2() {
        return this.userDefined2;
    }
    
    public void setUserDefined2(String userDefined2) {
        this.userDefined2 = userDefined2;
    }
    
    @Column(name="USER_DEFINED_3", length=30)
    public String getUserDefined3() {
        return this.userDefined3;
    }
    
    public void setUserDefined3(String userDefined3) {
        this.userDefined3 = userDefined3;
    }
    
    @Column(name="USER_DEFINED_4", length=30)
    public String getUserDefined4() {
        return this.userDefined4;
    }
    
    public void setUserDefined4(String userDefined4) {
        this.userDefined4 = userDefined4;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_1", length=7)
    public Date getUserDate1() {
        return this.userDate1;
    }
    
    public void setUserDate1(Date userDate1) {
        this.userDate1 = userDate1;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_2", length=7)
    public Date getUserDate2() {
        return this.userDate2;
    }
    
    public void setUserDate2(Date userDate2) {
        this.userDate2 = userDate2;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_3", length=7)
    public Date getUserDate3() {
        return this.userDate3;
    }
    
    public void setUserDate3(Date userDate3) {
        this.userDate3 = userDate3;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_4", length=7)
    public Date getUserDate4() {
        return this.userDate4;
    }
    
    public void setUserDate4(Date userDate4) {
        this.userDate4 = userDate4;
    }
    
    @Column(name="PLAN_TYPE", length=1)
    public String getPlanType() {
        return this.planType;
    }
    
    public void setPlanType(String planType) {
        this.planType = planType;
    }
    
    @Column(name="USER_DEFINED_5", length=30)
    public String getUserDefined5() {
        return this.userDefined5;
    }
    
    public void setUserDefined5(String userDefined5) {
        this.userDefined5 = userDefined5;
    }
    
    @Column(name="USER_DEFINED_6", length=30)
    public String getUserDefined6() {
        return this.userDefined6;
    }
    
    public void setUserDefined6(String userDefined6) {
        this.userDefined6 = userDefined6;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_5", length=7)
    public Date getUserDate5() {
        return this.userDate5;
    }
    
    public void setUserDate5(Date userDate5) {
        this.userDate5 = userDate5;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_6", length=7)
    public Date getUserDate6() {
        return this.userDate6;
    }
    
    public void setUserDate6(Date userDate6) {
        this.userDate6 = userDate6;
    }
    
    @Column(name="BENEFIT_CARRYOVER_IND", length=1)
    public String getBenefitCarryoverInd() {
        return this.benefitCarryoverInd;
    }
    
    public void setBenefitCarryoverInd(String benefitCarryoverInd) {
        this.benefitCarryoverInd = benefitCarryoverInd;
    }
    
    @Column(name="MBR_SERVICE_AREA", length=15)
    public String getMbrServiceArea() {
        return this.mbrServiceArea;
    }
    
    public void setMbrServiceArea(String mbrServiceArea) {
        this.mbrServiceArea = mbrServiceArea;
    }
    
    @Column(name="CONTRACT_TYPE_DETERMINANT", length=1)
    public String getContractTypeDeterminant() {
        return this.contractTypeDeterminant;
    }
    
    public void setContractTypeDeterminant(String contractTypeDeterminant) {
        this.contractTypeDeterminant = contractTypeDeterminant;
    }




}


