package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.*;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PremiumMaster generated by hbm2java
 */
@Entity
@Table(name="PREMIUM_MASTER"
    ,schema="DORIS"
)
public class PremiumMaster extends Base.BaseEntity implements java.io.Serializable {


     private PremiumMasterId id;
     private BenefitPackageMaster benefitPackageMaster;
     private LineOfBusinessMaster lineOfBusinessMaster;
     private ReasonCodeMaster reasonCodeMaster;
     private GroupMaster group;
     private char recordType;
     private String planRiderCode;
     private Date effectiveDate;
     private Date endDate;
     private String companyCode;
     private String glRefCode;
     private String tieringMethod;
     private BigDecimal rate1;
     private BigDecimal rate2;
     private BigDecimal rate3;
     private BigDecimal rate4;
     private BigDecimal rate5;
     private String priceRule1;
     private String priceRule2;
     private String priceSchedule1;
     private String priceSchedule2;
     private BigDecimal pctOfBilled;
     private Character priceOrAdjudicate;
     private BigDecimal pctAllowed;
     private String matrixDef;
     private BigDecimal pctOfMatrix;
     private BigDecimal adminFee;
     private String adFeeCompCode;
     private String adFeeGlCode;
     private String specPgmProcessCd;
     private String geographicRegion;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private Character adFeeLevelCode;
     private Character exclusionType;
     private Short exclusionPeriod;
     private Character applyPcp;
     private String reasonCode;
     private String cobCalcMethod;
     private String commissionMatrixDef;
     private String commissionCompanyCode;
     private String commissionGlRefCode;
     private Character rateCategory;
     private String instCobCalcMethod;
     private char depDetermRuleCode;
     private char cobPolicyFlag;
     private char cobExcludeCapClaimCode;
     private String claimFilingIndicator;
     private Date rateModifyDate;
     private String dentalCobCalcMethod;
     private Character excludeCapClmDtl;
     private Byte depAgeLimit;
     private Byte stuAgeLimit;
     private String depAgeLimitAction;
     private String depAgeLimitReason;
     private String stuAgeLimitAction;
     private String stuAgeLimitReason;
     private String stuNoVerificationAction;
     private String stuNoVerificationReason;
     private String recordStatus;
     private String userDefined1;
     private String userDefined2;
     private String userDefined3;
     private String userDefined4;
     private String userDefined5;
     private String userDefined6;
     private String userDefined7;
     private Date userDate1;
     private Date userDate2;
     private Date userDate3;
     private String userDefined8;
     private String userDefined9;
     private String userDefined10;
     private Date userDate4;
     private Date userDate5;
     private Date userDate6;
     private Date userDate7;
     private Date userDate8;
     private Date userDate9;
     private Date userDate10;
     private String comments;
     private String depConvOption;
     private String depConvAction;
     private String stuConvOption;
     private String stuConvAction;
     private Date renewalDate;
     private Date convYearStartDate;
     private String planType;
     private String priceIndicator;
     private String parSearch;
     private String dualPsCalc;
     private String mbrsSsnReq;
     private String benefitCarryoverInd;
     private String compareLogicInd;
     private String rxBin;
     private String rxPcn;
     private String rxGroup;
     private String pbpNumber;

    public PremiumMaster() {
    }

	
    public PremiumMaster(PremiumMasterId id, BenefitPackageMaster benefitPackageMaster, LineOfBusinessMaster lineOfBusinessMaster, GroupMaster group, char recordType, String planRiderCode, Date effectiveDate, String cobCalcMethod, String instCobCalcMethod, char depDetermRuleCode, char cobPolicyFlag, char cobExcludeCapClaimCode, String claimFilingIndicator) {
        this.id = id;
        this.benefitPackageMaster = benefitPackageMaster;
        this.lineOfBusinessMaster = lineOfBusinessMaster;
        this.group = group;
        this.recordType = recordType;
        this.planRiderCode = planRiderCode;
        this.effectiveDate = effectiveDate;
        this.cobCalcMethod = cobCalcMethod;
        this.instCobCalcMethod = instCobCalcMethod;
        this.depDetermRuleCode = depDetermRuleCode;
        this.cobPolicyFlag = cobPolicyFlag;
        this.cobExcludeCapClaimCode = cobExcludeCapClaimCode;
        this.claimFilingIndicator = claimFilingIndicator;
    }
    public PremiumMaster(PremiumMasterId id, BenefitPackageMaster benefitPackageMaster, LineOfBusinessMaster lineOfBusinessMaster, ReasonCodeMaster reasonCodeMaster, GroupMaster group, char recordType, String planRiderCode, Date effectiveDate, Date endDate, String companyCode, String glRefCode, String tieringMethod, BigDecimal rate1, BigDecimal rate2, BigDecimal rate3, BigDecimal rate4, BigDecimal rate5, String priceRule1, String priceRule2, String priceSchedule1, String priceSchedule2, BigDecimal pctOfBilled, Character priceOrAdjudicate, BigDecimal pctAllowed, String matrixDef, BigDecimal pctOfMatrix, BigDecimal adminFee, String adFeeCompCode, String adFeeGlCode, String specPgmProcessCd, String geographicRegion, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, Character adFeeLevelCode, Character exclusionType, Short exclusionPeriod, Character applyPcp, String reasonCode, String cobCalcMethod, String commissionMatrixDef, String commissionCompanyCode, String commissionGlRefCode, Character rateCategory, String instCobCalcMethod, char depDetermRuleCode, char cobPolicyFlag, char cobExcludeCapClaimCode, String claimFilingIndicator, Date rateModifyDate, String dentalCobCalcMethod, Character excludeCapClmDtl, Byte depAgeLimit, Byte stuAgeLimit, String depAgeLimitAction, String depAgeLimitReason, String stuAgeLimitAction, String stuAgeLimitReason, String stuNoVerificationAction, String stuNoVerificationReason, String recordStatus, String userDefined1, String userDefined2, String userDefined3, String userDefined4, String userDefined5, String userDefined6, String userDefined7, Date userDate1, Date userDate2, Date userDate3, String userDefined8, String userDefined9, String userDefined10, Date userDate4, Date userDate5, Date userDate6, Date userDate7, Date userDate8, Date userDate9, Date userDate10, String comments, String depConvOption, String depConvAction, String stuConvOption, String stuConvAction, Date renewalDate, Date convYearStartDate, String planType, String priceIndicator, String parSearch, String dualPsCalc, String mbrsSsnReq, String benefitCarryoverInd, String compareLogicInd, String rxBin, String rxPcn, String rxGroup, String pbpNumber) {
       this.id = id;
       this.benefitPackageMaster = benefitPackageMaster;
       this.lineOfBusinessMaster = lineOfBusinessMaster;
       this.reasonCodeMaster = reasonCodeMaster;
       this.group = group;
       this.recordType = recordType;
       this.planRiderCode = planRiderCode;
       this.effectiveDate = effectiveDate;
       this.endDate = endDate;
       this.companyCode = companyCode;
       this.glRefCode = glRefCode;
       this.tieringMethod = tieringMethod;
       this.rate1 = rate1;
       this.rate2 = rate2;
       this.rate3 = rate3;
       this.rate4 = rate4;
       this.rate5 = rate5;
       this.priceRule1 = priceRule1;
       this.priceRule2 = priceRule2;
       this.priceSchedule1 = priceSchedule1;
       this.priceSchedule2 = priceSchedule2;
       this.pctOfBilled = pctOfBilled;
       this.priceOrAdjudicate = priceOrAdjudicate;
       this.pctAllowed = pctAllowed;
       this.matrixDef = matrixDef;
       this.pctOfMatrix = pctOfMatrix;
       this.adminFee = adminFee;
       this.adFeeCompCode = adFeeCompCode;
       this.adFeeGlCode = adFeeGlCode;
       this.specPgmProcessCd = specPgmProcessCd;
       this.geographicRegion = geographicRegion;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.adFeeLevelCode = adFeeLevelCode;
       this.exclusionType = exclusionType;
       this.exclusionPeriod = exclusionPeriod;
       this.applyPcp = applyPcp;
       this.reasonCode = reasonCode;
       this.cobCalcMethod = cobCalcMethod;
       this.commissionMatrixDef = commissionMatrixDef;
       this.commissionCompanyCode = commissionCompanyCode;
       this.commissionGlRefCode = commissionGlRefCode;
       this.rateCategory = rateCategory;
       this.instCobCalcMethod = instCobCalcMethod;
       this.depDetermRuleCode = depDetermRuleCode;
       this.cobPolicyFlag = cobPolicyFlag;
       this.cobExcludeCapClaimCode = cobExcludeCapClaimCode;
       this.claimFilingIndicator = claimFilingIndicator;
       this.rateModifyDate = rateModifyDate;
       this.dentalCobCalcMethod = dentalCobCalcMethod;
       this.excludeCapClmDtl = excludeCapClmDtl;
       this.depAgeLimit = depAgeLimit;
       this.stuAgeLimit = stuAgeLimit;
       this.depAgeLimitAction = depAgeLimitAction;
       this.depAgeLimitReason = depAgeLimitReason;
       this.stuAgeLimitAction = stuAgeLimitAction;
       this.stuAgeLimitReason = stuAgeLimitReason;
       this.stuNoVerificationAction = stuNoVerificationAction;
       this.stuNoVerificationReason = stuNoVerificationReason;
       this.recordStatus = recordStatus;
       this.userDefined1 = userDefined1;
       this.userDefined2 = userDefined2;
       this.userDefined3 = userDefined3;
       this.userDefined4 = userDefined4;
       this.userDefined5 = userDefined5;
       this.userDefined6 = userDefined6;
       this.userDefined7 = userDefined7;
       this.userDate1 = userDate1;
       this.userDate2 = userDate2;
       this.userDate3 = userDate3;
       this.userDefined8 = userDefined8;
       this.userDefined9 = userDefined9;
       this.userDefined10 = userDefined10;
       this.userDate4 = userDate4;
       this.userDate5 = userDate5;
       this.userDate6 = userDate6;
       this.userDate7 = userDate7;
       this.userDate8 = userDate8;
       this.userDate9 = userDate9;
       this.userDate10 = userDate10;
       this.comments = comments;
       this.depConvOption = depConvOption;
       this.depConvAction = depConvAction;
       this.stuConvOption = stuConvOption;
       this.stuConvAction = stuConvAction;
       this.renewalDate = renewalDate;
       this.convYearStartDate = convYearStartDate;
       this.planType = planType;
       this.priceIndicator = priceIndicator;
       this.parSearch = parSearch;
       this.dualPsCalc = dualPsCalc;
       this.mbrsSsnReq = mbrsSsnReq;
       this.benefitCarryoverInd = benefitCarryoverInd;
       this.compareLogicInd = compareLogicInd;
       this.rxBin = rxBin;
       this.rxPcn = rxPcn;
       this.rxGroup = rxGroup;
       this.pbpNumber = pbpNumber;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="seqGroupId", column=@Column(name="SEQ_GROUP_ID", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="seqPremId", column=@Column(name="SEQ_PREM_ID", nullable=false, precision=9, scale=0) ) } )
    public PremiumMasterId getId() {
        return this.id;
    }
    
    public void setId(PremiumMasterId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BENEFIT_PACKAGE_ID", nullable=false)
    public BenefitPackageMaster getBenefitPackageMaster() {
        return this.benefitPackageMaster;
    }
    
    public void setBenefitPackageMaster(BenefitPackageMaster benefitPackageMaster) {
        this.benefitPackageMaster = benefitPackageMaster;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LINE_OF_BUSINESS", nullable=false)
    public LineOfBusinessMaster getLineOfBusinessMaster() {
        return this.lineOfBusinessMaster;
    }
    
    public void setLineOfBusinessMaster(LineOfBusinessMaster lineOfBusinessMaster) {
        this.lineOfBusinessMaster = lineOfBusinessMaster;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TERM_REASON")
    public ReasonCodeMaster getReasonCodeMaster() {
        return this.reasonCodeMaster;
    }
    
    public void setReasonCodeMaster(ReasonCodeMaster reasonCodeMaster) {
        this.reasonCodeMaster = reasonCodeMaster;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SEQ_GROUP_ID", nullable=false, insertable=false, updatable=false)
    public GroupMaster getGroup() {
        return this.group;
    }
    
    public void setGroup(GroupMaster group) {
        this.group = group;
    }
    
    @Column(name="RECORD_TYPE", nullable=false, length=1)
    public char getRecordType() {
        return this.recordType;
    }
    
    public void setRecordType(char recordType) {
        this.recordType = recordType;
    }
    
    @Column(name="PLAN_RIDER_CODE", nullable=false, length=10)
    public String getPlanRiderCode() {
        return this.planRiderCode;
    }
    
    public void setPlanRiderCode(String planRiderCode) {
        this.planRiderCode = planRiderCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", nullable=false, length=7)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=7)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
    @Column(name="COMPANY_CODE", length=5)
    public String getCompanyCode() {
        return this.companyCode;
    }
    
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }
    
    @Column(name="GL_REF_CODE", length=3)
    public String getGlRefCode() {
        return this.glRefCode;
    }
    
    public void setGlRefCode(String glRefCode) {
        this.glRefCode = glRefCode;
    }
    
    @Column(name="TIERING_METHOD", length=2)
    public String getTieringMethod() {
        return this.tieringMethod;
    }
    
    public void setTieringMethod(String tieringMethod) {
        this.tieringMethod = tieringMethod;
    }
    
    @Column(name="RATE_1", precision=20, scale=4)
    public BigDecimal getRate1() {
        return this.rate1;
    }
    
    public void setRate1(BigDecimal rate1) {
        this.rate1 = rate1;
    }
    
    @Column(name="RATE_2", precision=20, scale=4)
    public BigDecimal getRate2() {
        return this.rate2;
    }
    
    public void setRate2(BigDecimal rate2) {
        this.rate2 = rate2;
    }
    
    @Column(name="RATE_3", precision=20, scale=4)
    public BigDecimal getRate3() {
        return this.rate3;
    }
    
    public void setRate3(BigDecimal rate3) {
        this.rate3 = rate3;
    }
    
    @Column(name="RATE_4", precision=20, scale=4)
    public BigDecimal getRate4() {
        return this.rate4;
    }
    
    public void setRate4(BigDecimal rate4) {
        this.rate4 = rate4;
    }
    
    @Column(name="RATE_5", precision=20, scale=4)
    public BigDecimal getRate5() {
        return this.rate5;
    }
    
    public void setRate5(BigDecimal rate5) {
        this.rate5 = rate5;
    }
    
    @Column(name="PRICE_RULE_1", length=5)
    public String getPriceRule1() {
        return this.priceRule1;
    }
    
    public void setPriceRule1(String priceRule1) {
        this.priceRule1 = priceRule1;
    }
    
    @Column(name="PRICE_RULE_2", length=5)
    public String getPriceRule2() {
        return this.priceRule2;
    }
    
    public void setPriceRule2(String priceRule2) {
        this.priceRule2 = priceRule2;
    }
    
    @Column(name="PRICE_SCHEDULE_1", length=3)
    public String getPriceSchedule1() {
        return this.priceSchedule1;
    }
    
    public void setPriceSchedule1(String priceSchedule1) {
        this.priceSchedule1 = priceSchedule1;
    }
    
    @Column(name="PRICE_SCHEDULE_2", length=3)
    public String getPriceSchedule2() {
        return this.priceSchedule2;
    }
    
    public void setPriceSchedule2(String priceSchedule2) {
        this.priceSchedule2 = priceSchedule2;
    }
    
    @Column(name="PCT_OF_BILLED", precision=5, scale=4)
    public BigDecimal getPctOfBilled() {
        return this.pctOfBilled;
    }
    
    public void setPctOfBilled(BigDecimal pctOfBilled) {
        this.pctOfBilled = pctOfBilled;
    }
    
    @Column(name="PRICE_OR_ADJUDICATE", length=1)
    public Character getPriceOrAdjudicate() {
        return this.priceOrAdjudicate;
    }
    
    public void setPriceOrAdjudicate(Character priceOrAdjudicate) {
        this.priceOrAdjudicate = priceOrAdjudicate;
    }
    
    @Column(name="PCT_ALLOWED", precision=5, scale=4)
    public BigDecimal getPctAllowed() {
        return this.pctAllowed;
    }
    
    public void setPctAllowed(BigDecimal pctAllowed) {
        this.pctAllowed = pctAllowed;
    }
    
    @Column(name="MATRIX_DEF", length=15)
    public String getMatrixDef() {
        return this.matrixDef;
    }
    
    public void setMatrixDef(String matrixDef) {
        this.matrixDef = matrixDef;
    }
    
    @Column(name="PCT_OF_MATRIX", precision=5, scale=4)
    public BigDecimal getPctOfMatrix() {
        return this.pctOfMatrix;
    }
    
    public void setPctOfMatrix(BigDecimal pctOfMatrix) {
        this.pctOfMatrix = pctOfMatrix;
    }
    
    @Column(name="ADMIN_FEE", precision=18)
    public BigDecimal getAdminFee() {
        return this.adminFee;
    }
    
    public void setAdminFee(BigDecimal adminFee) {
        this.adminFee = adminFee;
    }
    
    @Column(name="AD_FEE_COMP_CODE", length=5)
    public String getAdFeeCompCode() {
        return this.adFeeCompCode;
    }
    
    public void setAdFeeCompCode(String adFeeCompCode) {
        this.adFeeCompCode = adFeeCompCode;
    }
    
    @Column(name="AD_FEE_GL_CODE", length=3)
    public String getAdFeeGlCode() {
        return this.adFeeGlCode;
    }
    
    public void setAdFeeGlCode(String adFeeGlCode) {
        this.adFeeGlCode = adFeeGlCode;
    }
    
    @Column(name="SPEC_PGM_PROCESS_CD", length=2)
    public String getSpecPgmProcessCd() {
        return this.specPgmProcessCd;
    }
    
    public void setSpecPgmProcessCd(String specPgmProcessCd) {
        this.specPgmProcessCd = specPgmProcessCd;
    }
    
    @Column(name="GEOGRAPHIC_REGION", length=3)
    public String getGeographicRegion() {
        return this.geographicRegion;
    }
    
    public void setGeographicRegion(String geographicRegion) {
        this.geographicRegion = geographicRegion;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="AD_FEE_LEVEL_CODE", length=1)
    public Character getAdFeeLevelCode() {
        return this.adFeeLevelCode;
    }
    
    public void setAdFeeLevelCode(Character adFeeLevelCode) {
        this.adFeeLevelCode = adFeeLevelCode;
    }
    
    @Column(name="EXCLUSION_TYPE", length=1)
    public Character getExclusionType() {
        return this.exclusionType;
    }
    
    public void setExclusionType(Character exclusionType) {
        this.exclusionType = exclusionType;
    }
    
    @Column(name="EXCLUSION_PERIOD", precision=3, scale=0)
    public Short getExclusionPeriod() {
        return this.exclusionPeriod;
    }
    
    public void setExclusionPeriod(Short exclusionPeriod) {
        this.exclusionPeriod = exclusionPeriod;
    }
    
    @Column(name="APPLY_PCP", length=1)
    public Character getApplyPcp() {
        return this.applyPcp;
    }
    
    public void setApplyPcp(Character applyPcp) {
        this.applyPcp = applyPcp;
    }
    
    @Column(name="REASON_CODE", length=5)
    public String getReasonCode() {
        return this.reasonCode;
    }
    
    public void setReasonCode(String reasonCode) {
        this.reasonCode = reasonCode;
    }
    
    @Column(name="COB_CALC_METHOD", nullable=false, length=2)
    public String getCobCalcMethod() {
        return this.cobCalcMethod;
    }
    
    public void setCobCalcMethod(String cobCalcMethod) {
        this.cobCalcMethod = cobCalcMethod;
    }
    
    @Column(name="COMMISSION_MATRIX_DEF", length=5)
    public String getCommissionMatrixDef() {
        return this.commissionMatrixDef;
    }
    
    public void setCommissionMatrixDef(String commissionMatrixDef) {
        this.commissionMatrixDef = commissionMatrixDef;
    }
    
    @Column(name="COMMISSION_COMPANY_CODE", length=5)
    public String getCommissionCompanyCode() {
        return this.commissionCompanyCode;
    }
    
    public void setCommissionCompanyCode(String commissionCompanyCode) {
        this.commissionCompanyCode = commissionCompanyCode;
    }
    
    @Column(name="COMMISSION_GL_REF_CODE", length=3)
    public String getCommissionGlRefCode() {
        return this.commissionGlRefCode;
    }
    
    public void setCommissionGlRefCode(String commissionGlRefCode) {
        this.commissionGlRefCode = commissionGlRefCode;
    }
    
    @Column(name="RATE_CATEGORY", length=1)
    public Character getRateCategory() {
        return this.rateCategory;
    }
    
    public void setRateCategory(Character rateCategory) {
        this.rateCategory = rateCategory;
    }
    
    @Column(name="INST_COB_CALC_METHOD", nullable=false, length=2)
    public String getInstCobCalcMethod() {
        return this.instCobCalcMethod;
    }
    
    public void setInstCobCalcMethod(String instCobCalcMethod) {
        this.instCobCalcMethod = instCobCalcMethod;
    }
    
    @Column(name="DEP_DETERM_RULE_CODE", nullable=false, length=1)
    public char getDepDetermRuleCode() {
        return this.depDetermRuleCode;
    }
    
    public void setDepDetermRuleCode(char depDetermRuleCode) {
        this.depDetermRuleCode = depDetermRuleCode;
    }
    
    @Column(name="COB_POLICY_FLAG", nullable=false, length=1)
    public char getCobPolicyFlag() {
        return this.cobPolicyFlag;
    }
    
    public void setCobPolicyFlag(char cobPolicyFlag) {
        this.cobPolicyFlag = cobPolicyFlag;
    }
    
    @Column(name="COB_EXCLUDE_CAP_CLAIM_CODE", nullable=false, length=1)
    public char getCobExcludeCapClaimCode() {
        return this.cobExcludeCapClaimCode;
    }
    
    public void setCobExcludeCapClaimCode(char cobExcludeCapClaimCode) {
        this.cobExcludeCapClaimCode = cobExcludeCapClaimCode;
    }
    
    @Column(name="CLAIM_FILING_INDICATOR", nullable=false, length=2)
    public String getClaimFilingIndicator() {
        return this.claimFilingIndicator;
    }
    
    public void setClaimFilingIndicator(String claimFilingIndicator) {
        this.claimFilingIndicator = claimFilingIndicator;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="RATE_MODIFY_DATE", length=7)
    public Date getRateModifyDate() {
        return this.rateModifyDate;
    }
    
    public void setRateModifyDate(Date rateModifyDate) {
        this.rateModifyDate = rateModifyDate;
    }
    
    @Column(name="DENTAL_COB_CALC_METHOD", length=2)
    public String getDentalCobCalcMethod() {
        return this.dentalCobCalcMethod;
    }
    
    public void setDentalCobCalcMethod(String dentalCobCalcMethod) {
        this.dentalCobCalcMethod = dentalCobCalcMethod;
    }
    
    @Column(name="EXCLUDE_CAP_CLM_DTL", length=1)
    public Character getExcludeCapClmDtl() {
        return this.excludeCapClmDtl;
    }
    
    public void setExcludeCapClmDtl(Character excludeCapClmDtl) {
        this.excludeCapClmDtl = excludeCapClmDtl;
    }
    
    @Column(name="DEP_AGE_LIMIT", precision=2, scale=0)
    public Byte getDepAgeLimit() {
        return this.depAgeLimit;
    }
    
    public void setDepAgeLimit(Byte depAgeLimit) {
        this.depAgeLimit = depAgeLimit;
    }
    
    @Column(name="STU_AGE_LIMIT", precision=2, scale=0)
    public Byte getStuAgeLimit() {
        return this.stuAgeLimit;
    }
    
    public void setStuAgeLimit(Byte stuAgeLimit) {
        this.stuAgeLimit = stuAgeLimit;
    }
    
    @Column(name="DEP_AGE_LIMIT_ACTION", length=5)
    public String getDepAgeLimitAction() {
        return this.depAgeLimitAction;
    }
    
    public void setDepAgeLimitAction(String depAgeLimitAction) {
        this.depAgeLimitAction = depAgeLimitAction;
    }
    
    @Column(name="DEP_AGE_LIMIT_REASON", length=5)
    public String getDepAgeLimitReason() {
        return this.depAgeLimitReason;
    }
    
    public void setDepAgeLimitReason(String depAgeLimitReason) {
        this.depAgeLimitReason = depAgeLimitReason;
    }
    
    @Column(name="STU_AGE_LIMIT_ACTION", length=5)
    public String getStuAgeLimitAction() {
        return this.stuAgeLimitAction;
    }
    
    public void setStuAgeLimitAction(String stuAgeLimitAction) {
        this.stuAgeLimitAction = stuAgeLimitAction;
    }
    
    @Column(name="STU_AGE_LIMIT_REASON", length=5)
    public String getStuAgeLimitReason() {
        return this.stuAgeLimitReason;
    }
    
    public void setStuAgeLimitReason(String stuAgeLimitReason) {
        this.stuAgeLimitReason = stuAgeLimitReason;
    }
    
    @Column(name="STU_NO_VERIFICATION_ACTION", length=5)
    public String getStuNoVerificationAction() {
        return this.stuNoVerificationAction;
    }
    
    public void setStuNoVerificationAction(String stuNoVerificationAction) {
        this.stuNoVerificationAction = stuNoVerificationAction;
    }
    
    @Column(name="STU_NO_VERIFICATION_REASON", length=5)
    public String getStuNoVerificationReason() {
        return this.stuNoVerificationReason;
    }
    
    public void setStuNoVerificationReason(String stuNoVerificationReason) {
        this.stuNoVerificationReason = stuNoVerificationReason;
    }
    
    @Column(name="RECORD_STATUS", length=15)
    public String getRecordStatus() {
        return this.recordStatus;
    }
    
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }
    
    @Column(name="USER_DEFINED_1", length=30)
    public String getUserDefined1() {
        return this.userDefined1;
    }
    
    public void setUserDefined1(String userDefined1) {
        this.userDefined1 = userDefined1;
    }
    
    @Column(name="USER_DEFINED_2", length=30)
    public String getUserDefined2() {
        return this.userDefined2;
    }
    
    public void setUserDefined2(String userDefined2) {
        this.userDefined2 = userDefined2;
    }
    
    @Column(name="USER_DEFINED_3", length=30)
    public String getUserDefined3() {
        return this.userDefined3;
    }
    
    public void setUserDefined3(String userDefined3) {
        this.userDefined3 = userDefined3;
    }
    
    @Column(name="USER_DEFINED_4", length=30)
    public String getUserDefined4() {
        return this.userDefined4;
    }
    
    public void setUserDefined4(String userDefined4) {
        this.userDefined4 = userDefined4;
    }
    
    @Column(name="USER_DEFINED_5", length=30)
    public String getUserDefined5() {
        return this.userDefined5;
    }
    
    public void setUserDefined5(String userDefined5) {
        this.userDefined5 = userDefined5;
    }
    
    @Column(name="USER_DEFINED_6", length=30)
    public String getUserDefined6() {
        return this.userDefined6;
    }
    
    public void setUserDefined6(String userDefined6) {
        this.userDefined6 = userDefined6;
    }
    
    @Column(name="USER_DEFINED_7", length=30)
    public String getUserDefined7() {
        return this.userDefined7;
    }
    
    public void setUserDefined7(String userDefined7) {
        this.userDefined7 = userDefined7;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_1", length=7)
    public Date getUserDate1() {
        return this.userDate1;
    }
    
    public void setUserDate1(Date userDate1) {
        this.userDate1 = userDate1;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_2", length=7)
    public Date getUserDate2() {
        return this.userDate2;
    }
    
    public void setUserDate2(Date userDate2) {
        this.userDate2 = userDate2;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_3", length=7)
    public Date getUserDate3() {
        return this.userDate3;
    }
    
    public void setUserDate3(Date userDate3) {
        this.userDate3 = userDate3;
    }
    
    @Column(name="USER_DEFINED_8", length=30)
    public String getUserDefined8() {
        return this.userDefined8;
    }
    
    public void setUserDefined8(String userDefined8) {
        this.userDefined8 = userDefined8;
    }
    
    @Column(name="USER_DEFINED_9", length=30)
    public String getUserDefined9() {
        return this.userDefined9;
    }
    
    public void setUserDefined9(String userDefined9) {
        this.userDefined9 = userDefined9;
    }
    
    @Column(name="USER_DEFINED_10", length=30)
    public String getUserDefined10() {
        return this.userDefined10;
    }
    
    public void setUserDefined10(String userDefined10) {
        this.userDefined10 = userDefined10;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_4", length=7)
    public Date getUserDate4() {
        return this.userDate4;
    }
    
    public void setUserDate4(Date userDate4) {
        this.userDate4 = userDate4;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_5", length=7)
    public Date getUserDate5() {
        return this.userDate5;
    }
    
    public void setUserDate5(Date userDate5) {
        this.userDate5 = userDate5;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_6", length=7)
    public Date getUserDate6() {
        return this.userDate6;
    }
    
    public void setUserDate6(Date userDate6) {
        this.userDate6 = userDate6;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_7", length=7)
    public Date getUserDate7() {
        return this.userDate7;
    }
    
    public void setUserDate7(Date userDate7) {
        this.userDate7 = userDate7;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_8", length=7)
    public Date getUserDate8() {
        return this.userDate8;
    }
    
    public void setUserDate8(Date userDate8) {
        this.userDate8 = userDate8;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_9", length=7)
    public Date getUserDate9() {
        return this.userDate9;
    }
    
    public void setUserDate9(Date userDate9) {
        this.userDate9 = userDate9;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="USER_DATE_10", length=7)
    public Date getUserDate10() {
        return this.userDate10;
    }
    
    public void setUserDate10(Date userDate10) {
        this.userDate10 = userDate10;
    }
    
    @Column(name="COMMENTS", length=80)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    
    @Column(name="DEP_CONV_OPTION", length=15)
    public String getDepConvOption() {
        return this.depConvOption;
    }
    
    public void setDepConvOption(String depConvOption) {
        this.depConvOption = depConvOption;
    }
    
    @Column(name="DEP_CONV_ACTION", length=15)
    public String getDepConvAction() {
        return this.depConvAction;
    }
    
    public void setDepConvAction(String depConvAction) {
        this.depConvAction = depConvAction;
    }
    
    @Column(name="STU_CONV_OPTION", length=15)
    public String getStuConvOption() {
        return this.stuConvOption;
    }
    
    public void setStuConvOption(String stuConvOption) {
        this.stuConvOption = stuConvOption;
    }
    
    @Column(name="STU_CONV_ACTION", length=15)
    public String getStuConvAction() {
        return this.stuConvAction;
    }
    
    public void setStuConvAction(String stuConvAction) {
        this.stuConvAction = stuConvAction;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="RENEWAL_DATE", length=7)
    public Date getRenewalDate() {
        return this.renewalDate;
    }
    
    public void setRenewalDate(Date renewalDate) {
        this.renewalDate = renewalDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CONV_YEAR_START_DATE", length=7)
    public Date getConvYearStartDate() {
        return this.convYearStartDate;
    }
    
    public void setConvYearStartDate(Date convYearStartDate) {
        this.convYearStartDate = convYearStartDate;
    }
    
    @Column(name="PLAN_TYPE", length=1)
    public String getPlanType() {
        return this.planType;
    }
    
    public void setPlanType(String planType) {
        this.planType = planType;
    }
    
    @Column(name="PRICE_INDICATOR", length=15)
    public String getPriceIndicator() {
        return this.priceIndicator;
    }
    
    public void setPriceIndicator(String priceIndicator) {
        this.priceIndicator = priceIndicator;
    }
    
    @Column(name="PAR_SEARCH", length=1)
    public String getParSearch() {
        return this.parSearch;
    }
    
    public void setParSearch(String parSearch) {
        this.parSearch = parSearch;
    }
    
    @Column(name="DUAL_PS_CALC", length=2)
    public String getDualPsCalc() {
        return this.dualPsCalc;
    }
    
    public void setDualPsCalc(String dualPsCalc) {
        this.dualPsCalc = dualPsCalc;
    }
    
    @Column(name="MBRS_SSN_REQ", length=1)
    public String getMbrsSsnReq() {
        return this.mbrsSsnReq;
    }
    
    public void setMbrsSsnReq(String mbrsSsnReq) {
        this.mbrsSsnReq = mbrsSsnReq;
    }
    
    @Column(name="BENEFIT_CARRYOVER_IND", length=1)
    public String getBenefitCarryoverInd() {
        return this.benefitCarryoverInd;
    }
    
    public void setBenefitCarryoverInd(String benefitCarryoverInd) {
        this.benefitCarryoverInd = benefitCarryoverInd;
    }
    
    @Column(name="COMPARE_LOGIC_IND", length=1)
    public String getCompareLogicInd() {
        return this.compareLogicInd;
    }
    
    public void setCompareLogicInd(String compareLogicInd) {
        this.compareLogicInd = compareLogicInd;
    }
    
    @Column(name="RX_BIN", length=6)
    public String getRxBin() {
        return this.rxBin;
    }
    
    public void setRxBin(String rxBin) {
        this.rxBin = rxBin;
    }
    
    @Column(name="RX_PCN", length=10)
    public String getRxPcn() {
        return this.rxPcn;
    }
    
    public void setRxPcn(String rxPcn) {
        this.rxPcn = rxPcn;
    }
    
    @Column(name="RX_GROUP", length=15)
    public String getRxGroup() {
        return this.rxGroup;
    }
    
    public void setRxGroup(String rxGroup) {
        this.rxGroup = rxGroup;
    }
    
    @Column(name="PBP_NUMBER", length=3)
    public String getPbpNumber() {
        return this.pbpNumber;
    }
    
    public void setPbpNumber(String pbpNumber) {
        this.pbpNumber = pbpNumber;
    }




}


