package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcessingMessagesId generated by hbm2java
 */
@Embeddable
public class ProcessingMessagesId  implements java.io.Serializable {


     private Date messageDate;
     private String procedureName;
     private String grouping;
     private char class_;
     private char type;
     private String message;
     private String userId;
     private String userKeyName;
     private String userKeyValue;
     private BigDecimal seqMessageId;
     private Integer seqSessionId;
     private Character retainMessages;
     private String secondaryBusKey;
     private Short lineNumber;
     private Character displayMessage;
     private String subLine;
     private String secondaryBusKeyName;

    public ProcessingMessagesId() {
    }

	
    public ProcessingMessagesId(Date messageDate, String procedureName, String grouping, char class_, char type, String message, String userId) {
        this.messageDate = messageDate;
        this.procedureName = procedureName;
        this.grouping = grouping;
        this.class_ = class_;
        this.type = type;
        this.message = message;
        this.userId = userId;
    }
    public ProcessingMessagesId(Date messageDate, String procedureName, String grouping, char class_, char type, String message, String userId, String userKeyName, String userKeyValue, BigDecimal seqMessageId, Integer seqSessionId, Character retainMessages, String secondaryBusKey, Short lineNumber, Character displayMessage, String subLine, String secondaryBusKeyName) {
       this.messageDate = messageDate;
       this.procedureName = procedureName;
       this.grouping = grouping;
       this.class_ = class_;
       this.type = type;
       this.message = message;
       this.userId = userId;
       this.userKeyName = userKeyName;
       this.userKeyValue = userKeyValue;
       this.seqMessageId = seqMessageId;
       this.seqSessionId = seqSessionId;
       this.retainMessages = retainMessages;
       this.secondaryBusKey = secondaryBusKey;
       this.lineNumber = lineNumber;
       this.displayMessage = displayMessage;
       this.subLine = subLine;
       this.secondaryBusKeyName = secondaryBusKeyName;
    }
   

    @Column(name="MESSAGE_DATE", nullable=false, length=7)
    public Date getMessageDate() {
        return this.messageDate;
    }
    
    public void setMessageDate(Date messageDate) {
        this.messageDate = messageDate;
    }

    @Column(name="PROCEDURE_NAME", nullable=false, length=30)
    public String getProcedureName() {
        return this.procedureName;
    }
    
    public void setProcedureName(String procedureName) {
        this.procedureName = procedureName;
    }

    @Column(name="GROUPING", nullable=false, length=30)
    public String getGrouping() {
        return this.grouping;
    }
    
    public void setGrouping(String grouping) {
        this.grouping = grouping;
    }

    @Column(name="CLASS", nullable=false, length=1)
    public char getClass_() {
        return this.class_;
    }
    
    public void setClass_(char class_) {
        this.class_ = class_;
    }

    @Column(name="TYPE", nullable=false, length=1)
    public char getType() {
        return this.type;
    }
    
    public void setType(char type) {
        this.type = type;
    }

    @Column(name="MESSAGE", nullable=false, length=256)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Column(name="USER_ID", nullable=false, length=8)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name="USER_KEY_NAME", length=30)
    public String getUserKeyName() {
        return this.userKeyName;
    }
    
    public void setUserKeyName(String userKeyName) {
        this.userKeyName = userKeyName;
    }

    @Column(name="USER_KEY_VALUE", length=30)
    public String getUserKeyValue() {
        return this.userKeyValue;
    }
    
    public void setUserKeyValue(String userKeyValue) {
        this.userKeyValue = userKeyValue;
    }

    @Column(name="SEQ_MESSAGE_ID", precision=22, scale=0)
    public BigDecimal getSeqMessageId() {
        return this.seqMessageId;
    }
    
    public void setSeqMessageId(BigDecimal seqMessageId) {
        this.seqMessageId = seqMessageId;
    }

    @Column(name="SEQ_SESSION_ID", precision=9, scale=0)
    public Integer getSeqSessionId() {
        return this.seqSessionId;
    }
    
    public void setSeqSessionId(Integer seqSessionId) {
        this.seqSessionId = seqSessionId;
    }

    @Column(name="RETAIN_MESSAGES", length=1)
    public Character getRetainMessages() {
        return this.retainMessages;
    }
    
    public void setRetainMessages(Character retainMessages) {
        this.retainMessages = retainMessages;
    }

    @Column(name="SECONDARY_BUS_KEY", length=30)
    public String getSecondaryBusKey() {
        return this.secondaryBusKey;
    }
    
    public void setSecondaryBusKey(String secondaryBusKey) {
        this.secondaryBusKey = secondaryBusKey;
    }

    @Column(name="LINE_NUMBER", precision=3, scale=0)
    public Short getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(Short lineNumber) {
        this.lineNumber = lineNumber;
    }

    @Column(name="DISPLAY_MESSAGE", length=1)
    public Character getDisplayMessage() {
        return this.displayMessage;
    }
    
    public void setDisplayMessage(Character displayMessage) {
        this.displayMessage = displayMessage;
    }

    @Column(name="SUB_LINE", length=2)
    public String getSubLine() {
        return this.subLine;
    }
    
    public void setSubLine(String subLine) {
        this.subLine = subLine;
    }

    @Column(name="SECONDARY_BUS_KEY_NAME", length=30)
    public String getSecondaryBusKeyName() {
        return this.secondaryBusKeyName;
    }
    
    public void setSecondaryBusKeyName(String secondaryBusKeyName) {
        this.secondaryBusKeyName = secondaryBusKeyName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProcessingMessagesId) ) return false;
		 ProcessingMessagesId castOther = ( ProcessingMessagesId ) other; 
         
		 return ( (this.getMessageDate()==castOther.getMessageDate()) || ( this.getMessageDate()!=null && castOther.getMessageDate()!=null && this.getMessageDate().equals(castOther.getMessageDate()) ) )
 && ( (this.getProcedureName()==castOther.getProcedureName()) || ( this.getProcedureName()!=null && castOther.getProcedureName()!=null && this.getProcedureName().equals(castOther.getProcedureName()) ) )
 && ( (this.getGrouping()==castOther.getGrouping()) || ( this.getGrouping()!=null && castOther.getGrouping()!=null && this.getGrouping().equals(castOther.getGrouping()) ) )
 && (this.getClass_()==castOther.getClass_())
 && (this.getType()==castOther.getType())
 && ( (this.getMessage()==castOther.getMessage()) || ( this.getMessage()!=null && castOther.getMessage()!=null && this.getMessage().equals(castOther.getMessage()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getUserKeyName()==castOther.getUserKeyName()) || ( this.getUserKeyName()!=null && castOther.getUserKeyName()!=null && this.getUserKeyName().equals(castOther.getUserKeyName()) ) )
 && ( (this.getUserKeyValue()==castOther.getUserKeyValue()) || ( this.getUserKeyValue()!=null && castOther.getUserKeyValue()!=null && this.getUserKeyValue().equals(castOther.getUserKeyValue()) ) )
 && ( (this.getSeqMessageId()==castOther.getSeqMessageId()) || ( this.getSeqMessageId()!=null && castOther.getSeqMessageId()!=null && this.getSeqMessageId().equals(castOther.getSeqMessageId()) ) )
 && ( (this.getSeqSessionId()==castOther.getSeqSessionId()) || ( this.getSeqSessionId()!=null && castOther.getSeqSessionId()!=null && this.getSeqSessionId().equals(castOther.getSeqSessionId()) ) )
 && ( (this.getRetainMessages()==castOther.getRetainMessages()) || ( this.getRetainMessages()!=null && castOther.getRetainMessages()!=null && this.getRetainMessages().equals(castOther.getRetainMessages()) ) )
 && ( (this.getSecondaryBusKey()==castOther.getSecondaryBusKey()) || ( this.getSecondaryBusKey()!=null && castOther.getSecondaryBusKey()!=null && this.getSecondaryBusKey().equals(castOther.getSecondaryBusKey()) ) )
 && ( (this.getLineNumber()==castOther.getLineNumber()) || ( this.getLineNumber()!=null && castOther.getLineNumber()!=null && this.getLineNumber().equals(castOther.getLineNumber()) ) )
 && ( (this.getDisplayMessage()==castOther.getDisplayMessage()) || ( this.getDisplayMessage()!=null && castOther.getDisplayMessage()!=null && this.getDisplayMessage().equals(castOther.getDisplayMessage()) ) )
 && ( (this.getSubLine()==castOther.getSubLine()) || ( this.getSubLine()!=null && castOther.getSubLine()!=null && this.getSubLine().equals(castOther.getSubLine()) ) )
 && ( (this.getSecondaryBusKeyName()==castOther.getSecondaryBusKeyName()) || ( this.getSecondaryBusKeyName()!=null && castOther.getSecondaryBusKeyName()!=null && this.getSecondaryBusKeyName().equals(castOther.getSecondaryBusKeyName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMessageDate() == null ? 0 : this.getMessageDate().hashCode() );
         result = 37 * result + ( getProcedureName() == null ? 0 : this.getProcedureName().hashCode() );
         result = 37 * result + ( getGrouping() == null ? 0 : this.getGrouping().hashCode() );
         result = 37 * result + this.getClass_();
         result = 37 * result + this.getType();
         result = 37 * result + ( getMessage() == null ? 0 : this.getMessage().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getUserKeyName() == null ? 0 : this.getUserKeyName().hashCode() );
         result = 37 * result + ( getUserKeyValue() == null ? 0 : this.getUserKeyValue().hashCode() );
         result = 37 * result + ( getSeqMessageId() == null ? 0 : this.getSeqMessageId().hashCode() );
         result = 37 * result + ( getSeqSessionId() == null ? 0 : this.getSeqSessionId().hashCode() );
         result = 37 * result + ( getRetainMessages() == null ? 0 : this.getRetainMessages().hashCode() );
         result = 37 * result + ( getSecondaryBusKey() == null ? 0 : this.getSecondaryBusKey().hashCode() );
         result = 37 * result + ( getLineNumber() == null ? 0 : this.getLineNumber().hashCode() );
         result = 37 * result + ( getDisplayMessage() == null ? 0 : this.getDisplayMessage().hashCode() );
         result = 37 * result + ( getSubLine() == null ? 0 : this.getSubLine().hashCode() );
         result = 37 * result + ( getSecondaryBusKeyName() == null ? 0 : this.getSecondaryBusKeyName().hashCode() );
         return result;
   }   


}


