package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.util.*;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProcessingMessages generated by hbm2java
 */
@Entity
@Table(name="PROCESSING_MESSAGES"
    ,schema="DORIS"
)
public class ProcessingMessages extends Base.BaseEntity implements java.io.Serializable {


     private ProcessingMessagesId id;

    public ProcessingMessages() {
    }

    public ProcessingMessages(ProcessingMessagesId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="messageDate", column=@Column(name="MESSAGE_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="procedureName", column=@Column(name="PROCEDURE_NAME", nullable=false, length=30) ), 
        @AttributeOverride(name="grouping", column=@Column(name="GROUPING", nullable=false, length=30) ), 
        @AttributeOverride(name="class_", column=@Column(name="CLASS", nullable=false, length=1) ), 
        @AttributeOverride(name="type", column=@Column(name="TYPE", nullable=false, length=1) ), 
        @AttributeOverride(name="message", column=@Column(name="MESSAGE", nullable=false, length=256) ), 
        @AttributeOverride(name="userId", column=@Column(name="USER_ID", nullable=false, length=8) ), 
        @AttributeOverride(name="userKeyName", column=@Column(name="USER_KEY_NAME", length=30) ), 
        @AttributeOverride(name="userKeyValue", column=@Column(name="USER_KEY_VALUE", length=30) ), 
        @AttributeOverride(name="seqMessageId", column=@Column(name="SEQ_MESSAGE_ID", precision=22, scale=0) ), 
        @AttributeOverride(name="seqSessionId", column=@Column(name="SEQ_SESSION_ID", precision=9, scale=0) ), 
        @AttributeOverride(name="retainMessages", column=@Column(name="RETAIN_MESSAGES", length=1) ), 
        @AttributeOverride(name="secondaryBusKey", column=@Column(name="SECONDARY_BUS_KEY", length=30) ), 
        @AttributeOverride(name="lineNumber", column=@Column(name="LINE_NUMBER", precision=3, scale=0) ), 
        @AttributeOverride(name="displayMessage", column=@Column(name="DISPLAY_MESSAGE", length=1) ), 
        @AttributeOverride(name="subLine", column=@Column(name="SUB_LINE", length=2) ), 
        @AttributeOverride(name="secondaryBusKeyName", column=@Column(name="SECONDARY_BUS_KEY_NAME", length=30) ) } )
    public ProcessingMessagesId getId() {
        return this.id;
    }
    
    public void setId(ProcessingMessagesId id) {
        this.id = id;
    }




}


