package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RuleAccumBenefitCrosswalkId generated by hbm2java
 */
@Embeddable
public class RuleAccumBenefitCrosswalkId  implements java.io.Serializable {


     private String region;
     private String sourceId;
     private String externalBenefit;
     private String xcelysBrule;
     private Date effectiveDate;

    public RuleAccumBenefitCrosswalkId() {
    }

    public RuleAccumBenefitCrosswalkId(String region, String sourceId, String externalBenefit, String xcelysBrule, Date effectiveDate) {
       this.region = region;
       this.sourceId = sourceId;
       this.externalBenefit = externalBenefit;
       this.xcelysBrule = xcelysBrule;
       this.effectiveDate = effectiveDate;
    }
   

    @Column(name="REGION", nullable=false, length=1)
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }

    @Column(name="SOURCE_ID", nullable=false, length=30)
    public String getSourceId() {
        return this.sourceId;
    }
    
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }

    @Column(name="EXTERNAL_BENEFIT", nullable=false, length=30)
    public String getExternalBenefit() {
        return this.externalBenefit;
    }
    
    public void setExternalBenefit(String externalBenefit) {
        this.externalBenefit = externalBenefit;
    }

    @Column(name="XCELYS_BRULE", nullable=false, length=10)
    public String getXcelysBrule() {
        return this.xcelysBrule;
    }
    
    public void setXcelysBrule(String xcelysBrule) {
        this.xcelysBrule = xcelysBrule;
    }

    @Column(name="EFFECTIVE_DATE", nullable=false, length=7)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RuleAccumBenefitCrosswalkId) ) return false;
		 RuleAccumBenefitCrosswalkId castOther = ( RuleAccumBenefitCrosswalkId ) other; 
         
		 return ( (this.getRegion()==castOther.getRegion()) || ( this.getRegion()!=null && castOther.getRegion()!=null && this.getRegion().equals(castOther.getRegion()) ) )
 && ( (this.getSourceId()==castOther.getSourceId()) || ( this.getSourceId()!=null && castOther.getSourceId()!=null && this.getSourceId().equals(castOther.getSourceId()) ) )
 && ( (this.getExternalBenefit()==castOther.getExternalBenefit()) || ( this.getExternalBenefit()!=null && castOther.getExternalBenefit()!=null && this.getExternalBenefit().equals(castOther.getExternalBenefit()) ) )
 && ( (this.getXcelysBrule()==castOther.getXcelysBrule()) || ( this.getXcelysBrule()!=null && castOther.getXcelysBrule()!=null && this.getXcelysBrule().equals(castOther.getXcelysBrule()) ) )
 && ( (this.getEffectiveDate()==castOther.getEffectiveDate()) || ( this.getEffectiveDate()!=null && castOther.getEffectiveDate()!=null && this.getEffectiveDate().equals(castOther.getEffectiveDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRegion() == null ? 0 : this.getRegion().hashCode() );
         result = 37 * result + ( getSourceId() == null ? 0 : this.getSourceId().hashCode() );
         result = 37 * result + ( getExternalBenefit() == null ? 0 : this.getExternalBenefit().hashCode() );
         result = 37 * result + ( getXcelysBrule() == null ? 0 : this.getXcelysBrule().hashCode() );
         result = 37 * result + ( getEffectiveDate() == null ? 0 : this.getEffectiveDate().hashCode() );
         return result;
   }   


}


