package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.util.*;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RuleAccumBenefitCrosswalk generated by hbm2java
 */
@Entity
@Table(name="RULE_ACCUM_BENEFIT_CROSSWALK"
    ,schema="DORIS"
)
public class RuleAccumBenefitCrosswalk extends Base.BaseEntity implements java.io.Serializable {


     private RuleAccumBenefitCrosswalkId id;
     private Date termDate;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;

    public RuleAccumBenefitCrosswalk() {
    }

	
    public RuleAccumBenefitCrosswalk(RuleAccumBenefitCrosswalkId id) {
        this.id = id;
    }
    public RuleAccumBenefitCrosswalk(RuleAccumBenefitCrosswalkId id, Date termDate, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess) {
       this.id = id;
       this.termDate = termDate;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="region", column=@Column(name="REGION", nullable=false, length=1) ), 
        @AttributeOverride(name="sourceId", column=@Column(name="SOURCE_ID", nullable=false, length=30) ), 
        @AttributeOverride(name="externalBenefit", column=@Column(name="EXTERNAL_BENEFIT", nullable=false, length=30) ), 
        @AttributeOverride(name="xcelysBrule", column=@Column(name="XCELYS_BRULE", nullable=false, length=10) ), 
        @AttributeOverride(name="effectiveDate", column=@Column(name="EFFECTIVE_DATE", nullable=false, length=7) ) } )
    public RuleAccumBenefitCrosswalkId getId() {
        return this.id;
    }
    
    public void setId(RuleAccumBenefitCrosswalkId id) {
        this.id = id;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="TERM_DATE", length=7)
    public Date getTermDate() {
        return this.termDate;
    }
    
    public void setTermDate(Date termDate) {
        this.termDate = termDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }



  // The following is extra code specified in the hbm.xml files

         
                private BenefitRule benefitRule ;
				
				@ManyToOne(fetch=FetchType.LAZY)
			    @JoinColumn(name="XCELYS_BRULE", nullable=false,insertable=false, updatable=false)
			    public BenefitRule getBenefitRule() {
			        return this.benefitRule;
			    }
			    
			    public void setBenefitRule(BenefitRule benefitRule) {
			        this.benefitRule = benefitRule;
			    } 
			    
			
  // end of extra code specified in the hbm.xml files

}


