package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RulePlanProdMappingId generated by hbm2java
 */
@Embeddable
public class RulePlanProdMappingId  implements java.io.Serializable {


     private String region;
     private String tier1Code;
     private String tier2Code;
     private String tier3Code;
     private String medicarePlan;
     private String xcelysPlanProdCod;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;

    public RulePlanProdMappingId() {
    }

	
    public RulePlanProdMappingId(String region, String xcelysPlanProdCod) {
        this.region = region;
        this.xcelysPlanProdCod = xcelysPlanProdCod;
    }
    public RulePlanProdMappingId(String region, String tier1Code, String tier2Code, String tier3Code, String medicarePlan, String xcelysPlanProdCod, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess) {
       this.region = region;
       this.tier1Code = tier1Code;
       this.tier2Code = tier2Code;
       this.tier3Code = tier3Code;
       this.medicarePlan = medicarePlan;
       this.xcelysPlanProdCod = xcelysPlanProdCod;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
    }
   

    @Column(name="REGION", nullable=false, length=1)
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }

    @Column(name="TIER_1_CODE", length=15)
    public String getTier1Code() {
        return this.tier1Code;
    }
    
    public void setTier1Code(String tier1Code) {
        this.tier1Code = tier1Code;
    }

    @Column(name="TIER_2_CODE", length=15)
    public String getTier2Code() {
        return this.tier2Code;
    }
    
    public void setTier2Code(String tier2Code) {
        this.tier2Code = tier2Code;
    }

    @Column(name="TIER_3_CODE", length=15)
    public String getTier3Code() {
        return this.tier3Code;
    }
    
    public void setTier3Code(String tier3Code) {
        this.tier3Code = tier3Code;
    }

    @Column(name="MEDICARE_PLAN", length=15)
    public String getMedicarePlan() {
        return this.medicarePlan;
    }
    
    public void setMedicarePlan(String medicarePlan) {
        this.medicarePlan = medicarePlan;
    }

    @Column(name="XCELYS_PLAN_PROD_COD", nullable=false, length=8)
    public String getXcelysPlanProdCod() {
        return this.xcelysPlanProdCod;
    }
    
    public void setXcelysPlanProdCod(String xcelysPlanProdCod) {
        this.xcelysPlanProdCod = xcelysPlanProdCod;
    }

    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }

    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }

    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }

    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RulePlanProdMappingId) ) return false;
		 RulePlanProdMappingId castOther = ( RulePlanProdMappingId ) other; 
         
		 return ( (this.getRegion()==castOther.getRegion()) || ( this.getRegion()!=null && castOther.getRegion()!=null && this.getRegion().equals(castOther.getRegion()) ) )
 && ( (this.getTier1Code()==castOther.getTier1Code()) || ( this.getTier1Code()!=null && castOther.getTier1Code()!=null && this.getTier1Code().equals(castOther.getTier1Code()) ) )
 && ( (this.getTier2Code()==castOther.getTier2Code()) || ( this.getTier2Code()!=null && castOther.getTier2Code()!=null && this.getTier2Code().equals(castOther.getTier2Code()) ) )
 && ( (this.getTier3Code()==castOther.getTier3Code()) || ( this.getTier3Code()!=null && castOther.getTier3Code()!=null && this.getTier3Code().equals(castOther.getTier3Code()) ) )
 && ( (this.getMedicarePlan()==castOther.getMedicarePlan()) || ( this.getMedicarePlan()!=null && castOther.getMedicarePlan()!=null && this.getMedicarePlan().equals(castOther.getMedicarePlan()) ) )
 && ( (this.getXcelysPlanProdCod()==castOther.getXcelysPlanProdCod()) || ( this.getXcelysPlanProdCod()!=null && castOther.getXcelysPlanProdCod()!=null && this.getXcelysPlanProdCod().equals(castOther.getXcelysPlanProdCod()) ) )
 && ( (this.getSecurityCode()==castOther.getSecurityCode()) || ( this.getSecurityCode()!=null && castOther.getSecurityCode()!=null && this.getSecurityCode().equals(castOther.getSecurityCode()) ) )
 && ( (this.getInsertDatetime()==castOther.getInsertDatetime()) || ( this.getInsertDatetime()!=null && castOther.getInsertDatetime()!=null && this.getInsertDatetime().equals(castOther.getInsertDatetime()) ) )
 && ( (this.getInsertUser()==castOther.getInsertUser()) || ( this.getInsertUser()!=null && castOther.getInsertUser()!=null && this.getInsertUser().equals(castOther.getInsertUser()) ) )
 && ( (this.getInsertProcess()==castOther.getInsertProcess()) || ( this.getInsertProcess()!=null && castOther.getInsertProcess()!=null && this.getInsertProcess().equals(castOther.getInsertProcess()) ) )
 && ( (this.getUpdateDatetime()==castOther.getUpdateDatetime()) || ( this.getUpdateDatetime()!=null && castOther.getUpdateDatetime()!=null && this.getUpdateDatetime().equals(castOther.getUpdateDatetime()) ) )
 && ( (this.getUpdateUser()==castOther.getUpdateUser()) || ( this.getUpdateUser()!=null && castOther.getUpdateUser()!=null && this.getUpdateUser().equals(castOther.getUpdateUser()) ) )
 && ( (this.getUpdateProcess()==castOther.getUpdateProcess()) || ( this.getUpdateProcess()!=null && castOther.getUpdateProcess()!=null && this.getUpdateProcess().equals(castOther.getUpdateProcess()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRegion() == null ? 0 : this.getRegion().hashCode() );
         result = 37 * result + ( getTier1Code() == null ? 0 : this.getTier1Code().hashCode() );
         result = 37 * result + ( getTier2Code() == null ? 0 : this.getTier2Code().hashCode() );
         result = 37 * result + ( getTier3Code() == null ? 0 : this.getTier3Code().hashCode() );
         result = 37 * result + ( getMedicarePlan() == null ? 0 : this.getMedicarePlan().hashCode() );
         result = 37 * result + ( getXcelysPlanProdCod() == null ? 0 : this.getXcelysPlanProdCod().hashCode() );
         result = 37 * result + ( getSecurityCode() == null ? 0 : this.getSecurityCode().hashCode() );
         result = 37 * result + ( getInsertDatetime() == null ? 0 : this.getInsertDatetime().hashCode() );
         result = 37 * result + ( getInsertUser() == null ? 0 : this.getInsertUser().hashCode() );
         result = 37 * result + ( getInsertProcess() == null ? 0 : this.getInsertProcess().hashCode() );
         result = 37 * result + ( getUpdateDatetime() == null ? 0 : this.getUpdateDatetime().hashCode() );
         result = 37 * result + ( getUpdateUser() == null ? 0 : this.getUpdateUser().hashCode() );
         result = 37 * result + ( getUpdateProcess() == null ? 0 : this.getUpdateProcess().hashCode() );
         return result;
   }   


}


