package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StageBenefPackageMstrId generated by hbm2java
 */
@Embeddable
public class StageBenefPackageMstrId  implements java.io.Serializable {


     private String batchId;
     private int transactionId;

    public StageBenefPackageMstrId() {
    }

    public StageBenefPackageMstrId(String batchId, int transactionId) {
       this.batchId = batchId;
       this.transactionId = transactionId;
    }
   

    @Column(name="BATCH_ID", nullable=false, length=9)
    public String getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    @Column(name="TRANSACTION_ID", nullable=false, precision=9, scale=0)
    public int getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StageBenefPackageMstrId) ) return false;
		 StageBenefPackageMstrId castOther = ( StageBenefPackageMstrId ) other; 
         
		 return ( (this.getBatchId()==castOther.getBatchId()) || ( this.getBatchId()!=null && castOther.getBatchId()!=null && this.getBatchId().equals(castOther.getBatchId()) ) )
 && (this.getTransactionId()==castOther.getTransactionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBatchId() == null ? 0 : this.getBatchId().hashCode() );
         result = 37 * result + this.getTransactionId();
         return result;
   }   


}


