package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.*;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StageBenefPackageDtl generated by hbm2java
 */
@Entity
@Table(name="STAGE_BENEF_PACKAGE_DTL"
    ,schema="DORIS"
)
public class StageBenefPackageDtl extends Base.BaseEntity implements java.io.Serializable {


     private StageBenefPackageDtlId id;
     private String benefitPackageId;
     private String benefitRule;
     private Date startDate;
     private Date endDate;
     private String parProvReq;
     private String authReq;
     private String riderReqFilter;
     private String supDepRule;
     private Short noMosContFrom;
     private Short noMosContThru;
     private String securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private Integer processingOrder;
     private String riderOperator;
     private String adjustForOcPaid;
     private String parOperator;
     private String authOperator;
     private String applyPar;
     private String authLevel;
     private String applyRider;
     private String weightedValueAccum;
     private String applyPatlib;
     private String albenId;
     private String patientLiabCompareInd;
     private String applyContractType;
     private String altSchedId;
     private String reasonCode;
     private String crossAccum;
     private String applyClmInd1;
     private String applyClmInd2;
     private BigDecimal seqBenPackage;

    public StageBenefPackageDtl() {
    }

	
    public StageBenefPackageDtl(StageBenefPackageDtlId id) {
        this.id = id;
    }
    public StageBenefPackageDtl(StageBenefPackageDtlId id, String benefitPackageId, String benefitRule, Date startDate, Date endDate, String parProvReq, String authReq, String riderReqFilter, String supDepRule, Short noMosContFrom, Short noMosContThru, String securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, Integer processingOrder, String riderOperator, String adjustForOcPaid, String parOperator, String authOperator, String applyPar, String authLevel, String applyRider, String weightedValueAccum, String applyPatlib, String albenId, String patientLiabCompareInd, String applyContractType, String altSchedId, String reasonCode, String crossAccum, String applyClmInd1, String applyClmInd2, BigDecimal seqBenPackage) {
       this.id = id;
       this.benefitPackageId = benefitPackageId;
       this.benefitRule = benefitRule;
       this.startDate = startDate;
       this.endDate = endDate;
       this.parProvReq = parProvReq;
       this.authReq = authReq;
       this.riderReqFilter = riderReqFilter;
       this.supDepRule = supDepRule;
       this.noMosContFrom = noMosContFrom;
       this.noMosContThru = noMosContThru;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.processingOrder = processingOrder;
       this.riderOperator = riderOperator;
       this.adjustForOcPaid = adjustForOcPaid;
       this.parOperator = parOperator;
       this.authOperator = authOperator;
       this.applyPar = applyPar;
       this.authLevel = authLevel;
       this.applyRider = applyRider;
       this.weightedValueAccum = weightedValueAccum;
       this.applyPatlib = applyPatlib;
       this.albenId = albenId;
       this.patientLiabCompareInd = patientLiabCompareInd;
       this.applyContractType = applyContractType;
       this.altSchedId = altSchedId;
       this.reasonCode = reasonCode;
       this.crossAccum = crossAccum;
       this.applyClmInd1 = applyClmInd1;
       this.applyClmInd2 = applyClmInd2;
       this.seqBenPackage = seqBenPackage;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="batchId", column=@Column(name="BATCH_ID", nullable=false, length=9) ), 
        @AttributeOverride(name="transactionId", column=@Column(name="TRANSACTION_ID", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="seqNo", column=@Column(name="SEQ_NO", nullable=false, precision=22, scale=0) ) } )
    public StageBenefPackageDtlId getId() {
        return this.id;
    }
    
    public void setId(StageBenefPackageDtlId id) {
        this.id = id;
    }
    
    @Column(name="BENEFIT_PACKAGE_ID", length=8)
    public String getBenefitPackageId() {
        return this.benefitPackageId;
    }
    
    public void setBenefitPackageId(String benefitPackageId) {
        this.benefitPackageId = benefitPackageId;
    }
    
    @Column(name="BENEFIT_RULE", length=10)
    public String getBenefitRule() {
        return this.benefitRule;
    }
    
    public void setBenefitRule(String benefitRule) {
        this.benefitRule = benefitRule;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=7)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=7)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
    @Column(name="PAR_PROV_REQ", length=1)
    public String getParProvReq() {
        return this.parProvReq;
    }
    
    public void setParProvReq(String parProvReq) {
        this.parProvReq = parProvReq;
    }
    
    @Column(name="AUTH_REQ", length=1)
    public String getAuthReq() {
        return this.authReq;
    }
    
    public void setAuthReq(String authReq) {
        this.authReq = authReq;
    }
    
    @Column(name="RIDER_REQ_FILTER", length=20)
    public String getRiderReqFilter() {
        return this.riderReqFilter;
    }
    
    public void setRiderReqFilter(String riderReqFilter) {
        this.riderReqFilter = riderReqFilter;
    }
    
    @Column(name="SUP_DEP_RULE", length=1)
    public String getSupDepRule() {
        return this.supDepRule;
    }
    
    public void setSupDepRule(String supDepRule) {
        this.supDepRule = supDepRule;
    }
    
    @Column(name="NO_MOS_CONT_FROM", precision=3, scale=0)
    public Short getNoMosContFrom() {
        return this.noMosContFrom;
    }
    
    public void setNoMosContFrom(Short noMosContFrom) {
        this.noMosContFrom = noMosContFrom;
    }
    
    @Column(name="NO_MOS_CONT_THRU", precision=3, scale=0)
    public Short getNoMosContThru() {
        return this.noMosContThru;
    }
    
    public void setNoMosContThru(Short noMosContThru) {
        this.noMosContThru = noMosContThru;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public String getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="PROCESSING_ORDER", precision=7, scale=0)
    public Integer getProcessingOrder() {
        return this.processingOrder;
    }
    
    public void setProcessingOrder(Integer processingOrder) {
        this.processingOrder = processingOrder;
    }
    
    @Column(name="RIDER_OPERATOR", length=2)
    public String getRiderOperator() {
        return this.riderOperator;
    }
    
    public void setRiderOperator(String riderOperator) {
        this.riderOperator = riderOperator;
    }
    
    @Column(name="ADJUST_FOR_OC_PAID", length=1)
    public String getAdjustForOcPaid() {
        return this.adjustForOcPaid;
    }
    
    public void setAdjustForOcPaid(String adjustForOcPaid) {
        this.adjustForOcPaid = adjustForOcPaid;
    }
    
    @Column(name="PAR_OPERATOR", length=2)
    public String getParOperator() {
        return this.parOperator;
    }
    
    public void setParOperator(String parOperator) {
        this.parOperator = parOperator;
    }
    
    @Column(name="AUTH_OPERATOR", length=2)
    public String getAuthOperator() {
        return this.authOperator;
    }
    
    public void setAuthOperator(String authOperator) {
        this.authOperator = authOperator;
    }
    
    @Column(name="APPLY_PAR", length=1)
    public String getApplyPar() {
        return this.applyPar;
    }
    
    public void setApplyPar(String applyPar) {
        this.applyPar = applyPar;
    }
    
    @Column(name="AUTH_LEVEL", length=1)
    public String getAuthLevel() {
        return this.authLevel;
    }
    
    public void setAuthLevel(String authLevel) {
        this.authLevel = authLevel;
    }
    
    @Column(name="APPLY_RIDER", length=1)
    public String getApplyRider() {
        return this.applyRider;
    }
    
    public void setApplyRider(String applyRider) {
        this.applyRider = applyRider;
    }
    
    @Column(name="WEIGHTED_VALUE_ACCUM", length=8)
    public String getWeightedValueAccum() {
        return this.weightedValueAccum;
    }
    
    public void setWeightedValueAccum(String weightedValueAccum) {
        this.weightedValueAccum = weightedValueAccum;
    }
    
    @Column(name="APPLY_PATLIB", length=1)
    public String getApplyPatlib() {
        return this.applyPatlib;
    }
    
    public void setApplyPatlib(String applyPatlib) {
        this.applyPatlib = applyPatlib;
    }
    
    @Column(name="ALBEN_ID", length=8)
    public String getAlbenId() {
        return this.albenId;
    }
    
    public void setAlbenId(String albenId) {
        this.albenId = albenId;
    }
    
    @Column(name="PATIENT_LIAB_COMPARE_IND", length=1)
    public String getPatientLiabCompareInd() {
        return this.patientLiabCompareInd;
    }
    
    public void setPatientLiabCompareInd(String patientLiabCompareInd) {
        this.patientLiabCompareInd = patientLiabCompareInd;
    }
    
    @Column(name="APPLY_CONTRACT_TYPE", length=1)
    public String getApplyContractType() {
        return this.applyContractType;
    }
    
    public void setApplyContractType(String applyContractType) {
        this.applyContractType = applyContractType;
    }
    
    @Column(name="ALT_SCHED_ID", length=1)
    public String getAltSchedId() {
        return this.altSchedId;
    }
    
    public void setAltSchedId(String altSchedId) {
        this.altSchedId = altSchedId;
    }
    
    @Column(name="REASON_CODE", length=5)
    public String getReasonCode() {
        return this.reasonCode;
    }
    
    public void setReasonCode(String reasonCode) {
        this.reasonCode = reasonCode;
    }
    
    @Column(name="CROSS_ACCUM", length=1)
    public String getCrossAccum() {
        return this.crossAccum;
    }
    
    public void setCrossAccum(String crossAccum) {
        this.crossAccum = crossAccum;
    }
    
    @Column(name="APPLY_CLM_IND_1", length=1)
    public String getApplyClmInd1() {
        return this.applyClmInd1;
    }
    
    public void setApplyClmInd1(String applyClmInd1) {
        this.applyClmInd1 = applyClmInd1;
    }
    
    @Column(name="APPLY_CLM_IND_2", length=1)
    public String getApplyClmInd2() {
        return this.applyClmInd2;
    }
    
    public void setApplyClmInd2(String applyClmInd2) {
        this.applyClmInd2 = applyClmInd2;
    }
    
    @Column(name="SEQ_BEN_PACKAGE", precision=22, scale=0)
    public BigDecimal getSeqBenPackage() {
        return this.seqBenPackage;
    }
    
    public void setSeqBenPackage(BigDecimal seqBenPackage) {
        this.seqBenPackage = seqBenPackage;
    }




}


