package Xcelys.Entity;
// Generated Sep 20, 2011 10:12:32 AM by Hibernate Tools 3.2.0.CR1


import java.util.*;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TradingPartnerMaster generated by hbm2java
 */
@Entity
@Table(name="TRADING_PARTNER_MASTER"
    ,schema="DORIS"
)
public class TradingPartnerMaster extends Base.BaseEntity implements java.io.Serializable {


     private String tradingPartnerId;
     private String tradingPartnerName;
     private Character tradingPartnerType;
     private String addressLine1;
     private String addressLine2;
     private String city;
     private String state;
     private String zipCode;
     private String country;
     private String contactName;
     private String phoneNumber;
     private String faxNumber;
     private String email;
     private String userDefined1;
     private String userDefined2;
     private String userDefined3;
     private String userDefined4;
     private String userDefined5;
     private String userDefined6;
     private String userDefined7;
     private String comments;
     private Character securityCode;
     private Date insertDatetime;
     private String insertUser;
     private String insertProcess;
     private Date updateDatetime;
     private String updateUser;
     private String updateProcess;
     private String ediAccessNumber;

    public TradingPartnerMaster() {
    }

	
    public TradingPartnerMaster(String tradingPartnerId, String tradingPartnerName) {
        this.tradingPartnerId = tradingPartnerId;
        this.tradingPartnerName = tradingPartnerName;
    }
    public TradingPartnerMaster(String tradingPartnerId, String tradingPartnerName, Character tradingPartnerType, String addressLine1, String addressLine2, String city, String state, String zipCode, String country, String contactName, String phoneNumber, String faxNumber, String email, String userDefined1, String userDefined2, String userDefined3, String userDefined4, String userDefined5, String userDefined6, String userDefined7, String comments, Character securityCode, Date insertDatetime, String insertUser, String insertProcess, Date updateDatetime, String updateUser, String updateProcess, String ediAccessNumber) {
       this.tradingPartnerId = tradingPartnerId;
       this.tradingPartnerName = tradingPartnerName;
       this.tradingPartnerType = tradingPartnerType;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.city = city;
       this.state = state;
       this.zipCode = zipCode;
       this.country = country;
       this.contactName = contactName;
       this.phoneNumber = phoneNumber;
       this.faxNumber = faxNumber;
       this.email = email;
       this.userDefined1 = userDefined1;
       this.userDefined2 = userDefined2;
       this.userDefined3 = userDefined3;
       this.userDefined4 = userDefined4;
       this.userDefined5 = userDefined5;
       this.userDefined6 = userDefined6;
       this.userDefined7 = userDefined7;
       this.comments = comments;
       this.securityCode = securityCode;
       this.insertDatetime = insertDatetime;
       this.insertUser = insertUser;
       this.insertProcess = insertProcess;
       this.updateDatetime = updateDatetime;
       this.updateUser = updateUser;
       this.updateProcess = updateProcess;
       this.ediAccessNumber = ediAccessNumber;
    }
   
     @Id 
    
    @Column(name="TRADING_PARTNER_ID", nullable=false, length=15)
    public String getTradingPartnerId() {
        return this.tradingPartnerId;
    }
    
    public void setTradingPartnerId(String tradingPartnerId) {
        this.tradingPartnerId = tradingPartnerId;
    }
    
    @Column(name="TRADING_PARTNER_NAME", nullable=false, length=40)
    public String getTradingPartnerName() {
        return this.tradingPartnerName;
    }
    
    public void setTradingPartnerName(String tradingPartnerName) {
        this.tradingPartnerName = tradingPartnerName;
    }
    
    @Column(name="TRADING_PARTNER_TYPE", length=1)
    public Character getTradingPartnerType() {
        return this.tradingPartnerType;
    }
    
    public void setTradingPartnerType(Character tradingPartnerType) {
        this.tradingPartnerType = tradingPartnerType;
    }
    
    @Column(name="ADDRESS_LINE_1", length=40)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    
    @Column(name="ADDRESS_LINE_2", length=40)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    
    @Column(name="CITY", length=30)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="STATE", length=6)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="ZIP_CODE", length=15)
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    
    @Column(name="COUNTRY", length=20)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="CONTACT_NAME", length=60)
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    
    @Column(name="PHONE_NUMBER", length=20)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    @Column(name="FAX_NUMBER", length=20)
    public String getFaxNumber() {
        return this.faxNumber;
    }
    
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }
    
    @Column(name="EMAIL", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="USER_DEFINED_1", length=15)
    public String getUserDefined1() {
        return this.userDefined1;
    }
    
    public void setUserDefined1(String userDefined1) {
        this.userDefined1 = userDefined1;
    }
    
    @Column(name="USER_DEFINED_2", length=15)
    public String getUserDefined2() {
        return this.userDefined2;
    }
    
    public void setUserDefined2(String userDefined2) {
        this.userDefined2 = userDefined2;
    }
    
    @Column(name="USER_DEFINED_3", length=15)
    public String getUserDefined3() {
        return this.userDefined3;
    }
    
    public void setUserDefined3(String userDefined3) {
        this.userDefined3 = userDefined3;
    }
    
    @Column(name="USER_DEFINED_4", length=15)
    public String getUserDefined4() {
        return this.userDefined4;
    }
    
    public void setUserDefined4(String userDefined4) {
        this.userDefined4 = userDefined4;
    }
    
    @Column(name="USER_DEFINED_5", length=15)
    public String getUserDefined5() {
        return this.userDefined5;
    }
    
    public void setUserDefined5(String userDefined5) {
        this.userDefined5 = userDefined5;
    }
    
    @Column(name="USER_DEFINED_6", length=15)
    public String getUserDefined6() {
        return this.userDefined6;
    }
    
    public void setUserDefined6(String userDefined6) {
        this.userDefined6 = userDefined6;
    }
    
    @Column(name="USER_DEFINED_7", length=15)
    public String getUserDefined7() {
        return this.userDefined7;
    }
    
    public void setUserDefined7(String userDefined7) {
        this.userDefined7 = userDefined7;
    }
    
    @Column(name="COMMENTS", length=256)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    
    @Column(name="SECURITY_CODE", length=1)
    public Character getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(Character securityCode) {
        this.securityCode = securityCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSERT_DATETIME", length=7)
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }
    
    @Column(name="INSERT_USER", length=8)
    public String getInsertUser() {
        return this.insertUser;
    }
    
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }
    
    @Column(name="INSERT_PROCESS", length=8)
    public String getInsertProcess() {
        return this.insertProcess;
    }
    
    public void setInsertProcess(String insertProcess) {
        this.insertProcess = insertProcess;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATETIME", length=7)
    public Date getUpdateDatetime() {
        return this.updateDatetime;
    }
    
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
    
    @Column(name="UPDATE_USER", length=8)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    
    @Column(name="UPDATE_PROCESS", length=8)
    public String getUpdateProcess() {
        return this.updateProcess;
    }
    
    public void setUpdateProcess(String updateProcess) {
        this.updateProcess = updateProcess;
    }
    
    @Column(name="EDI_ACCESS_NUMBER", length=20)
    public String getEdiAccessNumber() {
        return this.ediAccessNumber;
    }
    
    public void setEdiAccessNumber(String ediAccessNumber) {
        this.ediAccessNumber = ediAccessNumber;
    }




}


